
 
 
 
 

// Generated helper templates
// Generated items
// Blaze\Blaze.DataModel\DatabaseModel\Res_VisionPrescription_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_VisionPrescription_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_VisionPrescription_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_VisionPrescription_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_VisionPrescription_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_VisionPrescription_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ValueSet_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ValueSet_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ValueSet_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ValueSet_Index_reference_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ValueSet_Index_context_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ValueSet_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ValueSet_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_TestScript_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_TestScript_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_TestScript_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_TestScript_Index_testscript_test_capability_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_TestScript_Index_testscript_setup_capability_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_TestScript_Index_testscript_capability_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_TestScript_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_TestScript_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Task_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Task_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Task_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Task_Index_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Task_Index_performer_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Task_Index_failure_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Task_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Task_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyRequest_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyRequest_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyRequest_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyRequest_Index_supplier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyRequest_Index_kind_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyRequest_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyRequest_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyDelivery_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyDelivery_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyDelivery_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyDelivery_Index_receiver_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyDelivery_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyDelivery_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_substance_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_quantity_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_expiry_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_container_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_category_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Subscription_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Subscription_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Subscription_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Subscription_Index_contact_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Subscription_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Subscription_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureMap_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureMap_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureMap_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureMap_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureMap_Index_context_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureMap_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureMap_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_valueset_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_path_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_ext_context_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_context_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_base_path_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_Index_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_Index_parent_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_Index_container_id_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_Index_container_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_Index_bodysite_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Slot_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Slot_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Slot_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Slot_Index_slot_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Slot_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Slot_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Slot_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Sequence_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Sequence_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Sequence_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Sequence_Index_species_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Sequence_Index_chromosome_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Sequence_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Sequence_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SearchParameter_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SearchParameter_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SearchParameter_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SearchParameter_Index_target_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SearchParameter_Index_context_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SearchParameter_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SearchParameter_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Schedule_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Schedule_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Schedule_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Schedule_Index_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Schedule_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Schedule_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Schedule_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RiskAssessment_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RiskAssessment_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RiskAssessment_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RiskAssessment_Index_method_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RiskAssessment_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RiskAssessment_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_telecom_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_phonetic_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_phone_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_name_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_email_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_address_use_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_address_state_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_address_postalcode_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_address_country_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_address_city_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_address_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest_Index_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest_Index_specialty_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest_Index_recipient_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest_Index_priority_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest_Index_basedon_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_QuestionnaireResponse_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_QuestionnaireResponse_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_QuestionnaireResponse_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_QuestionnaireResponse_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_QuestionnaireResponse_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Questionnaire_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Questionnaire_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Questionnaire_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Questionnaire_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Questionnaire_Index_context_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Questionnaire_Index_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Questionnaire_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Questionnaire_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_userid_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_target_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_sig_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_patient_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_entity_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_entity_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_agent_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Protocol_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Protocol_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Protocol_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Protocol_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Protocol_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Protocol_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessResponse_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessResponse_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessResponse_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessResponse_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessResponse_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessResponse_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessRequest_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessRequest_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessRequest_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessRequest_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessRequest_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessRequest_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcedureRequest_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcedureRequest_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcedureRequest_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcedureRequest_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcedureRequest_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcedureRequest_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Procedure_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Procedure_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Procedure_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Procedure_Index_performer_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Procedure_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Procedure_Index_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Procedure_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Procedure_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_telecom_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_specialty_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_role_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_phone_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_location_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_email_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_telecom_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_specialty_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_role_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_phonetic_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_phone_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_organization_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_name_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_location_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_given_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_family_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_email_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_communication_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_address_use_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_address_state_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_address_postalcode_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_address_country_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_address_city_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_address_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_telecom_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_relatedperson_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_practitioner_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_phonetic_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_phone_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_patient_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_name_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_link_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_email_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_address_use_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_address_state_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_address_postalcode_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_address_country_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_address_city_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_address_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentReconciliation_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentReconciliation_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentReconciliation_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentReconciliation_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentReconciliation_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentReconciliation_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentNotice_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentNotice_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentNotice_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentNotice_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentNotice_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentNotice_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_ethnicity_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_race_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_telecom_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_phonetic_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_phone_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_name_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_link_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_language_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_given_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_family_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_email_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_careprovider_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_animal_species_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_animal_breed_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_address_use_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_address_state_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_address_postalcode_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_address_country_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_address_city_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_address_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Parameters_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Parameters_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Parameters_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Parameters_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Parameters_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_address_use_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_address_state_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_address_postalcode_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_address_country_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_address_city_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_address_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderSet_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderSet_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderSet_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderSet_Index_topic_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderSet_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderSet_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderSet_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderResponse_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderResponse_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderResponse_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderResponse_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderResponse_Index_fulfillment_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderResponse_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderResponse_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Order_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Order_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Order_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Order_Index_when_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Order_Index_when_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Order_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Order_Index_detail_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Order_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Order_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationOutcome_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationOutcome_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationOutcome_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationOutcome_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationOutcome_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationDefinition_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationDefinition_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationDefinition_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationDefinition_Index_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationDefinition_Index_paramprofile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationDefinition_Index_context_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationDefinition_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationDefinition_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_related_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_related_target_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_performer_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_data_absent_reason_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_component_value_string_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_component_value_quantity_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_component_value_concept_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_component_data_absent_reason_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_component_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_category_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder_Index_supplement_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder_Index_oraldiet_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder_Index_formula_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder_Index_additive_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_value_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_telecom_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_period_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_id_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_context_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_contact_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ModuleDefinition_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ModuleDefinition_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ModuleDefinition_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ModuleDefinition_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ModuleDefinition_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MessageHeader_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MessageHeader_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MessageHeader_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MessageHeader_Index_target_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MessageHeader_Index_destination_uri_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MessageHeader_Index_destination_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MessageHeader_Index_data_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MessageHeader_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MessageHeader_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationStatement_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationStatement_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationStatement_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationStatement_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationStatement_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationStatement_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationOrder_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationOrder_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationOrder_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationOrder_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationOrder_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationOrder_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationDispense_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationDispense_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationDispense_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationDispense_Index_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationDispense_Index_responsibleparty_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationDispense_Index_receiver_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationDispense_Index_prescription_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationDispense_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationDispense_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationAdministration_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationAdministration_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationAdministration_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationAdministration_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationAdministration_Index_device_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationAdministration_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationAdministration_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_package_item_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_package_item_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_ingredient_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_ingredient_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_form_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_container_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Media_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Media_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Media_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Media_Index_view_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Media_Index_subtype_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Media_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Media_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Media_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MeasureReport_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MeasureReport_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MeasureReport_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MeasureReport_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MeasureReport_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Measure_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Measure_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Measure_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Measure_Index_topic_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Measure_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Measure_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Measure_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Location_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Location_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Location_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Location_Index_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Location_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Location_Index_address_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Location_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Location_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List_Index_notes_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List_Index_item_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List_Index_empty_reason_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List_Index_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Linkage_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Linkage_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Linkage_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Linkage_Index_source_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Linkage_Index_item_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Linkage_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Linkage_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Library_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Library_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Library_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Library_Index_topic_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Library_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Library_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Library_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImplementationGuide_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImplementationGuide_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImplementationGuide_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImplementationGuide_Index_resource_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImplementationGuide_Index_dependency_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImplementationGuide_Index_context_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImplementationGuide_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImplementationGuide_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_vaccine_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_support_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_status_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_information_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_dose_sequence_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_dose_number_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_date_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_vaccine_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_reason_not_given_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_reason_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_reaction_date_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_reaction_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_dose_sequence_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_uid_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_series_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_order_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_modality_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_dicom_class_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_bodysite_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingObjectSelection_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingObjectSelection_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingObjectSelection_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingObjectSelection_Index_title_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingObjectSelection_Index_selected_study_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingObjectSelection_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingObjectSelection_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingExcerpt_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingExcerpt_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingExcerpt_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingExcerpt_Index_title_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingExcerpt_Index_selected_study_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingExcerpt_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingExcerpt_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_Index_servicetype_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_Index_servicecategory_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_Index_programname_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_Index_location_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_Index_characteristic_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_GuidanceResponse_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_GuidanceResponse_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_GuidanceResponse_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_GuidanceResponse_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_GuidanceResponse_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_Index_value_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_Index_member_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_Index_exclude_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_Index_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_Index_characteristic_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Goal_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Goal_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Goal_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Goal_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Goal_Index_category_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Goal_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Goal_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Flag_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Flag_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Flag_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Flag_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Flag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_FamilyMemberHistory_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_FamilyMemberHistory_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_FamilyMemberHistory_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_FamilyMemberHistory_Index_relationship_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_FamilyMemberHistory_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_FamilyMemberHistory_Index_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_FamilyMemberHistory_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_FamilyMemberHistory_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExplanationOfBenefit_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExplanationOfBenefit_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExplanationOfBenefit_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExplanationOfBenefit_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExplanationOfBenefit_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExplanationOfBenefit_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExpansionProfile_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExpansionProfile_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExpansionProfile_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExpansionProfile_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExpansionProfile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EpisodeOfCare_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EpisodeOfCare_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EpisodeOfCare_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EpisodeOfCare_Index_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EpisodeOfCare_Index_incomingreferral_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EpisodeOfCare_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EpisodeOfCare_Index_condition_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EpisodeOfCare_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EpisodeOfCare_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentResponse_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentResponse_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentResponse_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentResponse_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentResponse_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentResponse_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentRequest_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentRequest_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentRequest_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentRequest_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentRequest_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentRequest_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_special_arrangement_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_reason_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_procedure_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_practitioner_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_participant_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_participant_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_location_period_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_location_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_indication_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_incomingreferral_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_episodeofcare_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_condition_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityResponse_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityResponse_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityResponse_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityResponse_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityResponse_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityResponse_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityRequest_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityRequest_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityRequest_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityRequest_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityRequest_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityRequest_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_setting_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_securitylabel_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_relation_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_relatesto_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_related_ref_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_related_id_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_location_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_language_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_format_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_facility_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_event_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_class_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_author_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_related_ref_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_related_id_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_recipient_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_content_ref_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_author_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_specimen_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_result_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_request_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_image_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_diagnosis_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_category_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_specimen_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_item_status_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_item_past_status_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_item_date_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_event_status_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_event_date_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_bodysite_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_actor_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseStatement_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseStatement_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseStatement_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseStatement_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseStatement_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseRequest_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseRequest_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseRequest_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseRequest_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseRequest_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceMetric_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceMetric_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceMetric_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceMetric_Index_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceMetric_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceMetric_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceComponent_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceComponent_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceComponent_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceComponent_Index_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceComponent_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceComponent_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Device_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Device_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Device_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Device_Index_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Device_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Device_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Device_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DetectedIssue_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DetectedIssue_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DetectedIssue_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DetectedIssue_Index_implicated_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DetectedIssue_Index_category_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DetectedIssue_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DetectedIssue_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportServiceModule_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportServiceModule_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportServiceModule_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportServiceModule_Index_topic_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportServiceModule_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportServiceModule_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportServiceModule_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportRule_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportRule_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportRule_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportRule_Index_topic_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportRule_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportRule_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportRule_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DataElement_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DataElement_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DataElement_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DataElement_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DataElement_Index_description_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DataElement_Index_context_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DataElement_Index_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DataElement_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DataElement_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Coverage_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Coverage_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Coverage_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Coverage_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Coverage_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Coverage_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_ttopic_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_topic_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_subject_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_signer_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_patient_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_domain_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_authority_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_agent_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_supported_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_securityservice_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_resourceprofile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_resource_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_mode_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_format_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_event_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_context_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_stage_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_severity_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_evidence_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_category_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_body_site_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_target_system_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_target_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_source_system_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_source_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_product_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_dependson_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_context_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_section_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_period_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_entry_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_context_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_class_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_author_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_attester_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CompartmentDefinition_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CompartmentDefinition_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CompartmentDefinition_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CompartmentDefinition_Index_resource_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CompartmentDefinition_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CompartmentDefinition_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest_Index_recipient_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest_Index_priority_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest_Index_medium_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest_Index_category_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Communication_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Communication_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Communication_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Communication_Index_recipient_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Communication_Index_medium_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Communication_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Communication_Index_category_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Communication_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Communication_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CodeSystem_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CodeSystem_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CodeSystem_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CodeSystem_Index_language_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CodeSystem_Index_context_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CodeSystem_Index_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CodeSystem_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CodeSystem_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_ruledout_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_resolved_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_problem_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_plan_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_investigation_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_finding_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_action_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClaimResponse_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClaimResponse_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClaimResponse_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClaimResponse_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClaimResponse_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClaimResponse_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Claim_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Claim_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Claim_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Claim_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Claim_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Claim_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CareTeam_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CareTeam_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CareTeam_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CareTeam_Index_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CareTeam_Index_status_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CareTeam_Index_participant_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CareTeam_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CareTeam_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CareTeam_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_relatedplan_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_relatedcode_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_performer_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_participant_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_goal_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_condition_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_activityreference_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_activitydate_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_activitycode_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Bundle_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Bundle_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Bundle_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Bundle_Index_message_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Bundle_Index_composition_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Bundle_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Bundle_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_BodySite_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_BodySite_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_BodySite_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_BodySite_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_BodySite_Index_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_BodySite_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_BodySite_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Binary_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Binary_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Binary_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Binary_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Binary_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Basic_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Basic_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Basic_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Basic_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Basic_Index_code_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Basic_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Basic_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_user_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_subtype_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_policy_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_patient_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_entity_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_entity_name_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_entity_id_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_entity_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_altid_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_agent_name_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_agent_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_address_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AppointmentResponse_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AppointmentResponse_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AppointmentResponse_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AppointmentResponse_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AppointmentResponse_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AppointmentResponse_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_service_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_practitioner_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_patient_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_part_status_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_location_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_appointment_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_actor_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_Index_substance_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_Index_severity_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_Index_route_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_Index_onset_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_Index_manifestation_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Account_Index_tag_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Account_Index_security_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Account_Index_profile_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Account_Index_type_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Account_Index_identifier_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Account_History_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Account_Configuration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Blaze_RootUrlStore_Configuration.cs
