
 
 
 
 


// Generated helper templates
// Blaze\Blaze.DataModel\DatabaseModel\_DbEntityModelGenerator.txt4
// Generated items
// Blaze\Blaze.DataModel\DatabaseModel\Res_VisionPrescription_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_VisionPrescription_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_VisionPrescription_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_VisionPrescription_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_VisionPrescription_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_VisionPrescription.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ValueSet_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ValueSet_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ValueSet_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ValueSet_Index_reference.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ValueSet_Index_context.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ValueSet_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ValueSet.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_TestScript_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_TestScript_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_TestScript_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_TestScript_Index_testscript_test_capability.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_TestScript_Index_testscript_setup_capability.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_TestScript_Index_testscript_capability.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_TestScript_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_TestScript.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Task_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Task_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Task_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Task_Index_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Task_Index_performer.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Task_Index_failure.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Task_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Task.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyRequest_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyRequest_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyRequest_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyRequest_Index_supplier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyRequest_Index_kind.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyRequest_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyRequest.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyDelivery_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyDelivery_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyDelivery_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyDelivery_Index_receiver.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyDelivery_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SupplyDelivery.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_substance.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_quantity.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_expiry.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_container_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_Index_category.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Substance.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Subscription_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Subscription_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Subscription_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Subscription_Index_contact.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Subscription_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Subscription.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureMap_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureMap_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureMap_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureMap_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureMap_Index_context.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureMap_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureMap.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_valueset.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_path.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_ext_context.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_context.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_Index_base_path.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_StructureDefinition.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_Index_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_Index_parent.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_Index_container_id.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_Index_container.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_Index_bodysite.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Specimen.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Slot_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Slot_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Slot_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Slot_Index_slot_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Slot_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Slot_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Slot.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Sequence_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Sequence_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Sequence_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Sequence_Index_species.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Sequence_Index_chromosome.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Sequence_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Sequence.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SearchParameter_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SearchParameter_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SearchParameter_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SearchParameter_Index_target.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SearchParameter_Index_context.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SearchParameter_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_SearchParameter.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Schedule_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Schedule_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Schedule_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Schedule_Index_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Schedule_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Schedule_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Schedule.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RiskAssessment_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RiskAssessment_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RiskAssessment_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RiskAssessment_Index_method.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RiskAssessment_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RiskAssessment.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_telecom.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_phonetic.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_phone.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_name.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_email.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_address_use.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_address_state.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_address_postalcode.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_address_country.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_address_city.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_Index_address.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_RelatedPerson.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest_Index_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest_Index_specialty.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest_Index_recipient.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest_Index_priority.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest_Index_basedon.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ReferralRequest.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_QuestionnaireResponse_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_QuestionnaireResponse_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_QuestionnaireResponse_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_QuestionnaireResponse_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_QuestionnaireResponse.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Questionnaire_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Questionnaire_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Questionnaire_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Questionnaire_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Questionnaire_Index_context.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Questionnaire_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Questionnaire_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Questionnaire.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_userid.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_target.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_sig.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_patient.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_entity_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_entity.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_Index_agent.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Provenance.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Protocol_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Protocol_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Protocol_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Protocol_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Protocol_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Protocol.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessResponse_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessResponse_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessResponse_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessResponse_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessResponse_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessResponse.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessRequest_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessRequest_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessRequest_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessRequest_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessRequest_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcessRequest.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcedureRequest_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcedureRequest_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcedureRequest_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcedureRequest_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcedureRequest_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ProcedureRequest.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Procedure_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Procedure_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Procedure_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Procedure_Index_performer.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Procedure_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Procedure_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Procedure_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Procedure.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_telecom.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_specialty.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_role.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_phone.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_location.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_Index_email.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PractitionerRole.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_telecom.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_specialty.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_role.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_phonetic.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_phone.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_organization.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_name.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_location.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_given.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_family.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_email.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_communication.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_address_use.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_address_state.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_address_postalcode.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_address_country.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_address_city.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_Index_address.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Practitioner.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_telecom.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_relatedperson.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_practitioner.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_phonetic.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_phone.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_patient.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_name.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_link.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_email.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_address_use.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_address_state.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_address_postalcode.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_address_country.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_address_city.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_Index_address.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Person.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentReconciliation_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentReconciliation_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentReconciliation_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentReconciliation_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentReconciliation_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentReconciliation.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentNotice_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentNotice_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentNotice_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentNotice_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentNotice_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_PaymentNotice.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_telecom.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_phonetic.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_phone.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_name.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_link.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_language.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_given.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_family.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_email.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_careprovider.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_animal_species.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_animal_breed.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_address_use.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_address_state.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_address_postalcode.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_address_country.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_address_city.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_Index_address.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Patient.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Parameters_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Parameters_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Parameters_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Parameters_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Parameters.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_address_use.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_address_state.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_address_postalcode.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_address_country.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_address_city.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_Index_address.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Organization.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderSet_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderSet_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderSet_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderSet_Index_topic.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderSet_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderSet_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderSet.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderResponse_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderResponse_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderResponse_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderResponse_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderResponse_Index_fulfillment.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderResponse_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OrderResponse.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Order_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Order_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Order_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Order_Index_when_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Order_Index_when.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Order_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Order_Index_detail.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Order_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Order.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationOutcome_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationOutcome_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationOutcome_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationOutcome_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationOutcome.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationDefinition_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationDefinition_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationDefinition_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationDefinition_Index_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationDefinition_Index_paramprofile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationDefinition_Index_context.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationDefinition_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_OperationDefinition.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_value_concept.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_related_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_related_target.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_performer.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_data_absent_reason.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_component_value_string.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_component_value_quantity.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_component_value_concept.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_component_data_absent_reason.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_component_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_Index_category.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Observation.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder_Index_supplement.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder_Index_oraldiet.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder_Index_formula.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder_Index_additive.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NutritionOrder.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_value.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_telecom.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_period.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_id_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_context.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_Index_contact.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_NamingSystem.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ModuleDefinition_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ModuleDefinition_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ModuleDefinition_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ModuleDefinition_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ModuleDefinition.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MessageHeader_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MessageHeader_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MessageHeader_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MessageHeader_Index_target.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MessageHeader_Index_destination_uri.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MessageHeader_Index_destination.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MessageHeader_Index_data.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MessageHeader_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MessageHeader.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationStatement_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationStatement_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationStatement_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationStatement_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationStatement_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationStatement_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationStatement.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationOrder_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationOrder_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationOrder_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationOrder_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationOrder_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationOrder_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationOrder.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationDispense_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationDispense_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationDispense_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationDispense_Index_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationDispense_Index_responsibleparty.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationDispense_Index_receiver.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationDispense_Index_prescription.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationDispense_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationDispense_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationDispense.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationAdministration_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationAdministration_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationAdministration_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationAdministration_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationAdministration_Index_device.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationAdministration_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationAdministration_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MedicationAdministration.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_package_item_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_package_item.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_ingredient_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_ingredient.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_form.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_container.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Medication.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Media_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Media_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Media_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Media_Index_view.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Media_Index_subtype.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Media_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Media_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Media.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MeasureReport_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MeasureReport_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MeasureReport_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MeasureReport_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_MeasureReport.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Measure_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Measure_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Measure_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Measure_Index_topic.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Measure_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Measure_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Measure.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Location_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Location_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Location_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Location_Index_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Location_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Location_Index_address.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Location_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Location.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List_Index_notes.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List_Index_item.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List_Index_empty_reason.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_List.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Linkage_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Linkage_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Linkage_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Linkage_Index_source.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Linkage_Index_item.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Linkage_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Linkage.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Library_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Library_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Library_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Library_Index_topic.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Library_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Library_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Library.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImplementationGuide_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImplementationGuide_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImplementationGuide_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImplementationGuide_Index_resource.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImplementationGuide_Index_dependency.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImplementationGuide_Index_context.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImplementationGuide_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImplementationGuide.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_vaccine_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_support.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_status.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_information.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_dose_sequence.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_dose_number.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_Index_date.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImmunizationRecommendation.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_vaccine_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_reason_not_given.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_reason.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_reaction_date.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_reaction.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_Index_dose_sequence.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Immunization.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_uid.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_series.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_order.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_modality.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_dicom_class.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_Index_bodysite.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingStudy.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingObjectSelection_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingObjectSelection_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingObjectSelection_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingObjectSelection_Index_title.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingObjectSelection_Index_selected_study.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingObjectSelection_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingObjectSelection.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingExcerpt_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingExcerpt_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingExcerpt_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingExcerpt_Index_title.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingExcerpt_Index_selected_study.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingExcerpt_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ImagingExcerpt.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_Index_servicetype.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_Index_servicecategory.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_Index_programname.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_Index_location.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_Index_characteristic.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_HealthcareService.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_GuidanceResponse_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_GuidanceResponse_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_GuidanceResponse_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_GuidanceResponse_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_GuidanceResponse.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_Index_value.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_Index_member.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_Index_exclude.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_Index_characteristic.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Group.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Goal_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Goal_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Goal_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Goal_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Goal_Index_category.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Goal_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Goal.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Flag_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Flag_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Flag_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Flag_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Flag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_FamilyMemberHistory_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_FamilyMemberHistory_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_FamilyMemberHistory_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_FamilyMemberHistory_Index_relationship.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_FamilyMemberHistory_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_FamilyMemberHistory_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_FamilyMemberHistory_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_FamilyMemberHistory.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExplanationOfBenefit_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExplanationOfBenefit_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExplanationOfBenefit_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExplanationOfBenefit_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExplanationOfBenefit_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExplanationOfBenefit.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExpansionProfile_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExpansionProfile_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExpansionProfile_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExpansionProfile_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ExpansionProfile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EpisodeOfCare_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EpisodeOfCare_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EpisodeOfCare_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EpisodeOfCare_Index_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EpisodeOfCare_Index_incomingreferral.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EpisodeOfCare_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EpisodeOfCare_Index_condition.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EpisodeOfCare_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EpisodeOfCare.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentResponse_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentResponse_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentResponse_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentResponse_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentResponse_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentResponse.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentRequest_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentRequest_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentRequest_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentRequest_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentRequest_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EnrollmentRequest.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_special_arrangement.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_reason.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_procedure.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_practitioner.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_participant_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_participant.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_location_period.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_location.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_indication.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_incomingreferral.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_episodeofcare.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_Index_condition.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Encounter.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityResponse_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityResponse_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityResponse_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityResponse_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityResponse_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityResponse.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityRequest_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityRequest_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityRequest_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityRequest_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityRequest_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_EligibilityRequest.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_setting.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_securitylabel.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_relation.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_relatesto.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_related_ref.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_related_id.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_location.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_language.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_format.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_facility.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_event.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_class.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_Index_author.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentReference.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_related_ref.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_related_id.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_recipient.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_content_ref.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_Index_author.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DocumentManifest.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_specimen.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_result.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_request.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_image.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_diagnosis.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_Index_category.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticReport.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_specimen.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_item_status.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_item_past_status.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_item_date.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_event_status.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_event_date.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_bodysite.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_Index_actor.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DiagnosticOrder.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseStatement_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseStatement_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseStatement_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseStatement_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseStatement.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseRequest_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseRequest_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseRequest_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseRequest_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceUseRequest.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceMetric_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceMetric_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceMetric_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceMetric_Index_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceMetric_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceMetric.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceComponent_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceComponent_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceComponent_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceComponent_Index_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceComponent_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DeviceComponent.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Device_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Device_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Device_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Device_Index_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Device_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Device_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Device.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DetectedIssue_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DetectedIssue_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DetectedIssue_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DetectedIssue_Index_implicated.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DetectedIssue_Index_category.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DetectedIssue_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DetectedIssue.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportServiceModule_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportServiceModule_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportServiceModule_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportServiceModule_Index_topic.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportServiceModule_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportServiceModule_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportServiceModule.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportRule_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportRule_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportRule_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportRule_Index_topic.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportRule_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportRule_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DecisionSupportRule.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DataElement_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DataElement_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DataElement_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DataElement_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DataElement_Index_description.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DataElement_Index_context.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DataElement_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DataElement_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_DataElement.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Coverage_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Coverage_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Coverage_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Coverage_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Coverage_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Coverage.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_ttopic.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_topic.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_subject.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_signer.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_patient.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_domain.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_authority.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_Index_agent.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Contract.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_supported_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_securityservice.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_resourceprofile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_resource.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_mode.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_format.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_event.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_Index_context.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Conformance.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_stage.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_severity.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_evidence.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_category.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_Index_body_site.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Condition.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_target_system.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_target_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_source_system.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_source_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_product.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_dependson.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_Index_context.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ConceptMap.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_section.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_period.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_entry.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_context.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_class.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_author.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_Index_attester.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Composition.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CompartmentDefinition_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CompartmentDefinition_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CompartmentDefinition_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CompartmentDefinition_Index_resource.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CompartmentDefinition_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CompartmentDefinition.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest_Index_recipient.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest_Index_priority.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest_Index_medium.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest_Index_category.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CommunicationRequest.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Communication_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Communication_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Communication_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Communication_Index_recipient.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Communication_Index_medium.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Communication_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Communication_Index_category.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Communication_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Communication.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CodeSystem_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CodeSystem_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CodeSystem_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CodeSystem_Index_language.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CodeSystem_Index_context.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CodeSystem_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CodeSystem_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CodeSystem.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_trigger_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_ruledout.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_resolved.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_problem.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_plan.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_investigation.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_finding.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_Index_action.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClinicalImpression.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClaimResponse_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClaimResponse_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClaimResponse_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClaimResponse_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClaimResponse_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_ClaimResponse.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Claim_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Claim_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Claim_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Claim_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Claim_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Claim.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CareTeam_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CareTeam_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CareTeam_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CareTeam_Index_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CareTeam_Index_status.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CareTeam_Index_participant.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CareTeam_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CareTeam_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CareTeam.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_relatedplan.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_relatedcode.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_performer.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_participant.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_goal.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_condition.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_activityreference.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_activitydate.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_Index_activitycode.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_CarePlan.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Bundle_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Bundle_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Bundle_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Bundle_Index_message.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Bundle_Index_composition.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Bundle_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Bundle.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_BodySite_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_BodySite_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_BodySite_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_BodySite_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_BodySite_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_BodySite_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_BodySite.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Binary_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Binary_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Binary_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Binary_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Binary.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Basic_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Basic_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Basic_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Basic_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Basic_Index_code.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Basic_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Basic.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_user.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_subtype.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_policy.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_patient.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_entity_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_entity_name.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_entity_id.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_entity.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_altid.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_agent_name.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_agent.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_Index_address.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AuditEvent.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AppointmentResponse_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AppointmentResponse_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AppointmentResponse_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AppointmentResponse_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AppointmentResponse_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AppointmentResponse.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_service_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_practitioner.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_patient.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_part_status.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_location.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_appointment_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_Index_actor.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Appointment.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_Index_substance.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_Index_severity.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_Index_route.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_Index_onset.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_Index_manifestation.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_AllergyIntolerance.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Account_Index_tag.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Account_Index_security.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Account_Index_profile.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Account_Index_type.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Account_Index_identifier.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Account_History.cs
// Blaze\Blaze.DataModel\DatabaseModel\Res_Account.cs
// Blaze\Blaze.DataModel\DatabaseModel\Blaze_RootUrlStore.cs
