INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1919, 'totalgross', 30, 640);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1920, 'health level seven international (financial management)', 31, 640);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1921, 'net total of this invoice', 28, 641);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1922, 'totalnet', 30, 641);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1923, 'health level seven international (financial management)', 31, 641);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1924, 'type of invoice', 28, 642);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1925, 'type', 30, 642);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1926, 'health level seven international (financial management)', 31, 642);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1927, 'the identifier of the patient who has devices assigned to', 28, 643);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1928, 'subject', 30, 643);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1929, 'health level seven international (orders and observations)', 31, 643);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1930, 'what resource is being referenced', 28, 644);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1931, 'composed-of', 30, 644);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1932, 'health level seven international (clinical decision support)', 31, 644);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1933, 'a use context assigned to the library', 28, 645);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1934, 'context', 30, 645);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1935, 'health level seven international (clinical decision support)', 31, 645);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1936, 'a quantity- or range-valued use context assigned to the library', 28, 646);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1937, 'context-quantity', 30, 646);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1938, 'health level seven international (clinical decision support)', 31, 646);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1939, 'a type of use context assigned to the library', 28, 647);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1940, 'context-type', 30, 647);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1941, 'health level seven international (clinical decision support)', 31, 647);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1942, 'the library publication date', 28, 648);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1943, 'date', 30, 648);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1944, 'health level seven international (clinical decision support)', 31, 648);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1945, 'what resource is being referenced', 28, 649);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1946, 'depends-on', 30, 649);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1947, 'health level seven international (clinical decision support)', 31, 649);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1948, 'what resource is being referenced', 28, 650);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1949, 'derived-from', 30, 650);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1950, 'health level seven international (clinical decision support)', 31, 650);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1951, 'the description of the library', 28, 651);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1952, 'description', 30, 651);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1953, 'health level seven international (clinical decision support)', 31, 651);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1954, 'the time during which the library is intended to be in use', 28, 652);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1955, 'effective', 30, 652);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1956, 'health level seven international (clinical decision support)', 31, 652);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1957, 'external identifier for the library', 28, 653);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1958, 'identifier', 30, 653);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1959, 'health level seven international (clinical decision support)', 31, 653);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1960, 'intended jurisdiction for the library', 28, 654);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1961, 'jurisdiction', 30, 654);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1962, 'health level seven international (clinical decision support)', 31, 654);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1963, 'computationally friendly name of the library', 28, 655);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1964, 'name', 30, 655);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1965, 'health level seven international (clinical decision support)', 31, 655);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1966, 'what resource is being referenced', 28, 656);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1967, 'predecessor', 30, 656);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1968, 'health level seven international (clinical decision support)', 31, 656);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1969, 'name of the publisher of the library', 28, 657);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1970, 'publisher', 30, 657);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1971, 'health level seven international (clinical decision support)', 31, 657);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1972, 'the current status of the library', 28, 658);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1973, 'status', 30, 658);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1974, 'health level seven international (clinical decision support)', 31, 658);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1975, 'what resource is being referenced', 28, 659);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1976, 'successor', 30, 659);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1977, 'health level seven international (clinical decision support)', 31, 659);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1978, 'the human-friendly name of the library', 28, 660);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1979, 'title', 30, 660);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1980, 'health level seven international (clinical decision support)', 31, 660);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1981, 'topics associated with the module', 28, 661);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1982, 'topic', 30, 661);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1983, 'health level seven international (clinical decision support)', 31, 661);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1984, 'the type of the library (e.g. logic-library, model-definition, asset-collection, module-definition)', 28, 662);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1985, 'type', 30, 662);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1986, 'health level seven international (clinical decision support)', 31, 662);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1987, 'the uri that identifies the library', 28, 663);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1988, 'url', 30, 663);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1989, 'health level seven international (clinical decision support)', 31, 663);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1990, 'the business version of the library', 28, 664);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1991, 'version', 30, 664);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1992, 'health level seven international (clinical decision support)', 31, 664);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (1999, 'author of the linkage', 28, 667);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2000, 'author', 30, 667);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2001, 'health level seven international (patient care)', 31, 667);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2002, 'matches on any item in the linkage', 28, 668);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2003, 'item', 30, 668);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2004, 'health level seven international (patient care)', 31, 668);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2005, 'matches on any item in the linkage with a type of ''source''', 28, 669);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2006, 'source', 30, 669);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2007, 'health level seven international (patient care)', 31, 669);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2008, 'why list is empty', 28, 670);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2009, 'empty-reason', 30, 670);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2010, 'health level seven international (fhir infrastructure)', 31, 670);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2011, 'actual entry', 28, 671);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2012, 'item', 30, 671);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2013, 'health level seven international (fhir infrastructure)', 31, 671);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2014, 'the annotation  - text content (as markdown)', 28, 672);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2015, 'notes', 30, 672);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2016, 'health level seven international (fhir infrastructure)', 31, 672);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2017, 'who and/or what defined the list contents (aka author)', 28, 673);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2018, 'source', 30, 673);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2019, 'health level seven international (fhir infrastructure)', 31, 673);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2020, 'current | retired | entered-in-error', 28, 674);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2021, 'status', 30, 674);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2022, 'health level seven international (fhir infrastructure)', 31, 674);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2023, 'if all resources have the same subject', 28, 675);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2024, 'subject', 30, 675);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2025, 'health level seven international (fhir infrastructure)', 31, 675);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2026, 'descriptive name for the list', 28, 676);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2027, 'title', 30, 676);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2028, 'health level seven international (fhir infrastructure)', 31, 676);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2029, 'a (part of the) address of the location', 28, 677);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2030, 'address', 30, 677);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2031, 'health level seven international (patient administration)', 31, 677);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2032, 'a city specified in an address', 28, 678);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2033, 'address-city', 30, 678);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2034, 'health level seven international (patient administration)', 31, 678);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2035, 'a country specified in an address', 28, 679);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2036, 'address-country', 30, 679);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2037, 'health level seven international (patient administration)', 31, 679);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2038, 'a postal code specified in an address', 28, 680);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2039, 'address-postalcode', 30, 680);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2040, 'health level seven international (patient administration)', 31, 680);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2041, 'a state specified in an address', 28, 681);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2042, 'address-state', 30, 681);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2043, 'health level seven international (patient administration)', 31, 681);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2044, 'a use code specified in an address', 28, 682);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2045, 'address-use', 30, 682);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2046, 'health level seven international (patient administration)', 31, 682);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2047, 'technical endpoints providing access to services operated for the location', 28, 683);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2048, 'endpoint', 30, 683);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2049, 'health level seven international (patient administration)', 31, 683);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2050, 'an identifier for the location', 28, 684);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2051, 'identifier', 30, 684);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2052, 'health level seven international (patient administration)', 31, 684);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2053, 'a portion of the location''s name or alias', 28, 685);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2054, 'name', 30, 685);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2055, 'health level seven international (patient administration)', 31, 685);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2056, 'search for locations where the location.position is near to, or within a specified distance of, the provided coordinates expressed as [latitude]|[longitude]|[distance]|[units] (using the wgs84 datum, see notes). if the units are omitted, then kms should be assumed. if the distance is omitted, then the server can use its own discression as to what distances should be considered near (and units are irrelevant) servers may search using various tech', 28, 686);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2057, 'near', 30, 686);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2058, 'health level seven international (patient administration)', 31, 686);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2059, 'searches for locations (typically bed/room) that have an operational status (e.g. contaminated, housekeeping)', 28, 687);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2060, 'operational-status', 30, 687);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2061, 'health level seven international (patient administration)', 31, 687);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2062, 'searches for locations that are managed by the provided organization', 28, 688);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2063, 'organization', 30, 688);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2064, 'health level seven international (patient administration)', 31, 688);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2065, 'a location of which this location is a part', 28, 689);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2066, 'partof', 30, 689);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2067, 'health level seven international (patient administration)', 31, 689);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2068, 'searches for locations with a specific kind of status', 28, 690);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2069, 'status', 30, 690);
INSERT INTO "public"."SearchParameterIxStr" ("Id", "String", "ServiceSearchParameterId", "ResourceId") VALUES (2070, 'health level seven international (patient administration)', 31, 690);
