
 

// Generated helper templates
// Pyro\Pyro.DataModel\Repository\_RepositoryGenerator.txt4
// Generated items
// Pyro\Pyro.DataModel\Repository\VisionPrescriptionRepository.cs
// Pyro\Pyro.DataModel\Repository\ValueSetRepository.cs
// Pyro\Pyro.DataModel\Repository\TestScriptRepository.cs
// Pyro\Pyro.DataModel\Repository\TaskRepository.cs
// Pyro\Pyro.DataModel\Repository\SupplyRequestRepository.cs
// Pyro\Pyro.DataModel\Repository\SupplyDeliveryRepository.cs
// Pyro\Pyro.DataModel\Repository\SubstanceRepository.cs
// Pyro\Pyro.DataModel\Repository\SubscriptionRepository.cs
// Pyro\Pyro.DataModel\Repository\StructureMapRepository.cs
// Pyro\Pyro.DataModel\Repository\StructureDefinitionRepository.cs
// Pyro\Pyro.DataModel\Repository\SpecimenRepository.cs
// Pyro\Pyro.DataModel\Repository\SlotRepository.cs
// Pyro\Pyro.DataModel\Repository\SequenceRepository.cs
// Pyro\Pyro.DataModel\Repository\SearchParameterRepository.cs
// Pyro\Pyro.DataModel\Repository\ScheduleRepository.cs
// Pyro\Pyro.DataModel\Repository\RiskAssessmentRepository.cs
// Pyro\Pyro.DataModel\Repository\RelatedPersonRepository.cs
// Pyro\Pyro.DataModel\Repository\ReferralRequestRepository.cs
// Pyro\Pyro.DataModel\Repository\QuestionnaireResponseRepository.cs
// Pyro\Pyro.DataModel\Repository\QuestionnaireRepository.cs
// Pyro\Pyro.DataModel\Repository\ProvenanceRepository.cs
// Pyro\Pyro.DataModel\Repository\ProcessResponseRepository.cs
// Pyro\Pyro.DataModel\Repository\ProcessRequestRepository.cs
// Pyro\Pyro.DataModel\Repository\ProcedureRequestRepository.cs
// Pyro\Pyro.DataModel\Repository\ProcedureRepository.cs
// Pyro\Pyro.DataModel\Repository\PractitionerRoleRepository.cs
// Pyro\Pyro.DataModel\Repository\PractitionerRepository.cs
// Pyro\Pyro.DataModel\Repository\PlanDefinitionRepository.cs
// Pyro\Pyro.DataModel\Repository\PersonRepository.cs
// Pyro\Pyro.DataModel\Repository\PaymentReconciliationRepository.cs
// Pyro\Pyro.DataModel\Repository\PaymentNoticeRepository.cs
// Pyro\Pyro.DataModel\Repository\PatientRepository.cs
// Pyro\Pyro.DataModel\Repository\ParametersRepository.cs
// Pyro\Pyro.DataModel\Repository\OrganizationRepository.cs
// Pyro\Pyro.DataModel\Repository\OperationOutcomeRepository.cs
// Pyro\Pyro.DataModel\Repository\OperationDefinitionRepository.cs
// Pyro\Pyro.DataModel\Repository\ObservationRepository.cs
// Pyro\Pyro.DataModel\Repository\NutritionRequestRepository.cs
// Pyro\Pyro.DataModel\Repository\NamingSystemRepository.cs
// Pyro\Pyro.DataModel\Repository\MessageHeaderRepository.cs
// Pyro\Pyro.DataModel\Repository\MedicationStatementRepository.cs
// Pyro\Pyro.DataModel\Repository\MedicationOrderRepository.cs
// Pyro\Pyro.DataModel\Repository\MedicationDispenseRepository.cs
// Pyro\Pyro.DataModel\Repository\MedicationAdministrationRepository.cs
// Pyro\Pyro.DataModel\Repository\MedicationRepository.cs
// Pyro\Pyro.DataModel\Repository\MediaRepository.cs
// Pyro\Pyro.DataModel\Repository\MeasureReportRepository.cs
// Pyro\Pyro.DataModel\Repository\MeasureRepository.cs
// Pyro\Pyro.DataModel\Repository\LocationRepository.cs
// Pyro\Pyro.DataModel\Repository\ListRepository.cs
// Pyro\Pyro.DataModel\Repository\LinkageRepository.cs
// Pyro\Pyro.DataModel\Repository\LibraryRepository.cs
// Pyro\Pyro.DataModel\Repository\ImplementationGuideRepository.cs
// Pyro\Pyro.DataModel\Repository\ImmunizationRecommendationRepository.cs
// Pyro\Pyro.DataModel\Repository\ImmunizationRepository.cs
// Pyro\Pyro.DataModel\Repository\ImagingStudyRepository.cs
// Pyro\Pyro.DataModel\Repository\ImagingManifestRepository.cs
// Pyro\Pyro.DataModel\Repository\HealthcareServiceRepository.cs
// Pyro\Pyro.DataModel\Repository\GuidanceResponseRepository.cs
// Pyro\Pyro.DataModel\Repository\GroupRepository.cs
// Pyro\Pyro.DataModel\Repository\GoalRepository.cs
// Pyro\Pyro.DataModel\Repository\FlagRepository.cs
// Pyro\Pyro.DataModel\Repository\FamilyMemberHistoryRepository.cs
// Pyro\Pyro.DataModel\Repository\ExplanationOfBenefitRepository.cs
// Pyro\Pyro.DataModel\Repository\ExpansionProfileRepository.cs
// Pyro\Pyro.DataModel\Repository\EpisodeOfCareRepository.cs
// Pyro\Pyro.DataModel\Repository\EnrollmentResponseRepository.cs
// Pyro\Pyro.DataModel\Repository\EnrollmentRequestRepository.cs
// Pyro\Pyro.DataModel\Repository\EndpointRepository.cs
// Pyro\Pyro.DataModel\Repository\EncounterRepository.cs
// Pyro\Pyro.DataModel\Repository\EligibilityResponseRepository.cs
// Pyro\Pyro.DataModel\Repository\EligibilityRequestRepository.cs
// Pyro\Pyro.DataModel\Repository\DocumentReferenceRepository.cs
// Pyro\Pyro.DataModel\Repository\DocumentManifestRepository.cs
// Pyro\Pyro.DataModel\Repository\DiagnosticRequestRepository.cs
// Pyro\Pyro.DataModel\Repository\DiagnosticReportRepository.cs
// Pyro\Pyro.DataModel\Repository\DeviceUseStatementRepository.cs
// Pyro\Pyro.DataModel\Repository\DeviceUseRequestRepository.cs
// Pyro\Pyro.DataModel\Repository\DeviceMetricRepository.cs
// Pyro\Pyro.DataModel\Repository\DeviceComponentRepository.cs
// Pyro\Pyro.DataModel\Repository\DeviceRepository.cs
// Pyro\Pyro.DataModel\Repository\DetectedIssueRepository.cs
// Pyro\Pyro.DataModel\Repository\DecisionSupportServiceModuleRepository.cs
// Pyro\Pyro.DataModel\Repository\DataElementRepository.cs
// Pyro\Pyro.DataModel\Repository\CoverageRepository.cs
// Pyro\Pyro.DataModel\Repository\ContractRepository.cs
// Pyro\Pyro.DataModel\Repository\ConsentRepository.cs
// Pyro\Pyro.DataModel\Repository\ConformanceRepository.cs
// Pyro\Pyro.DataModel\Repository\ConditionRepository.cs
// Pyro\Pyro.DataModel\Repository\ConceptMapRepository.cs
// Pyro\Pyro.DataModel\Repository\CompositionRepository.cs
// Pyro\Pyro.DataModel\Repository\CompartmentDefinitionRepository.cs
// Pyro\Pyro.DataModel\Repository\CommunicationRequestRepository.cs
// Pyro\Pyro.DataModel\Repository\CommunicationRepository.cs
// Pyro\Pyro.DataModel\Repository\CodeSystemRepository.cs
// Pyro\Pyro.DataModel\Repository\ClinicalImpressionRepository.cs
// Pyro\Pyro.DataModel\Repository\ClaimResponseRepository.cs
// Pyro\Pyro.DataModel\Repository\ClaimRepository.cs
// Pyro\Pyro.DataModel\Repository\CareTeamRepository.cs
// Pyro\Pyro.DataModel\Repository\CarePlanRepository.cs
// Pyro\Pyro.DataModel\Repository\BundleRepository.cs
// Pyro\Pyro.DataModel\Repository\BodySiteRepository.cs
// Pyro\Pyro.DataModel\Repository\BinaryRepository.cs
// Pyro\Pyro.DataModel\Repository\BasicRepository.cs
// Pyro\Pyro.DataModel\Repository\AuditEventRepository.cs
// Pyro\Pyro.DataModel\Repository\AppointmentResponseRepository.cs
// Pyro\Pyro.DataModel\Repository\AppointmentRepository.cs
// Pyro\Pyro.DataModel\Repository\AllergyIntoleranceRepository.cs
// Pyro\Pyro.DataModel\Repository\ActivityDefinitionRepository.cs
// Pyro\Pyro.DataModel\Repository\AccountRepository.cs
