using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Pyro.DataModel.DatabaseModel;
using Pyro.DataModel.DatabaseModel.Base;
using Pyro.DataModel.Support;
using Pyro.DataModel.IndexSetter;
using Pyro.Common.Interfaces.Repositories;
using Pyro.Common.Interfaces.UriSupport;
using Pyro.Common.BusinessEntities.Dto;
using Hl7.Fhir.Model;

//This file was auto generated by _GenericCodeDataTypeEnumsGenerator.tt and should not be modified manually. 
//Generation time-stamp: : 11/11/2016 3:03:55 PM.

namespace Pyro.DataModel.Repository
{
  public partial class PractitionerRepository<ResourceType, ResourceHistoryType> : CommonResourceRepository<ResourceType, ResourceHistoryType>, IResourceRepository 
    where ResourceType : Res_Practitioner, new() 
    where ResourceHistoryType :Res_Practitioner_History, new()
  {
    public PractitionerRepository(DataModel.DatabaseModel.DatabaseContext Context) : base(Context) { }

    protected override void GetResourceHistoryEntityList(LinqKit.ExpressionStarter<ResourceType> Predicate, int StartRecord, List<DtoResource> DtoResourceList)
    {
      var HistoryEntityList = DbGetAll<ResourceType>(Predicate).SelectMany(y => y.Res_Practitioner_History_List)
        .OrderByDescending(x => x.lastUpdated)
        .Skip(StartRecord)
        .Take(_NumberOfRecordsPerPage)
        .ToList();

      if (HistoryEntityList != null)
        HistoryEntityList.ForEach(x => DtoResourceList.Add(IndexSettingSupport.SetDtoResource(x, false)));      
    }

    protected override int GetResourceHistoryEntityCount(LinqKit.ExpressionStarter<ResourceType> Predicate)
    {
      return DbGetAll<ResourceType>(Predicate).SelectMany(y => y.Res_Practitioner_History_List).Count();      
    }

    protected override void AddResourceHistoryEntityToResourceEntity(ResourceType ResourceEntity, ResourceHistoryType ResourceHistoryEntity)
    {
      ResourceEntity.Res_Practitioner_History_List.Add(ResourceHistoryEntity);
    }
    
    protected override ResourceType LoadCurrentResourceEntity(string FhirId)
    {
      var IncludeList = new List<Expression<Func<ResourceType, object>>>();
         IncludeList.Add(x => x.address_List);
      IncludeList.Add(x => x.address_city_List);
      IncludeList.Add(x => x.address_country_List);
      IncludeList.Add(x => x.address_postalcode_List);
      IncludeList.Add(x => x.address_state_List);
      IncludeList.Add(x => x.address_use_List);
      IncludeList.Add(x => x.communication_List);
      IncludeList.Add(x => x.email_List);
      IncludeList.Add(x => x.email_List);
      IncludeList.Add(x => x.family_List);
      IncludeList.Add(x => x.given_List);
      IncludeList.Add(x => x.identifier_List);
      IncludeList.Add(x => x.identifier_List);
      IncludeList.Add(x => x.location_List);
      IncludeList.Add(x => x.name_List);
      IncludeList.Add(x => x.organization_List);
      IncludeList.Add(x => x.phone_List);
      IncludeList.Add(x => x.phone_List);
      IncludeList.Add(x => x.phonetic_List);
      IncludeList.Add(x => x.role_List);
      IncludeList.Add(x => x.specialty_List);
      IncludeList.Add(x => x.telecom_List);
      IncludeList.Add(x => x.telecom_List);
      IncludeList.Add(x => x._profile_List);
      IncludeList.Add(x => x._security_List);
      IncludeList.Add(x => x._tag_List);
    
      var ResourceEntity = DbQueryEntityWithInclude<ResourceType>(x => x.FhirId == FhirId, IncludeList);
      return ResourceEntity;
    }
    
    protected override void ResetResourceEntity(ResourceType ResourceEntity)
    {
      ResourceEntity.active_Code = null;      
      ResourceEntity.active_System = null;      
      ResourceEntity.gender_Code = null;      
      ResourceEntity.gender_System = null;      
      ResourceEntity.XmlBlob = null;      
 
      
      _Context.Res_Practitioner_Index_address.RemoveRange(ResourceEntity.address_List);            
      _Context.Res_Practitioner_Index_address_city.RemoveRange(ResourceEntity.address_city_List);            
      _Context.Res_Practitioner_Index_address_country.RemoveRange(ResourceEntity.address_country_List);            
      _Context.Res_Practitioner_Index_address_postalcode.RemoveRange(ResourceEntity.address_postalcode_List);            
      _Context.Res_Practitioner_Index_address_state.RemoveRange(ResourceEntity.address_state_List);            
      _Context.Res_Practitioner_Index_address_use.RemoveRange(ResourceEntity.address_use_List);            
      _Context.Res_Practitioner_Index_communication.RemoveRange(ResourceEntity.communication_List);            
      _Context.Res_Practitioner_Index_email.RemoveRange(ResourceEntity.email_List);            
      _Context.Res_Practitioner_Index_email.RemoveRange(ResourceEntity.email_List);            
      _Context.Res_Practitioner_Index_family.RemoveRange(ResourceEntity.family_List);            
      _Context.Res_Practitioner_Index_given.RemoveRange(ResourceEntity.given_List);            
      _Context.Res_Practitioner_Index_identifier.RemoveRange(ResourceEntity.identifier_List);            
      _Context.Res_Practitioner_Index_identifier.RemoveRange(ResourceEntity.identifier_List);            
      _Context.Res_Practitioner_Index_location.RemoveRange(ResourceEntity.location_List);            
      _Context.Res_Practitioner_Index_name.RemoveRange(ResourceEntity.name_List);            
      _Context.Res_Practitioner_Index_organization.RemoveRange(ResourceEntity.organization_List);            
      _Context.Res_Practitioner_Index_phone.RemoveRange(ResourceEntity.phone_List);            
      _Context.Res_Practitioner_Index_phone.RemoveRange(ResourceEntity.phone_List);            
      _Context.Res_Practitioner_Index_phonetic.RemoveRange(ResourceEntity.phonetic_List);            
      _Context.Res_Practitioner_Index_role.RemoveRange(ResourceEntity.role_List);            
      _Context.Res_Practitioner_Index_specialty.RemoveRange(ResourceEntity.specialty_List);            
      _Context.Res_Practitioner_Index_telecom.RemoveRange(ResourceEntity.telecom_List);            
      _Context.Res_Practitioner_Index_telecom.RemoveRange(ResourceEntity.telecom_List);            
      _Context.Res_Practitioner_Index__profile.RemoveRange(ResourceEntity._profile_List);            
      _Context.Res_Practitioner_Index__security.RemoveRange(ResourceEntity._security_List);            
      _Context.Res_Practitioner_Index__tag.RemoveRange(ResourceEntity._tag_List);            
 
    }

    protected override void PopulateResourceEntity(ResourceType ResourceEntity, string ResourceVersion, Resource Resource, IDtoFhirRequestUri FhirRequestUri)
    {
      var ResourceTyped = Resource as Practitioner;
      var ResourseEntity = ResourceEntity as ResourceType;
      IndexSettingSupport.SetResourceBaseAddOrUpdate(ResourceTyped, ResourseEntity, ResourceVersion, false);

          if (ResourceTyped.Active != null)
      {
        if (ResourceTyped.ActiveElement is Hl7.Fhir.Model.FhirBoolean)
        {
          var Index = new TokenIndex();
          Index = IndexSetterFactory.Create(typeof(TokenIndex)).Set(ResourceTyped.ActiveElement, Index) as TokenIndex;
          if (Index != null)
          {
            ResourseEntity.active_Code = Index.Code;
            ResourseEntity.active_System = Index.System;
          }
        }
      }

      if (ResourceTyped.Gender != null)
      {
        if (ResourceTyped.GenderElement is Hl7.Fhir.Model.Code<Hl7.Fhir.Model.AdministrativeGender>)
        {
          var Index = new TokenIndex();
          Index = IndexSetterFactory.Create(typeof(TokenIndex)).Set(ResourceTyped.GenderElement, Index) as TokenIndex;
          if (Index != null)
          {
            ResourseEntity.gender_Code = Index.Code;
            ResourseEntity.gender_System = Index.System;
          }
        }
      }

      if (ResourceTyped.Address != null)
      {
        foreach (var item2 in ResourceTyped.Address)
        {
          var Index = new Res_Practitioner_Index_address();
          Index = IndexSetterFactory.Create(typeof(StringIndex)).Set(item2, Index) as Res_Practitioner_Index_address;
          ResourseEntity.address_List.Add(Index);
        }
      }

      foreach (var item1 in ResourceTyped.Address)
      {
        if (item1.City != null)
        {
          if (item1.CityElement is Hl7.Fhir.Model.FhirString)
          {
            var Index = new Res_Practitioner_Index_address_city();
            Index = IndexSetterFactory.Create(typeof(StringIndex)).Set(item1.CityElement, Index) as Res_Practitioner_Index_address_city;
            ResourseEntity.address_city_List.Add(Index);
          }
        }
      }

      foreach (var item1 in ResourceTyped.Address)
      {
        if (item1.Country != null)
        {
          if (item1.CountryElement is Hl7.Fhir.Model.FhirString)
          {
            var Index = new Res_Practitioner_Index_address_country();
            Index = IndexSetterFactory.Create(typeof(StringIndex)).Set(item1.CountryElement, Index) as Res_Practitioner_Index_address_country;
            ResourseEntity.address_country_List.Add(Index);
          }
        }
      }

      foreach (var item1 in ResourceTyped.Address)
      {
        if (item1.PostalCode != null)
        {
          if (item1.PostalCodeElement is Hl7.Fhir.Model.FhirString)
          {
            var Index = new Res_Practitioner_Index_address_postalcode();
            Index = IndexSetterFactory.Create(typeof(StringIndex)).Set(item1.PostalCodeElement, Index) as Res_Practitioner_Index_address_postalcode;
            ResourseEntity.address_postalcode_List.Add(Index);
          }
        }
      }

      foreach (var item1 in ResourceTyped.Address)
      {
        if (item1.State != null)
        {
          if (item1.StateElement is Hl7.Fhir.Model.FhirString)
          {
            var Index = new Res_Practitioner_Index_address_state();
            Index = IndexSetterFactory.Create(typeof(StringIndex)).Set(item1.StateElement, Index) as Res_Practitioner_Index_address_state;
            ResourseEntity.address_state_List.Add(Index);
          }
        }
      }

      foreach (var item1 in ResourceTyped.Address)
      {
        if (item1.Use != null)
        {
          if (item1.UseElement is Hl7.Fhir.Model.Code<Hl7.Fhir.Model.Address.AddressUse>)
          {
            var Index = new Res_Practitioner_Index_address_use();
            Index = IndexSetterFactory.Create(typeof(TokenIndex)).Set(item1.UseElement, Index) as Res_Practitioner_Index_address_use;
            ResourseEntity.address_use_List.Add(Index);
          }
        }
      }

      if (ResourceTyped.Communication != null)
      {
        foreach (var item3 in ResourceTyped.Communication)
        {
          if (item3 != null)
          {
            foreach (var item4 in item3.Coding)
            {
              var Index = new Res_Practitioner_Index_communication();
              Index = IndexSetterFactory.Create(typeof(TokenIndex)).Set(item4, Index) as Res_Practitioner_Index_communication;
              ResourseEntity.communication_List.Add(Index);
            }
          }
        }
      }

      foreach (var item2 in ResourceTyped.Telecom)
      {
        if (item2.System != null)
        {
          if ((ContactPoint.ContactPointSystem)item2.System == ContactPoint.ContactPointSystem.Email)
          {
            if (item2 is ContactPoint)
            {
              var Index = new Res_Practitioner_Index_email();
              Index = IndexSetterFactory.Create(typeof(TokenIndex)).Set(item2, Index) as Res_Practitioner_Index_email;
              ResourseEntity.email_List.Add(Index);
            }
          }
        }
      }

      foreach (var item1 in ResourceTyped.Role)
      {
        foreach (var item3 in item1.Telecom)
        {
          if (item3.System != null)
          {
            if ((ContactPoint.ContactPointSystem)item3.System == ContactPoint.ContactPointSystem.Email)
            {
              if (item3 is ContactPoint)
              {
                var Index = new Res_Practitioner_Index_email();
                Index = IndexSetterFactory.Create(typeof(TokenIndex)).Set(item3, Index) as Res_Practitioner_Index_email;
                ResourseEntity.email_List.Add(Index);
              }
            }
          }
        }
      }

      foreach (var item1 in ResourceTyped.Name)
      {
        if (item1.Family != null)
        {
          foreach (var item4 in item1.FamilyElement)
          {
            if (item4 is Hl7.Fhir.Model.FhirString)
            {
              var Index = new Res_Practitioner_Index_family();
              Index = IndexSetterFactory.Create(typeof(StringIndex)).Set(item4, Index) as Res_Practitioner_Index_family;
              ResourseEntity.family_List.Add(Index);
            }
          }
        }
      }

      foreach (var item1 in ResourceTyped.Name)
      {
        if (item1.Given != null)
        {
          foreach (var item4 in item1.GivenElement)
          {
            if (item4 is Hl7.Fhir.Model.FhirString)
            {
              var Index = new Res_Practitioner_Index_given();
              Index = IndexSetterFactory.Create(typeof(StringIndex)).Set(item4, Index) as Res_Practitioner_Index_given;
              ResourseEntity.given_List.Add(Index);
            }
          }
        }
      }

      if (ResourceTyped.Identifier != null)
      {
        foreach (var item3 in ResourceTyped.Identifier)
        {
          if (item3 is Hl7.Fhir.Model.Identifier)
          {
            var Index = new Res_Practitioner_Index_identifier();
            Index = IndexSetterFactory.Create(typeof(TokenIndex)).Set(item3, Index) as Res_Practitioner_Index_identifier;
            ResourseEntity.identifier_List.Add(Index);
          }
        }
      }

      foreach (var item1 in ResourceTyped.Role)
      {
        if (item1.Identifier != null)
        {
          foreach (var item4 in item1.Identifier)
          {
            if (item4 is Hl7.Fhir.Model.Identifier)
            {
              var Index = new Res_Practitioner_Index_identifier();
              Index = IndexSetterFactory.Create(typeof(TokenIndex)).Set(item4, Index) as Res_Practitioner_Index_identifier;
              ResourseEntity.identifier_List.Add(Index);
            }
          }
        }
      }

      foreach (var item1 in ResourceTyped.Role)
      {
        if (item1.Location != null)
        {
          foreach (var item in item1.Location)
          {
            if (item is ResourceReference)
            {
              var Index = new Res_Practitioner_Index_location();
              Index = IndexSetterFactory.Create(typeof(ReferenceIndex)).Set(item, Index, FhirRequestUri, this) as Res_Practitioner_Index_location;
              if (Index != null)
              {
                ResourseEntity.location_List.Add(Index);
              }
            }
          }
        }
      }

      if (ResourceTyped.Name != null)
      {
        foreach (var item3 in ResourceTyped.Name)
        {
          var Index = new Res_Practitioner_Index_name();
          Index = IndexSetterFactory.Create(typeof(StringIndex)).Set(item3, Index) as Res_Practitioner_Index_name;
          ResourseEntity.name_List.Add(Index);
        }
      }

      foreach (var item1 in ResourceTyped.Role)
      {
        if (item1.Organization != null)
        {
          if (item1.Organization is ResourceReference)
          {
            var Index = new Res_Practitioner_Index_organization();
            Index = IndexSetterFactory.Create(typeof(ReferenceIndex)).Set(item1.Organization, Index, FhirRequestUri, this) as Res_Practitioner_Index_organization;
            if (Index != null)
            {
              ResourseEntity.organization_List.Add(Index);
            }
          }
        }
      }

      foreach (var item2 in ResourceTyped.Telecom)
      {
        if (item2.System != null)
        {
          if ((ContactPoint.ContactPointSystem)item2.System == ContactPoint.ContactPointSystem.Phone)
          {
            if (item2 is ContactPoint)
            {
              var Index = new Res_Practitioner_Index_phone();
              Index = IndexSetterFactory.Create(typeof(TokenIndex)).Set(item2, Index) as Res_Practitioner_Index_phone;
              ResourseEntity.phone_List.Add(Index);
            }
          }
        }
      }

      foreach (var item1 in ResourceTyped.Role)
      {
        foreach (var item3 in item1.Telecom)
        {
          if (item3.System != null)
          {
            if ((ContactPoint.ContactPointSystem)item3.System == ContactPoint.ContactPointSystem.Phone)
            {
              if (item3 is ContactPoint)
              {
                var Index = new Res_Practitioner_Index_phone();
                Index = IndexSetterFactory.Create(typeof(TokenIndex)).Set(item3, Index) as Res_Practitioner_Index_phone;
                ResourseEntity.phone_List.Add(Index);
              }
            }
          }
        }
      }

      if (ResourceTyped.Name != null)
      {
        foreach (var item3 in ResourceTyped.Name)
        {
          var Index = new Res_Practitioner_Index_phonetic();
          Index = IndexSetterFactory.Create(typeof(StringIndex)).Set(item3, Index) as Res_Practitioner_Index_phonetic;
          ResourseEntity.phonetic_List.Add(Index);
        }
      }

      foreach (var item1 in ResourceTyped.Role)
      {
        if (item1.Code != null)
        {
          foreach (var item4 in item1.Code.Coding)
          {
            var Index = new Res_Practitioner_Index_role();
            Index = IndexSetterFactory.Create(typeof(TokenIndex)).Set(item4, Index) as Res_Practitioner_Index_role;
            ResourseEntity.role_List.Add(Index);
          }
        }
      }

      foreach (var item1 in ResourceTyped.Role)
      {
        if (item1.Specialty != null)
        {
          foreach (var item4 in item1.Specialty)
          {
            if (item4 != null)
            {
              foreach (var item5 in item4.Coding)
              {
                var Index = new Res_Practitioner_Index_specialty();
                Index = IndexSetterFactory.Create(typeof(TokenIndex)).Set(item5, Index) as Res_Practitioner_Index_specialty;
                ResourseEntity.specialty_List.Add(Index);
              }
            }
          }
        }
      }

      foreach (var item2 in ResourceTyped.Telecom)
      {
        if (item2 is ContactPoint)
        {
          var Index = new Res_Practitioner_Index_telecom();
          Index = IndexSetterFactory.Create(typeof(TokenIndex)).Set(item2, Index) as Res_Practitioner_Index_telecom;
          ResourseEntity.telecom_List.Add(Index);
        }
      }

      foreach (var item1 in ResourceTyped.Role)
      {
        foreach (var item3 in item1.Telecom)
        {
          if (item3 is ContactPoint)
          {
            var Index = new Res_Practitioner_Index_telecom();
            Index = IndexSetterFactory.Create(typeof(TokenIndex)).Set(item3, Index) as Res_Practitioner_Index_telecom;
            ResourseEntity.telecom_List.Add(Index);
          }
        }
      }

      if (ResourceTyped.Meta != null)
      {
        if (ResourceTyped.Meta.Profile != null)
        {
          foreach (var item4 in ResourceTyped.Meta.ProfileElement)
          {
            if (item4 is Hl7.Fhir.Model.FhirUri)
            {
              var Index = new Res_Practitioner_Index__profile();
              Index = IndexSetterFactory.Create(typeof(UriIndex)).Set(item4, Index) as Res_Practitioner_Index__profile;
              ResourseEntity._profile_List.Add(Index);
            }
          }
        }
      }

      if (ResourceTyped.Meta != null)
      {
        if (ResourceTyped.Meta.Security != null)
        {
          foreach (var item4 in ResourceTyped.Meta.Security)
          {
            if (item4 is Hl7.Fhir.Model.Coding)
            {
              var Index = new Res_Practitioner_Index__security();
              Index = IndexSetterFactory.Create(typeof(TokenIndex)).Set(item4, Index) as Res_Practitioner_Index__security;
              ResourseEntity._security_List.Add(Index);
            }
          }
        }
      }

      if (ResourceTyped.Meta != null)
      {
        if (ResourceTyped.Meta.Tag != null)
        {
          foreach (var item4 in ResourceTyped.Meta.Tag)
          {
            if (item4 is Hl7.Fhir.Model.Coding)
            {
              var Index = new Res_Practitioner_Index__tag();
              Index = IndexSetterFactory.Create(typeof(TokenIndex)).Set(item4, Index) as Res_Practitioner_Index__tag;
              ResourseEntity._tag_List.Add(Index);
            }
          }
        }
      }


      
    }

  }
} 

