using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Hl7.Fhir.Model;
using Common.BusinessEntities.Search;

namespace Common.BusinessEntities
{
  public static class DtoEnums
  {
    public enum CrudOperationType { None, Create, Read, Update, Delete };

    //The List of Resources Supported by the Blaze Server
    //Should move this to the Database, maybe, not sure!! 
    // Be very careful here the order of this enum matters as it is stored in the database as an integer for each Resource saved!!
    // You can Add but never change!!!!
    public enum SupportedFhirResource
    {
      DomainResource = 0,
      Parameters = 1,
      Resource = 2,
      AllergyIntolerance = 3,
      Appointment = 4,
      AppointmentResponse = 5,
      AuditEvent = 6,
      Basic = 7,
      Binary = 8,
      BodySite = 9,
      Bundle = 10,
      CarePlan = 11,
      Claim = 12,
      ClaimResponse = 13,
      ClinicalImpression = 14,
      Communication = 15,
      CommunicationRequest = 16,
      Composition = 17,
      ConceptMap = 18,
      Condition = 19,
      Conformance = 20,
      Contract = 21,
      Coverage = 22,
      DataElement = 23,
      Device = 24,
      DeviceComponent = 25,
      DeviceMetric = 26,
      DeviceUseRequest = 27,
      DeviceUseStatement = 28,
      DiagnosticOrder = 29,
      DiagnosticReport = 30,
      DocumentManifest = 31,
      DocumentReference = 32,
      EligibilityRequest = 33,
      EligibilityResponse = 34,
      Encounter = 35,
      EnrollmentRequest = 36,
      EnrollmentResponse = 37,
      EpisodeOfCare = 38,
      ExplanationOfBenefit = 39,
      FamilyMemberHistory = 40,
      Flag = 41,
      Goal = 42,
      Group = 43,
      HealthcareService = 44,
      ImagingObjectSelection = 45,
      ImagingStudy = 46,
      Immunization = 47,
      ImmunizationRecommendation = 48,
      List = 49,
      Location = 50,
      Media = 51,
      Medication = 52,
      MedicationAdministration = 53,
      MedicationDispense = 54,
      MedicationOrder = 55,
      MedicationStatement = 56,
      MessageHeader = 57,
      NamingSystem = 58,
      NutritionOrder = 59,
      Observation = 60,
      OperationDefinition = 61,
      OperationOutcome = 62,
      Order = 63,
      OrderResponse = 64,
      Organization = 65,
      Patient = 66,
      PaymentNotice = 67,
      PaymentReconciliation = 68,
      Person = 69,
      Practitioner = 70,
      Procedure = 71,
      ProcedureRequest = 72,
      ProcessRequest = 73,
      ProcessResponse = 74,
      Provenance = 75,
      Questionnaire = 76,
      QuestionnaireResponse = 77,
      ReferralRequest = 78,
      RelatedPerson = 79,
      RiskAssessment = 80,
      Schedule = 81,
      SearchParameter = 82,
      Slot = 83,
      Specimen = 84,
      StructureDefinition = 85,
      Subscription = 86,
      Substance = 87,
      SupplyDelivery = 88,
      SupplyRequest = 89,
      TestScript = 90,
      ValueSet = 91,
      VisionPrescription = 92
    };

    //Convert a Blaze Supported Resource enum to a FHIR API Resource enum
    public static Dictionary<ResourceType, DtoEnums.SupportedFhirResource> GetBlazeSupportedResorceTypeByFhirResourceTypeDictionary()
    {
      return new Dictionary<ResourceType, DtoEnums.SupportedFhirResource>()
      {
        {ResourceType.DomainResource,DtoEnums.SupportedFhirResource.DomainResource},
        {ResourceType.Parameters,DtoEnums.SupportedFhirResource.Parameters},
        {ResourceType.Resource,DtoEnums.SupportedFhirResource.Resource},
        {ResourceType.AllergyIntolerance,DtoEnums.SupportedFhirResource.AllergyIntolerance},
        {ResourceType.Appointment,DtoEnums.SupportedFhirResource.Appointment},
        {ResourceType.AppointmentResponse,DtoEnums.SupportedFhirResource.AppointmentResponse},
        {ResourceType.AuditEvent,DtoEnums.SupportedFhirResource.AuditEvent},
        {ResourceType.Basic,DtoEnums.SupportedFhirResource.Basic},
        {ResourceType.Binary,DtoEnums.SupportedFhirResource.Binary},
        {ResourceType.BodySite,DtoEnums.SupportedFhirResource.BodySite},
        {ResourceType.Bundle,DtoEnums.SupportedFhirResource.Bundle},
        {ResourceType.CarePlan,DtoEnums.SupportedFhirResource.CarePlan},
        {ResourceType.Claim,DtoEnums.SupportedFhirResource.Claim},
        {ResourceType.ClaimResponse,DtoEnums.SupportedFhirResource.ClaimResponse},
        {ResourceType.ClinicalImpression,DtoEnums.SupportedFhirResource.ClinicalImpression},
        {ResourceType.Communication,DtoEnums.SupportedFhirResource.Communication},
        {ResourceType.CommunicationRequest,DtoEnums.SupportedFhirResource.CommunicationRequest},
        {ResourceType.Composition,DtoEnums.SupportedFhirResource.Composition},
        {ResourceType.ConceptMap,DtoEnums.SupportedFhirResource.ConceptMap},
        {ResourceType.Condition,DtoEnums.SupportedFhirResource.Condition},
        {ResourceType.Conformance,DtoEnums.SupportedFhirResource.Conformance},
        {ResourceType.Contract,DtoEnums.SupportedFhirResource.Contract},
        {ResourceType.Coverage,DtoEnums.SupportedFhirResource.Coverage},
        {ResourceType.DataElement,DtoEnums.SupportedFhirResource.DataElement},
        {ResourceType.Device,DtoEnums.SupportedFhirResource.Device},
        {ResourceType.DeviceComponent,DtoEnums.SupportedFhirResource.DeviceComponent},
        {ResourceType.DeviceMetric,DtoEnums.SupportedFhirResource.DeviceMetric},
        {ResourceType.DeviceUseRequest,DtoEnums.SupportedFhirResource.DeviceUseRequest},
        {ResourceType.DeviceUseStatement,DtoEnums.SupportedFhirResource.DeviceUseStatement},
        {ResourceType.DiagnosticOrder,DtoEnums.SupportedFhirResource.DiagnosticOrder},
        {ResourceType.DiagnosticReport,DtoEnums.SupportedFhirResource.DiagnosticReport},
        {ResourceType.DocumentManifest,DtoEnums.SupportedFhirResource.DocumentManifest},
        {ResourceType.DocumentReference,DtoEnums.SupportedFhirResource.DocumentReference},
        {ResourceType.EligibilityRequest,DtoEnums.SupportedFhirResource.EligibilityRequest},
        {ResourceType.EligibilityResponse,DtoEnums.SupportedFhirResource.EligibilityResponse},
        {ResourceType.Encounter,DtoEnums.SupportedFhirResource.Encounter},
        {ResourceType.EnrollmentRequest,DtoEnums.SupportedFhirResource.EnrollmentRequest},
        {ResourceType.EnrollmentResponse,DtoEnums.SupportedFhirResource.EnrollmentResponse},
        {ResourceType.EpisodeOfCare,DtoEnums.SupportedFhirResource.EpisodeOfCare},
        {ResourceType.ExplanationOfBenefit,DtoEnums.SupportedFhirResource.ExplanationOfBenefit},
        {ResourceType.FamilyMemberHistory,DtoEnums.SupportedFhirResource.FamilyMemberHistory},
        {ResourceType.Flag,DtoEnums.SupportedFhirResource.Flag},
        {ResourceType.Goal,DtoEnums.SupportedFhirResource.Goal},
        {ResourceType.Group,DtoEnums.SupportedFhirResource.Group},
        {ResourceType.HealthcareService,DtoEnums.SupportedFhirResource.HealthcareService},
        {ResourceType.ImagingObjectSelection ,DtoEnums.SupportedFhirResource.ImagingObjectSelection},
        {ResourceType.ImagingStudy,DtoEnums.SupportedFhirResource.ImagingStudy},
        {ResourceType.Immunization,DtoEnums.SupportedFhirResource.Immunization},
        {ResourceType.ImmunizationRecommendation,DtoEnums.SupportedFhirResource.ImmunizationRecommendation},
        {ResourceType.List,DtoEnums.SupportedFhirResource.List},
        {ResourceType.Location,DtoEnums.SupportedFhirResource.Location},
        {ResourceType.Media,DtoEnums.SupportedFhirResource.Media},
        {ResourceType.Medication,DtoEnums.SupportedFhirResource.Medication},
        {ResourceType.MedicationAdministration,DtoEnums.SupportedFhirResource.MedicationAdministration},
        {ResourceType.MedicationDispense,DtoEnums.SupportedFhirResource.MedicationDispense},
        {ResourceType.MedicationOrder,DtoEnums.SupportedFhirResource.MedicationOrder},
        {ResourceType.MedicationStatement,DtoEnums.SupportedFhirResource.MedicationStatement},
        {ResourceType.MessageHeader,DtoEnums.SupportedFhirResource.MessageHeader},
        {ResourceType.NamingSystem,DtoEnums.SupportedFhirResource.NamingSystem},
        {ResourceType.NutritionOrder,DtoEnums.SupportedFhirResource.NutritionOrder},
        {ResourceType.Observation,DtoEnums.SupportedFhirResource.Observation},
        {ResourceType.OperationDefinition,DtoEnums.SupportedFhirResource.OperationDefinition},
        {ResourceType.OperationOutcome,DtoEnums.SupportedFhirResource.OperationOutcome},
        {ResourceType.Order,DtoEnums.SupportedFhirResource.Order},
        {ResourceType.OrderResponse,DtoEnums.SupportedFhirResource.OrderResponse},
        {ResourceType.Organization,DtoEnums.SupportedFhirResource.Organization},
        {ResourceType.Patient,DtoEnums.SupportedFhirResource.Patient},
        {ResourceType.PaymentNotice,DtoEnums.SupportedFhirResource.PaymentNotice},
        {ResourceType.PaymentReconciliation,DtoEnums.SupportedFhirResource.PaymentReconciliation},
        {ResourceType.Person,DtoEnums.SupportedFhirResource.Person},
        {ResourceType.Practitioner,DtoEnums.SupportedFhirResource.Practitioner},
        {ResourceType.Procedure,DtoEnums.SupportedFhirResource.Procedure},
        {ResourceType.ProcedureRequest,DtoEnums.SupportedFhirResource.ProcedureRequest},
        {ResourceType.ProcessRequest,DtoEnums.SupportedFhirResource.ProcessRequest},
        {ResourceType.ProcessResponse,DtoEnums.SupportedFhirResource.ProcessResponse},
        {ResourceType.Provenance,DtoEnums.SupportedFhirResource.Provenance},
        {ResourceType.Questionnaire,DtoEnums.SupportedFhirResource.Questionnaire},
        {ResourceType.QuestionnaireResponse,DtoEnums.SupportedFhirResource.QuestionnaireResponse},
        {ResourceType.ReferralRequest,DtoEnums.SupportedFhirResource.ReferralRequest},
        {ResourceType.RelatedPerson,DtoEnums.SupportedFhirResource.RelatedPerson},
        {ResourceType.RiskAssessment,DtoEnums.SupportedFhirResource.RiskAssessment},
        {ResourceType.Schedule,DtoEnums.SupportedFhirResource.Schedule},
        {ResourceType.SearchParameter,DtoEnums.SupportedFhirResource.SearchParameter},
        {ResourceType.Slot,DtoEnums.SupportedFhirResource.Slot},
        {ResourceType.Specimen,DtoEnums.SupportedFhirResource.Specimen},
        {ResourceType.StructureDefinition,DtoEnums.SupportedFhirResource.StructureDefinition},
        {ResourceType.Subscription,DtoEnums.SupportedFhirResource.Subscription},
        {ResourceType.Substance,DtoEnums.SupportedFhirResource.Substance},
        {ResourceType.SupplyDelivery,DtoEnums.SupportedFhirResource.SupplyDelivery},
        {ResourceType.SupplyRequest,DtoEnums.SupportedFhirResource.SupplyRequest},
        {ResourceType.TestScript,DtoEnums.SupportedFhirResource.TestScript},
        {ResourceType.ValueSet,DtoEnums.SupportedFhirResource.ValueSet},
        {ResourceType.VisionPrescription,DtoEnums.SupportedFhirResource.VisionPrescription}
      };
    }

    //Convert FHIR API Resource enum to the Blaze Supported Resource enum
    public static Dictionary<DtoEnums.SupportedFhirResource, ResourceType> GetFhirResourceTypeByBlazeSupportedResorceTypeDictionary()
    {
      return new Dictionary<DtoEnums.SupportedFhirResource, ResourceType>()
      {
        {DtoEnums.SupportedFhirResource.DomainResource,ResourceType.DomainResource},
        {DtoEnums.SupportedFhirResource.Parameters,ResourceType.Parameters},
        {DtoEnums.SupportedFhirResource.Resource,ResourceType.Resource},
        {DtoEnums.SupportedFhirResource.AllergyIntolerance,ResourceType.AllergyIntolerance},
        {DtoEnums.SupportedFhirResource.Appointment,ResourceType.Appointment},
        {DtoEnums.SupportedFhirResource.AppointmentResponse,ResourceType.AppointmentResponse},
        {DtoEnums.SupportedFhirResource.AuditEvent,ResourceType.AuditEvent},
        {DtoEnums.SupportedFhirResource.Basic,ResourceType.Basic},
        {DtoEnums.SupportedFhirResource.Binary,ResourceType.Binary},
        {DtoEnums.SupportedFhirResource.BodySite,ResourceType.BodySite},
        {DtoEnums.SupportedFhirResource.Bundle,ResourceType.Bundle},
        {DtoEnums.SupportedFhirResource.CarePlan,ResourceType.CarePlan},
        {DtoEnums.SupportedFhirResource.Claim,ResourceType.Claim},
        {DtoEnums.SupportedFhirResource.ClaimResponse,ResourceType.ClaimResponse},
        {DtoEnums.SupportedFhirResource.ClinicalImpression,ResourceType.ClinicalImpression},
        {DtoEnums.SupportedFhirResource.Communication,ResourceType.Communication},
        {DtoEnums.SupportedFhirResource.CommunicationRequest,ResourceType.CommunicationRequest},
        {DtoEnums.SupportedFhirResource.Composition,ResourceType.Composition},
        {DtoEnums.SupportedFhirResource.ConceptMap,ResourceType.ConceptMap},
        {DtoEnums.SupportedFhirResource.Condition,ResourceType.Condition},
        {DtoEnums.SupportedFhirResource.Conformance,ResourceType.Conformance},
        {DtoEnums.SupportedFhirResource.Contract,ResourceType.Contract},
        {DtoEnums.SupportedFhirResource.Coverage,ResourceType.Coverage},
        {DtoEnums.SupportedFhirResource.DataElement,ResourceType.DataElement},
        {DtoEnums.SupportedFhirResource.Device,ResourceType.Device},
        {DtoEnums.SupportedFhirResource.DeviceComponent,ResourceType.DeviceComponent},
        {DtoEnums.SupportedFhirResource.DeviceMetric,ResourceType.DeviceMetric},
        {DtoEnums.SupportedFhirResource.DeviceUseRequest,ResourceType.DeviceUseRequest},
        {DtoEnums.SupportedFhirResource.DeviceUseStatement,ResourceType.DeviceUseStatement},
        {DtoEnums.SupportedFhirResource.DiagnosticOrder,ResourceType.DiagnosticOrder},
        {DtoEnums.SupportedFhirResource.DiagnosticReport,ResourceType.DiagnosticReport},
        {DtoEnums.SupportedFhirResource.DocumentManifest,ResourceType.DocumentManifest},
        {DtoEnums.SupportedFhirResource.DocumentReference,ResourceType.DocumentReference},
        {DtoEnums.SupportedFhirResource.EligibilityRequest,ResourceType.EligibilityRequest},
        {DtoEnums.SupportedFhirResource.EligibilityResponse,ResourceType.EligibilityResponse},
        {DtoEnums.SupportedFhirResource.Encounter,ResourceType.Encounter},
        {DtoEnums.SupportedFhirResource.EnrollmentRequest,ResourceType.EnrollmentRequest},
        {DtoEnums.SupportedFhirResource.EnrollmentResponse,ResourceType.EnrollmentResponse},
        {DtoEnums.SupportedFhirResource.EpisodeOfCare,ResourceType.EpisodeOfCare},
        {DtoEnums.SupportedFhirResource.ExplanationOfBenefit,ResourceType.ExplanationOfBenefit},
        {DtoEnums.SupportedFhirResource.FamilyMemberHistory,ResourceType.FamilyMemberHistory},
        {DtoEnums.SupportedFhirResource.Flag,ResourceType.Flag},
        {DtoEnums.SupportedFhirResource.Goal,ResourceType.Goal},
        {DtoEnums.SupportedFhirResource.Group,ResourceType.Group},
        {DtoEnums.SupportedFhirResource.HealthcareService,ResourceType.HealthcareService},
        {DtoEnums.SupportedFhirResource.ImagingObjectSelection,ResourceType.ImagingObjectSelection}, 
        {DtoEnums.SupportedFhirResource.ImagingStudy,ResourceType.ImagingStudy},
        {DtoEnums.SupportedFhirResource.Immunization,ResourceType.Immunization},
        {DtoEnums.SupportedFhirResource.ImmunizationRecommendation,ResourceType.ImmunizationRecommendation},
        {DtoEnums.SupportedFhirResource.List,ResourceType.List},
        {DtoEnums.SupportedFhirResource.Location,ResourceType.Location},
        {DtoEnums.SupportedFhirResource.Media,ResourceType.Media},
        {DtoEnums.SupportedFhirResource.Medication,ResourceType.Medication},
        {DtoEnums.SupportedFhirResource.MedicationAdministration,ResourceType.MedicationAdministration},
        {DtoEnums.SupportedFhirResource.MedicationDispense,ResourceType.MedicationDispense},
        {DtoEnums.SupportedFhirResource.MedicationOrder,ResourceType.MedicationOrder},
        {DtoEnums.SupportedFhirResource.MedicationStatement,ResourceType.MedicationStatement},
        {DtoEnums.SupportedFhirResource.MessageHeader,ResourceType.MessageHeader},
        {DtoEnums.SupportedFhirResource.NamingSystem,ResourceType.NamingSystem},
        {DtoEnums.SupportedFhirResource.NutritionOrder,ResourceType.NutritionOrder},
        {DtoEnums.SupportedFhirResource.Observation,ResourceType.Observation},
        {DtoEnums.SupportedFhirResource.OperationDefinition,ResourceType.OperationDefinition},
        {DtoEnums.SupportedFhirResource.OperationOutcome,ResourceType.OperationOutcome},
        {DtoEnums.SupportedFhirResource.Order,ResourceType.Order},
        {DtoEnums.SupportedFhirResource.OrderResponse,ResourceType.OrderResponse},
        {DtoEnums.SupportedFhirResource.Organization,ResourceType.Organization},
        {DtoEnums.SupportedFhirResource.Patient,ResourceType.Patient},
        {DtoEnums.SupportedFhirResource.PaymentNotice,ResourceType.PaymentNotice},
        {DtoEnums.SupportedFhirResource.PaymentReconciliation,ResourceType.PaymentReconciliation},
        {DtoEnums.SupportedFhirResource.Person,ResourceType.Person},
        {DtoEnums.SupportedFhirResource.Practitioner,ResourceType.Practitioner},
        {DtoEnums.SupportedFhirResource.Procedure,ResourceType.Procedure},
        {DtoEnums.SupportedFhirResource.ProcedureRequest,ResourceType.ProcedureRequest},
        {DtoEnums.SupportedFhirResource.ProcessRequest,ResourceType.ProcessRequest},
        {DtoEnums.SupportedFhirResource.ProcessResponse,ResourceType.ProcessResponse},
        {DtoEnums.SupportedFhirResource.Provenance,ResourceType.Provenance},
        {DtoEnums.SupportedFhirResource.Questionnaire,ResourceType.Questionnaire},
        {DtoEnums.SupportedFhirResource.QuestionnaireResponse,ResourceType.QuestionnaireResponse},
        {DtoEnums.SupportedFhirResource.ReferralRequest,ResourceType.ReferralRequest},
        {DtoEnums.SupportedFhirResource.RelatedPerson,ResourceType.RelatedPerson},
        {DtoEnums.SupportedFhirResource.RiskAssessment,ResourceType.RiskAssessment},
        {DtoEnums.SupportedFhirResource.Schedule,ResourceType.Schedule},
        {DtoEnums.SupportedFhirResource.SearchParameter,ResourceType.SearchParameter},
        {DtoEnums.SupportedFhirResource.Slot,ResourceType.Slot},
        {DtoEnums.SupportedFhirResource.Specimen,ResourceType.Specimen},
        {DtoEnums.SupportedFhirResource.StructureDefinition,ResourceType.StructureDefinition},
        {DtoEnums.SupportedFhirResource.Subscription,ResourceType.Subscription},
        {DtoEnums.SupportedFhirResource.Substance,ResourceType.Substance},
        {DtoEnums.SupportedFhirResource.SupplyDelivery,ResourceType.SupplyDelivery},
        {DtoEnums.SupportedFhirResource.SupplyRequest,ResourceType.SupplyRequest},
        {DtoEnums.SupportedFhirResource.SupplyRequest,ResourceType.SupplyRequest},
        {DtoEnums.SupportedFhirResource.ValueSet,ResourceType.ValueSet},
        {DtoEnums.SupportedFhirResource.VisionPrescription,ResourceType.VisionPrescription}
      };
    }

    //Convert TypeOF(Resource) to a Blaze supported Resource enum
    public static Dictionary<Type, DtoEnums.SupportedFhirResource> GetBlazeSupportedResorceType_ByTypeOf_FhirResourceDictionary =
            new Dictionary<Type, DtoEnums.SupportedFhirResource>()     
            {
              { typeof(DomainResource),DtoEnums.SupportedFhirResource.DomainResource },
              { typeof(Parameters),DtoEnums.SupportedFhirResource.Parameters },
              { typeof(Resource),DtoEnums.SupportedFhirResource.Resource },
              { typeof(AllergyIntolerance),DtoEnums.SupportedFhirResource.AllergyIntolerance },
              { typeof(Appointment),DtoEnums.SupportedFhirResource.Appointment },
              { typeof(AppointmentResponse),DtoEnums.SupportedFhirResource.AppointmentResponse },
              { typeof(AuditEvent),DtoEnums.SupportedFhirResource.AuditEvent },
              { typeof(Basic),DtoEnums.SupportedFhirResource.Basic },
              { typeof(Binary),DtoEnums.SupportedFhirResource.Binary },
              { typeof(BodySite),DtoEnums.SupportedFhirResource.BodySite },
              { typeof(Bundle),DtoEnums.SupportedFhirResource.Bundle },
              { typeof(CarePlan),DtoEnums.SupportedFhirResource.CarePlan },
              { typeof(Claim),DtoEnums.SupportedFhirResource.Claim },
              { typeof(ClaimResponse),DtoEnums.SupportedFhirResource.ClaimResponse },
              { typeof(ClinicalImpression),DtoEnums.SupportedFhirResource.ClinicalImpression },
              { typeof(Communication),DtoEnums.SupportedFhirResource.Communication },
              { typeof(CommunicationRequest),DtoEnums.SupportedFhirResource.CommunicationRequest },
              { typeof(Composition),DtoEnums.SupportedFhirResource.Composition },
              { typeof(ConceptMap),DtoEnums.SupportedFhirResource.ConceptMap },
              { typeof(Condition),DtoEnums.SupportedFhirResource.Condition },
              { typeof(Conformance),DtoEnums.SupportedFhirResource.Conformance },
              { typeof(Contract),DtoEnums.SupportedFhirResource.Contract },
              { typeof(Coverage),DtoEnums.SupportedFhirResource.Coverage },
              { typeof(DataElement),DtoEnums.SupportedFhirResource.DataElement },
              { typeof(Device),DtoEnums.SupportedFhirResource.Device },
              { typeof(DeviceComponent),DtoEnums.SupportedFhirResource.DeviceComponent },
              { typeof(DeviceMetric),DtoEnums.SupportedFhirResource.DeviceMetric },
              { typeof(DeviceUseRequest),DtoEnums.SupportedFhirResource.DeviceUseRequest },
              { typeof(DeviceUseStatement),DtoEnums.SupportedFhirResource.DeviceUseStatement },
              { typeof(DiagnosticOrder),DtoEnums.SupportedFhirResource.DiagnosticOrder },
              { typeof(DiagnosticReport),DtoEnums.SupportedFhirResource.DiagnosticReport },
              { typeof(DocumentManifest),DtoEnums.SupportedFhirResource.DocumentManifest },
              { typeof(DocumentReference),DtoEnums.SupportedFhirResource.DocumentReference },
              { typeof(EligibilityRequest),DtoEnums.SupportedFhirResource.EligibilityRequest },
              { typeof(EligibilityResponse),DtoEnums.SupportedFhirResource.EligibilityResponse },
              { typeof(Encounter),DtoEnums.SupportedFhirResource.Encounter },
              { typeof(EnrollmentRequest),DtoEnums.SupportedFhirResource.EnrollmentRequest },
              { typeof(EnrollmentResponse),DtoEnums.SupportedFhirResource.EnrollmentResponse },
              { typeof(EpisodeOfCare),DtoEnums.SupportedFhirResource.EpisodeOfCare },
              { typeof(ExplanationOfBenefit),DtoEnums.SupportedFhirResource.ExplanationOfBenefit },
              { typeof(FamilyMemberHistory),DtoEnums.SupportedFhirResource.FamilyMemberHistory },
              { typeof(Flag),DtoEnums.SupportedFhirResource.Flag },
              { typeof(Goal),DtoEnums.SupportedFhirResource.Goal },
              { typeof(Group),DtoEnums.SupportedFhirResource.Group },
              { typeof(HealthcareService),DtoEnums.SupportedFhirResource.HealthcareService },
              { typeof(ImagingObjectSelection),DtoEnums.SupportedFhirResource.ImagingObjectSelection }, 
              { typeof(ImagingStudy),DtoEnums.SupportedFhirResource.ImagingStudy },
              { typeof(Immunization),DtoEnums.SupportedFhirResource.Immunization },
              { typeof(ImmunizationRecommendation),DtoEnums.SupportedFhirResource.ImmunizationRecommendation },
              { typeof(List),DtoEnums.SupportedFhirResource.List },
              { typeof(Location),DtoEnums.SupportedFhirResource.Location },
              { typeof(Media),DtoEnums.SupportedFhirResource.Media },
              { typeof(Medication),DtoEnums.SupportedFhirResource.Medication },
              { typeof(MedicationAdministration),DtoEnums.SupportedFhirResource.MedicationAdministration },
              { typeof(MedicationDispense),DtoEnums.SupportedFhirResource.MedicationDispense },
              { typeof(MedicationOrder),DtoEnums.SupportedFhirResource.MedicationOrder },
              { typeof(MedicationStatement),DtoEnums.SupportedFhirResource.MedicationStatement },
              { typeof(MessageHeader),DtoEnums.SupportedFhirResource.MessageHeader },
              { typeof(NamingSystem),DtoEnums.SupportedFhirResource.NamingSystem },
              { typeof(NutritionOrder),DtoEnums.SupportedFhirResource.NutritionOrder },
              { typeof(Observation),DtoEnums.SupportedFhirResource.Observation },
              { typeof(OperationDefinition),DtoEnums.SupportedFhirResource.OperationDefinition },
              { typeof(OperationOutcome),DtoEnums.SupportedFhirResource.OperationOutcome },
              { typeof(Order),DtoEnums.SupportedFhirResource.Order },
              { typeof(OrderResponse),DtoEnums.SupportedFhirResource.OrderResponse },
              { typeof(Organization),DtoEnums.SupportedFhirResource.Organization },
              { typeof(Patient),DtoEnums.SupportedFhirResource.Patient },
              { typeof(PaymentNotice),DtoEnums.SupportedFhirResource.PaymentNotice },
              { typeof(PaymentReconciliation),DtoEnums.SupportedFhirResource.PaymentReconciliation },
              { typeof(Person),DtoEnums.SupportedFhirResource.Person },
              { typeof(Practitioner),DtoEnums.SupportedFhirResource.Practitioner },
              { typeof(Procedure),DtoEnums.SupportedFhirResource.Procedure },
              { typeof(ProcedureRequest),DtoEnums.SupportedFhirResource.ProcedureRequest },
              { typeof(ProcessRequest),DtoEnums.SupportedFhirResource.ProcessRequest },
              { typeof(ProcessResponse),DtoEnums.SupportedFhirResource.ProcessResponse },
              { typeof(Provenance),DtoEnums.SupportedFhirResource.Provenance },
              { typeof(Questionnaire),DtoEnums.SupportedFhirResource.Questionnaire },
              { typeof(QuestionnaireResponse),DtoEnums.SupportedFhirResource.QuestionnaireResponse },
              { typeof(ReferralRequest),DtoEnums.SupportedFhirResource.ReferralRequest },
              { typeof(RelatedPerson),DtoEnums.SupportedFhirResource.RelatedPerson },
              { typeof(RiskAssessment),DtoEnums.SupportedFhirResource.RiskAssessment },
              { typeof(Schedule),DtoEnums.SupportedFhirResource.Schedule },
              { typeof(SearchParameter),DtoEnums.SupportedFhirResource.SearchParameter },
              { typeof(Slot),DtoEnums.SupportedFhirResource.Slot },
              { typeof(Specimen),DtoEnums.SupportedFhirResource.Specimen },
              { typeof(StructureDefinition),DtoEnums.SupportedFhirResource.StructureDefinition },
              { typeof(Subscription),DtoEnums.SupportedFhirResource.Subscription },
              { typeof(Substance),DtoEnums.SupportedFhirResource.Substance },
              { typeof(SupplyDelivery),DtoEnums.SupportedFhirResource.SupplyDelivery },
              { typeof(SupplyRequest),DtoEnums.SupportedFhirResource.SupplyRequest },
              { typeof(TestScript),DtoEnums.SupportedFhirResource.TestScript },
              { typeof(ValueSet),DtoEnums.SupportedFhirResource.ValueSet },
              { typeof(VisionPrescription),DtoEnums.SupportedFhirResource.VisionPrescription }
            };

    //Convert String Resource Name to FHIR API Resource Type enum
    public static Dictionary<string, ResourceType> GetFhirResourceTypeByNameDictionary()
    {
      return new Dictionary<string, ResourceType>()
      {
        {"DomainResource",ResourceType.DomainResource},
        {"Parameters",ResourceType.Parameters},
        {"Resource",ResourceType.Resource},
        {"AllergyIntolerance",ResourceType.AllergyIntolerance},
        {"Appointment",ResourceType.Appointment},
        {"AppointmentResponse",ResourceType.AppointmentResponse},
        {"AuditEvent",ResourceType.AuditEvent},
        {"Basic",ResourceType.Basic},
        {"Binary",ResourceType.Binary},
        {"BodySite",ResourceType.BodySite},
        {"Bundle",ResourceType.Bundle},
        {"CarePlan",ResourceType.CarePlan},
        {"Claim",ResourceType.Claim},
        {"ClaimResponse",ResourceType.ClaimResponse},
        {"ClinicalImpression",ResourceType.ClinicalImpression},
        {"Communication",ResourceType.Communication},
        {"CommunicationRequest",ResourceType.CommunicationRequest},
        {"Composition",ResourceType.Composition},
        {"ConceptMap",ResourceType.ConceptMap},
        {"Condition",ResourceType.Condition},
        {"Conformance",ResourceType.Conformance},
        {"Contract",ResourceType.Contract},        
        {"Coverage",ResourceType.Coverage},
        {"DataElement",ResourceType.DataElement},
        {"Device",ResourceType.Device},
        {"DeviceComponent",ResourceType.DeviceComponent},
        {"DeviceMetric",ResourceType.DeviceMetric},
        {"DeviceUseRequest",ResourceType.DeviceUseRequest},
        {"DeviceUseStatement",ResourceType.DeviceUseStatement},
        {"DiagnosticOrder",ResourceType.DiagnosticOrder},
        {"DiagnosticReport",ResourceType.DiagnosticReport},
        {"DocumentManifest",ResourceType.DocumentManifest},
        {"DocumentReference",ResourceType.DocumentReference},
        {"EligibilityRequest",ResourceType.EligibilityRequest},
        {"EligibilityResponse",ResourceType.EligibilityResponse},
        {"Encounter",ResourceType.Encounter},
        {"EnrollmentRequest",ResourceType.EnrollmentRequest},
        {"EnrollmentResponse",ResourceType.EnrollmentResponse},
        {"EpisodeOfCare",ResourceType.EpisodeOfCare},
        {"ExplanationOfBenefit",ResourceType.ExplanationOfBenefit},
        {"FamilyMemberHistory",ResourceType.FamilyMemberHistory},
        {"Flag",ResourceType.Flag},
        {"Goal",ResourceType.Goal},
        {"Group",ResourceType.Group},
        {"HealthcareService",ResourceType.HealthcareService},
        {"ImagingObjectSelection",ResourceType.ImagingObjectSelection},
        {"ImagingStudy",ResourceType.ImagingStudy},
        {"Immunization",ResourceType.Immunization},
        {"ImmunizationRecommendation",ResourceType.ImmunizationRecommendation},
        {"List",ResourceType.List},
        {"Location",ResourceType.Location},
        {"Media",ResourceType.Media},
        {"Medication",ResourceType.Medication},
        {"MedicationAdministration",ResourceType.MedicationAdministration},
        {"MedicationDispense",ResourceType.MedicationDispense},
        {"MedicationOrder",ResourceType.MedicationOrder},
        {"MedicationStatement",ResourceType.MedicationStatement},
        {"MessageHeader",ResourceType.MessageHeader},
        {"NamingSystem",ResourceType.NamingSystem},
        {"NutritionOrder",ResourceType.NutritionOrder},
        {"Observation",ResourceType.Observation},
        {"OperationDefinition",ResourceType.OperationDefinition},
        {"OperationOutcome",ResourceType.OperationOutcome},
        {"Order",ResourceType.Order},
        {"OrderResponse",ResourceType.OrderResponse},
        {"Organization",ResourceType.Organization},
        {"Patient",ResourceType.Patient},
        {"PaymentNotice",ResourceType.PaymentNotice},
        {"PaymentReconciliation",ResourceType.PaymentReconciliation},
        {"Person",ResourceType.Person},
        {"Practitioner",ResourceType.Practitioner},
        {"Procedure",ResourceType.Procedure},
        {"ProcedureRequest",ResourceType.ProcedureRequest},
        {"ProcessRequest",ResourceType.ProcessRequest},
        {"ProcessResponse",ResourceType.ProcessResponse},
        {"Provenance",ResourceType.Provenance},
        {"Questionnaire",ResourceType.Questionnaire},
        {"QuestionnaireResponse",ResourceType.QuestionnaireResponse},
        {"ReferralRequest",ResourceType.ReferralRequest},
        {"RelatedPerson",ResourceType.RelatedPerson},
        {"RiskAssessment",ResourceType.RiskAssessment},
        {"Schedule",ResourceType.Schedule},
        {"SearchParameter",ResourceType.SearchParameter},
        {"Slot",ResourceType.Slot},
        {"Specimen",ResourceType.Specimen},
        {"StructureDefinition",ResourceType.StructureDefinition},
        {"Subscription",ResourceType.Subscription},
        {"Substance",ResourceType.Substance},
        {"SupplyDelivery",ResourceType.SupplyDelivery},
        {"SupplyRequest",ResourceType.SupplyRequest},
        {"TestScript",ResourceType.TestScript},
        {"ValueSet",ResourceType.ValueSet},    
        {"VisionPrescription",ResourceType.VisionPrescription}
      };
    }

    //If you add a SearchParameterName here then you also need to add it to the Dictionary below it: "GetSearchParameterNameDictionary"
    public static class Search
    {
      public enum SearchParameterName
      {
        None,
        _Id,
        Active,
        Family,
        Given,
        Name,
        Phonetic,
        Identifier,
        Page,
        Description,
        Code,
        Date,
        Context
      };


      public static Dictionary<string, SearchParameterName> GetSearchParameterNameDictionary()
      {        
        return new Dictionary<string, SearchParameterName>()
      {
        {"_id", SearchParameterName._Id},
        {"active",SearchParameterName.Active},
        {"family",SearchParameterName.Family},
        {"given",SearchParameterName.Given},        
        {"name",SearchParameterName.Name}, 
        {"phonetic",SearchParameterName.Phonetic}, 
        {"identifier",SearchParameterName.Identifier}, 
        {"page",SearchParameterName.Page},
        {"description",SearchParameterName.Description},
        {"code",SearchParameterName.Code},
        {"date",SearchParameterName.Date},
        {"context",SearchParameterName.Context}
      };
      }

      public static Dictionary<string, SearchPrefixType> GetSearchPrefixTypeDictionary()
      {
        return new Dictionary<string, SearchPrefixType>()
      {
        {"ap", SearchPrefixType.Approximately},
        {"eb", SearchPrefixType.EndsBefore},
        {"eq", SearchPrefixType.Equal},
        {"gt", SearchPrefixType.Greater},
        {"ge", SearchPrefixType.GreaterOrEqual},
        {"lt", SearchPrefixType.Less},
        {"le", SearchPrefixType.LessOrEqual},
        {"ne", SearchPrefixType.NotEqual},
        {"sa", SearchPrefixType.StartsAfter}
      };
      }


    }
  }
}
