namespace Pyro.DataLayer.MigrationsMicrosoftSQLServer
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class DropOldLowHighUtcDateTimeColoums : DbMigration
    {
        public override void Up()
        {
            DropIndex("dbo.ActivityDefinitionResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ActivityDefinitionResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.AdverseEventResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.AdverseEventResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.AllergyIntoleranceResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.AllergyIntoleranceResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.AppointmentResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.AppointmentResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.AppointmentResponseResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.AppointmentResponseResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.AuditEventResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.AuditEventResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.BasicResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.BasicResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.BinaryResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.BinaryResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.BodySiteResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.BodySiteResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.BundleResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.BundleResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.CapabilityStatementResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.CapabilityStatementResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.CarePlanResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.CarePlanResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.CareTeamResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.CareTeamResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ChargeItemResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ChargeItemResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ClaimResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ClaimResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ClaimResponseResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ClaimResponseResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ClinicalImpressionResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ClinicalImpressionResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.CodeSystemResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.CodeSystemResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.CommunicationResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.CommunicationResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.CommunicationRequestResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.CommunicationRequestResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.CompartmentDefinitionResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.CompartmentDefinitionResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.CompositionResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.CompositionResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ConceptMapResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ConceptMapResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ConditionResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ConditionResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ConsentResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ConsentResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ContractResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ContractResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.CoverageResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.CoverageResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.DataElementResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.DataElementResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.DetectedIssueResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.DetectedIssueResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.DeviceComponentResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.DeviceComponentResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.DeviceResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.DeviceResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.DeviceMetricResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.DeviceMetricResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.DeviceRequestResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.DeviceRequestResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.DeviceUseStatementResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.DeviceUseStatementResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.DiagnosticReportResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.DiagnosticReportResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.DocumentManifestResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.DocumentManifestResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.DocumentReferenceResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.DocumentReferenceResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.EligibilityRequestResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.EligibilityRequestResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.EligibilityResponseResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.EligibilityResponseResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.EncounterResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.EncounterResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.EndpointResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.EndpointResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.EnrollmentRequestResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.EnrollmentRequestResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.EnrollmentResponseResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.EnrollmentResponseResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.EpisodeOfCareResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.EpisodeOfCareResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ExpansionProfileResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ExpansionProfileResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ExplanationOfBenefitResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ExplanationOfBenefitResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.FamilyMemberHistoryResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.FamilyMemberHistoryResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.FlagResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.FlagResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.GoalResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.GoalResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.GraphDefinitionResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.GraphDefinitionResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.GroupResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.GroupResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.GuidanceResponseResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.GuidanceResponseResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.HealthcareServiceResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.HealthcareServiceResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ImagingManifestResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ImagingManifestResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ImagingStudyResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ImagingStudyResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ImmunizationResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ImmunizationResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ImmunizationRecommendationResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ImmunizationRecommendationResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ImplementationGuideResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ImplementationGuideResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.LibraryResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.LibraryResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.LinkageResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.LinkageResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ListResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ListResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.LocationResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.LocationResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.MeasureResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.MeasureResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.MeasureReportResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.MeasureReportResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.MediaResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.MediaResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.MedicationAdministrationResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.MedicationAdministrationResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.MedicationDispenseResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.MedicationDispenseResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.MedicationResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.MedicationResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.MedicationRequestResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.MedicationRequestResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.MedicationStatementResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.MedicationStatementResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.MessageDefinitionResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.MessageDefinitionResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.MessageHeaderResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.MessageHeaderResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.NamingSystemResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.NamingSystemResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.NutritionOrderResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.NutritionOrderResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ObservationResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ObservationResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.OperationDefinitionResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.OperationDefinitionResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.OperationOutcomeResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.OperationOutcomeResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.OrganizationResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.OrganizationResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ParametersResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ParametersResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.PatientResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.PatientResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.PaymentNoticeResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.PaymentNoticeResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.PaymentReconciliationResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.PaymentReconciliationResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.PersonResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.PersonResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.PlanDefinitionResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.PlanDefinitionResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.PractitionerResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.PractitionerResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.PractitionerRoleResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.PractitionerRoleResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ProcedureResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ProcedureResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ProcedureRequestResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ProcedureRequestResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ProcessRequestResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ProcessRequestResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ProcessResponseResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ProcessResponseResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ProvenanceResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ProvenanceResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.QuestionnaireResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.QuestionnaireResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.QuestionnaireResponseResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.QuestionnaireResponseResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ReferralRequestResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ReferralRequestResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.RelatedPersonResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.RelatedPersonResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.RequestGroupResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.RequestGroupResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ResearchStudyResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ResearchStudyResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ResearchSubjectResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ResearchSubjectResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.RiskAssessmentResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.RiskAssessmentResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ScheduleResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ScheduleResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.SearchParameterResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.SearchParameterResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.SequenceResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.SequenceResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ServiceDefinitionResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ServiceDefinitionResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.SlotResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.SlotResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.SpecimenResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.SpecimenResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.StructureDefinitionResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.StructureDefinitionResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.StructureMapResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.StructureMapResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.SubscriptionResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.SubscriptionResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.SubstanceResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.SubstanceResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.SupplyDeliveryResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.SupplyDeliveryResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.SupplyRequestResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.SupplyRequestResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.TaskResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.TaskResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.TestReportResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.TestReportResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.TestScriptResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.TestScriptResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.ValueSetResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.ValueSetResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.VisionPrescriptionResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.VisionPrescriptionResIndexDateTime", "ix_DateTimeOffsetLow");
            DropIndex("dbo.AccountResIndexDateTime", "ix_DateTimeOffsetHigh");
            DropIndex("dbo.AccountResIndexDateTime", "ix_DateTimeOffsetLow");
            DropColumn("dbo.ActivityDefinitionResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ActivityDefinitionResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.AdverseEventResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.AdverseEventResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.AllergyIntoleranceResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.AllergyIntoleranceResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.AppointmentResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.AppointmentResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.AppointmentResponseResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.AppointmentResponseResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.AuditEventResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.AuditEventResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.BasicResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.BasicResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.BinaryResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.BinaryResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.BodySiteResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.BodySiteResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.BundleResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.BundleResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.CapabilityStatementResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.CapabilityStatementResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.CarePlanResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.CarePlanResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.CareTeamResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.CareTeamResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ChargeItemResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ChargeItemResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ClaimResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ClaimResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ClaimResponseResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ClaimResponseResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ClinicalImpressionResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ClinicalImpressionResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.CodeSystemResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.CodeSystemResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.CommunicationResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.CommunicationResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.CommunicationRequestResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.CommunicationRequestResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.CompartmentDefinitionResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.CompartmentDefinitionResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.CompositionResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.CompositionResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ConceptMapResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ConceptMapResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ConditionResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ConditionResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ConsentResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ConsentResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ContractResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ContractResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.CoverageResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.CoverageResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.DataElementResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.DataElementResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.DetectedIssueResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.DetectedIssueResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.DeviceComponentResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.DeviceComponentResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.DeviceResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.DeviceResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.DeviceMetricResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.DeviceMetricResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.DeviceRequestResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.DeviceRequestResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.DeviceUseStatementResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.DeviceUseStatementResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.DiagnosticReportResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.DiagnosticReportResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.DocumentManifestResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.DocumentManifestResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.DocumentReferenceResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.DocumentReferenceResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.EligibilityRequestResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.EligibilityRequestResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.EligibilityResponseResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.EligibilityResponseResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.EncounterResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.EncounterResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.EndpointResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.EndpointResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.EnrollmentRequestResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.EnrollmentRequestResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.EnrollmentResponseResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.EnrollmentResponseResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.EpisodeOfCareResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.EpisodeOfCareResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ExpansionProfileResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ExpansionProfileResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ExplanationOfBenefitResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ExplanationOfBenefitResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.FamilyMemberHistoryResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.FamilyMemberHistoryResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.FlagResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.FlagResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.GoalResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.GoalResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.GraphDefinitionResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.GraphDefinitionResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.GroupResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.GroupResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.GuidanceResponseResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.GuidanceResponseResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.HealthcareServiceResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.HealthcareServiceResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ImagingManifestResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ImagingManifestResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ImagingStudyResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ImagingStudyResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ImmunizationResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ImmunizationResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ImmunizationRecommendationResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ImmunizationRecommendationResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ImplementationGuideResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ImplementationGuideResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.LibraryResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.LibraryResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.LinkageResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.LinkageResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ListResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ListResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.LocationResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.LocationResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.MeasureResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.MeasureResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.MeasureReportResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.MeasureReportResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.MediaResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.MediaResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.MedicationAdministrationResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.MedicationAdministrationResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.MedicationDispenseResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.MedicationDispenseResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.MedicationResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.MedicationResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.MedicationRequestResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.MedicationRequestResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.MedicationStatementResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.MedicationStatementResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.MessageDefinitionResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.MessageDefinitionResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.MessageHeaderResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.MessageHeaderResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.NamingSystemResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.NamingSystemResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.NutritionOrderResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.NutritionOrderResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ObservationResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ObservationResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.OperationDefinitionResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.OperationDefinitionResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.OperationOutcomeResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.OperationOutcomeResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.OrganizationResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.OrganizationResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ParametersResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ParametersResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.PatientResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.PatientResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.PaymentNoticeResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.PaymentNoticeResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.PaymentReconciliationResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.PaymentReconciliationResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.PersonResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.PersonResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.PlanDefinitionResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.PlanDefinitionResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.PractitionerResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.PractitionerResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.PractitionerRoleResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.PractitionerRoleResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ProcedureResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ProcedureResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ProcedureRequestResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ProcedureRequestResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ProcessRequestResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ProcessRequestResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ProcessResponseResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ProcessResponseResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ProvenanceResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ProvenanceResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.QuestionnaireResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.QuestionnaireResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.QuestionnaireResponseResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.QuestionnaireResponseResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ReferralRequestResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ReferralRequestResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.RelatedPersonResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.RelatedPersonResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.RequestGroupResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.RequestGroupResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ResearchStudyResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ResearchStudyResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ResearchSubjectResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ResearchSubjectResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.RiskAssessmentResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.RiskAssessmentResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ScheduleResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ScheduleResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.SearchParameterResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.SearchParameterResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.SequenceResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.SequenceResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ServiceDefinitionResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ServiceDefinitionResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.SlotResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.SlotResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.SpecimenResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.SpecimenResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.StructureDefinitionResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.StructureDefinitionResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.StructureMapResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.StructureMapResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.SubscriptionResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.SubscriptionResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.SubstanceResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.SubstanceResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.SupplyDeliveryResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.SupplyDeliveryResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.SupplyRequestResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.SupplyRequestResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.TaskResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.TaskResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.TestReportResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.TestReportResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.TestScriptResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.TestScriptResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.ValueSetResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.ValueSetResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.VisionPrescriptionResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.VisionPrescriptionResIndexDateTime", "DateTimeOffsetLow");
            DropColumn("dbo.AccountResIndexDateTime", "DateTimeOffsetHigh");
            DropColumn("dbo.AccountResIndexDateTime", "DateTimeOffsetLow");
        }
        
        public override void Down()
        {
            AddColumn("dbo.AccountResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.AccountResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.VisionPrescriptionResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.VisionPrescriptionResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ValueSetResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ValueSetResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.TestScriptResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.TestScriptResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.TestReportResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.TestReportResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.TaskResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.TaskResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.SupplyRequestResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.SupplyRequestResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.SupplyDeliveryResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.SupplyDeliveryResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.SubstanceResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.SubstanceResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.SubscriptionResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.SubscriptionResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.StructureMapResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.StructureMapResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.StructureDefinitionResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.StructureDefinitionResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.SpecimenResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.SpecimenResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.SlotResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.SlotResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ServiceDefinitionResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ServiceDefinitionResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.SequenceResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.SequenceResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.SearchParameterResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.SearchParameterResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ScheduleResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ScheduleResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.RiskAssessmentResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.RiskAssessmentResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ResearchSubjectResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ResearchSubjectResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ResearchStudyResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ResearchStudyResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.RequestGroupResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.RequestGroupResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.RelatedPersonResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.RelatedPersonResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ReferralRequestResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ReferralRequestResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.QuestionnaireResponseResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.QuestionnaireResponseResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.QuestionnaireResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.QuestionnaireResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ProvenanceResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ProvenanceResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ProcessResponseResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ProcessResponseResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ProcessRequestResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ProcessRequestResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ProcedureRequestResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ProcedureRequestResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ProcedureResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ProcedureResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.PractitionerRoleResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.PractitionerRoleResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.PractitionerResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.PractitionerResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.PlanDefinitionResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.PlanDefinitionResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.PersonResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.PersonResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.PaymentReconciliationResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.PaymentReconciliationResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.PaymentNoticeResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.PaymentNoticeResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.PatientResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.PatientResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ParametersResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ParametersResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.OrganizationResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.OrganizationResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.OperationOutcomeResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.OperationOutcomeResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.OperationDefinitionResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.OperationDefinitionResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ObservationResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ObservationResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.NutritionOrderResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.NutritionOrderResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.NamingSystemResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.NamingSystemResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MessageHeaderResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MessageHeaderResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MessageDefinitionResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MessageDefinitionResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MedicationStatementResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MedicationStatementResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MedicationRequestResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MedicationRequestResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MedicationResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MedicationResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MedicationDispenseResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MedicationDispenseResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MedicationAdministrationResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MedicationAdministrationResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MediaResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MediaResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MeasureReportResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MeasureReportResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MeasureResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.MeasureResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.LocationResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.LocationResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ListResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ListResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.LinkageResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.LinkageResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.LibraryResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.LibraryResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ImplementationGuideResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ImplementationGuideResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ImmunizationRecommendationResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ImmunizationRecommendationResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ImmunizationResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ImmunizationResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ImagingStudyResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ImagingStudyResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ImagingManifestResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ImagingManifestResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.HealthcareServiceResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.HealthcareServiceResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.GuidanceResponseResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.GuidanceResponseResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.GroupResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.GroupResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.GraphDefinitionResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.GraphDefinitionResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.GoalResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.GoalResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.FlagResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.FlagResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.FamilyMemberHistoryResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.FamilyMemberHistoryResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ExplanationOfBenefitResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ExplanationOfBenefitResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ExpansionProfileResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ExpansionProfileResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.EpisodeOfCareResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.EpisodeOfCareResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.EnrollmentResponseResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.EnrollmentResponseResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.EnrollmentRequestResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.EnrollmentRequestResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.EndpointResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.EndpointResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.EncounterResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.EncounterResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.EligibilityResponseResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.EligibilityResponseResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.EligibilityRequestResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.EligibilityRequestResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DocumentReferenceResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DocumentReferenceResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DocumentManifestResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DocumentManifestResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DiagnosticReportResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DiagnosticReportResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DeviceUseStatementResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DeviceUseStatementResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DeviceRequestResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DeviceRequestResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DeviceMetricResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DeviceMetricResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DeviceResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DeviceResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DeviceComponentResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DeviceComponentResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DetectedIssueResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DetectedIssueResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DataElementResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.DataElementResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.CoverageResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.CoverageResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ContractResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ContractResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ConsentResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ConsentResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ConditionResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ConditionResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ConceptMapResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ConceptMapResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.CompositionResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.CompositionResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.CompartmentDefinitionResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.CompartmentDefinitionResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.CommunicationRequestResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.CommunicationRequestResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.CommunicationResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.CommunicationResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.CodeSystemResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.CodeSystemResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ClinicalImpressionResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ClinicalImpressionResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ClaimResponseResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ClaimResponseResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ClaimResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ClaimResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ChargeItemResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ChargeItemResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.CareTeamResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.CareTeamResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.CarePlanResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.CarePlanResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.CapabilityStatementResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.CapabilityStatementResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.BundleResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.BundleResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.BodySiteResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.BodySiteResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.BinaryResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.BinaryResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.BasicResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.BasicResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.AuditEventResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.AuditEventResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.AppointmentResponseResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.AppointmentResponseResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.AppointmentResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.AppointmentResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.AllergyIntoleranceResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.AllergyIntoleranceResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.AdverseEventResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.AdverseEventResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ActivityDefinitionResIndexDateTime", "DateTimeOffsetLow", c => c.DateTimeOffset(precision: 3));
            AddColumn("dbo.ActivityDefinitionResIndexDateTime", "DateTimeOffsetHigh", c => c.DateTimeOffset(precision: 3));
            CreateIndex("dbo.AccountResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.AccountResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.VisionPrescriptionResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.VisionPrescriptionResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ValueSetResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ValueSetResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.TestScriptResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.TestScriptResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.TestReportResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.TestReportResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.TaskResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.TaskResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.SupplyRequestResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.SupplyRequestResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.SupplyDeliveryResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.SupplyDeliveryResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.SubstanceResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.SubstanceResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.SubscriptionResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.SubscriptionResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.StructureMapResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.StructureMapResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.StructureDefinitionResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.StructureDefinitionResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.SpecimenResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.SpecimenResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.SlotResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.SlotResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ServiceDefinitionResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ServiceDefinitionResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.SequenceResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.SequenceResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.SearchParameterResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.SearchParameterResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ScheduleResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ScheduleResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.RiskAssessmentResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.RiskAssessmentResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ResearchSubjectResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ResearchSubjectResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ResearchStudyResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ResearchStudyResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.RequestGroupResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.RequestGroupResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.RelatedPersonResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.RelatedPersonResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ReferralRequestResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ReferralRequestResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.QuestionnaireResponseResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.QuestionnaireResponseResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.QuestionnaireResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.QuestionnaireResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ProvenanceResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ProvenanceResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ProcessResponseResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ProcessResponseResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ProcessRequestResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ProcessRequestResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ProcedureRequestResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ProcedureRequestResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ProcedureResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ProcedureResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.PractitionerRoleResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.PractitionerRoleResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.PractitionerResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.PractitionerResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.PlanDefinitionResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.PlanDefinitionResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.PersonResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.PersonResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.PaymentReconciliationResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.PaymentReconciliationResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.PaymentNoticeResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.PaymentNoticeResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.PatientResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.PatientResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ParametersResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ParametersResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.OrganizationResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.OrganizationResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.OperationOutcomeResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.OperationOutcomeResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.OperationDefinitionResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.OperationDefinitionResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ObservationResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ObservationResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.NutritionOrderResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.NutritionOrderResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.NamingSystemResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.NamingSystemResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.MessageHeaderResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.MessageHeaderResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.MessageDefinitionResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.MessageDefinitionResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.MedicationStatementResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.MedicationStatementResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.MedicationRequestResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.MedicationRequestResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.MedicationResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.MedicationResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.MedicationDispenseResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.MedicationDispenseResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.MedicationAdministrationResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.MedicationAdministrationResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.MediaResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.MediaResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.MeasureReportResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.MeasureReportResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.MeasureResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.MeasureResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.LocationResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.LocationResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ListResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ListResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.LinkageResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.LinkageResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.LibraryResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.LibraryResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ImplementationGuideResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ImplementationGuideResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ImmunizationRecommendationResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ImmunizationRecommendationResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ImmunizationResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ImmunizationResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ImagingStudyResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ImagingStudyResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ImagingManifestResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ImagingManifestResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.HealthcareServiceResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.HealthcareServiceResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.GuidanceResponseResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.GuidanceResponseResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.GroupResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.GroupResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.GraphDefinitionResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.GraphDefinitionResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.GoalResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.GoalResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.FlagResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.FlagResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.FamilyMemberHistoryResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.FamilyMemberHistoryResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ExplanationOfBenefitResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ExplanationOfBenefitResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ExpansionProfileResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ExpansionProfileResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.EpisodeOfCareResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.EpisodeOfCareResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.EnrollmentResponseResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.EnrollmentResponseResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.EnrollmentRequestResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.EnrollmentRequestResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.EndpointResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.EndpointResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.EncounterResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.EncounterResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.EligibilityResponseResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.EligibilityResponseResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.EligibilityRequestResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.EligibilityRequestResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.DocumentReferenceResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.DocumentReferenceResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.DocumentManifestResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.DocumentManifestResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.DiagnosticReportResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.DiagnosticReportResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.DeviceUseStatementResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.DeviceUseStatementResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.DeviceRequestResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.DeviceRequestResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.DeviceMetricResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.DeviceMetricResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.DeviceResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.DeviceResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.DeviceComponentResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.DeviceComponentResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.DetectedIssueResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.DetectedIssueResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.DataElementResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.DataElementResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.CoverageResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.CoverageResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ContractResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ContractResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ConsentResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ConsentResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ConditionResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ConditionResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ConceptMapResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ConceptMapResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.CompositionResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.CompositionResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.CompartmentDefinitionResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.CompartmentDefinitionResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.CommunicationRequestResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.CommunicationRequestResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.CommunicationResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.CommunicationResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.CodeSystemResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.CodeSystemResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ClinicalImpressionResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ClinicalImpressionResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ClaimResponseResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ClaimResponseResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ClaimResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ClaimResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ChargeItemResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ChargeItemResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.CareTeamResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.CareTeamResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.CarePlanResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.CarePlanResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.CapabilityStatementResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.CapabilityStatementResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.BundleResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.BundleResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.BodySiteResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.BodySiteResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.BinaryResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.BinaryResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.BasicResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.BasicResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.AuditEventResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.AuditEventResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.AppointmentResponseResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.AppointmentResponseResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.AppointmentResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.AppointmentResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.AllergyIntoleranceResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.AllergyIntoleranceResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.AdverseEventResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.AdverseEventResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
            CreateIndex("dbo.ActivityDefinitionResIndexDateTime", "DateTimeOffsetLow", name: "ix_DateTimeOffsetLow");
            CreateIndex("dbo.ActivityDefinitionResIndexDateTime", "DateTimeOffsetHigh", name: "ix_DateTimeOffsetHigh");
        }
    }
}
