// <auto-generated />
namespace Pyro.DataLayer.MigrationsMicrosoftSQLServer
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CaseSensitive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CaseSensitive));
        
        string IMigrationMetadata.Id
        {
            get { return "201810041523325_CaseSensitive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
