namespace Pyro.DataLayer.MigrationsMicrosoftSQLServer
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddNewLowHighUtcDateTimeColoums : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.ActivityDefinitionResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ActivityDefinitionResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.AdverseEventResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.AdverseEventResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.AllergyIntoleranceResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.AllergyIntoleranceResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.AppointmentResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.AppointmentResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.AppointmentResponseResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.AppointmentResponseResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.AuditEventResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.AuditEventResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.BasicResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.BasicResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.BinaryResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.BinaryResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.BodySiteResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.BodySiteResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.BundleResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.BundleResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.CapabilityStatementResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.CapabilityStatementResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.CarePlanResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.CarePlanResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.CareTeamResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.CareTeamResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ChargeItemResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ChargeItemResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ClaimResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ClaimResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ClaimResponseResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ClaimResponseResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ClinicalImpressionResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ClinicalImpressionResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.CodeSystemResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.CodeSystemResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.CommunicationResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.CommunicationResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.CommunicationRequestResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.CommunicationRequestResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.CompartmentDefinitionResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.CompartmentDefinitionResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.CompositionResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.CompositionResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ConceptMapResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ConceptMapResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ConditionResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ConditionResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ConsentResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ConsentResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ContractResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ContractResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.CoverageResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.CoverageResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DataElementResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DataElementResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DetectedIssueResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DetectedIssueResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DeviceComponentResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DeviceComponentResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DeviceResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DeviceResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DeviceMetricResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DeviceMetricResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DeviceRequestResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DeviceRequestResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DeviceUseStatementResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DeviceUseStatementResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DiagnosticReportResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DiagnosticReportResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DocumentManifestResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DocumentManifestResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DocumentReferenceResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.DocumentReferenceResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.EligibilityRequestResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.EligibilityRequestResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.EligibilityResponseResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.EligibilityResponseResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.EncounterResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.EncounterResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.EndpointResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.EndpointResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.EnrollmentRequestResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.EnrollmentRequestResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.EnrollmentResponseResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.EnrollmentResponseResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.EpisodeOfCareResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.EpisodeOfCareResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ExpansionProfileResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ExpansionProfileResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ExplanationOfBenefitResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ExplanationOfBenefitResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.FamilyMemberHistoryResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.FamilyMemberHistoryResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.FlagResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.FlagResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.GoalResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.GoalResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.GraphDefinitionResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.GraphDefinitionResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.GroupResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.GroupResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.GuidanceResponseResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.GuidanceResponseResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.HealthcareServiceResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.HealthcareServiceResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ImagingManifestResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ImagingManifestResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ImagingStudyResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ImagingStudyResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ImmunizationResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ImmunizationResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ImmunizationRecommendationResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ImmunizationRecommendationResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ImplementationGuideResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ImplementationGuideResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.LibraryResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.LibraryResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.LinkageResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.LinkageResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ListResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ListResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.LocationResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.LocationResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MeasureResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MeasureResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MeasureReportResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MeasureReportResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MediaResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MediaResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MedicationAdministrationResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MedicationAdministrationResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MedicationDispenseResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MedicationDispenseResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MedicationResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MedicationResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MedicationRequestResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MedicationRequestResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MedicationStatementResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MedicationStatementResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MessageDefinitionResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MessageDefinitionResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MessageHeaderResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.MessageHeaderResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.NamingSystemResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.NamingSystemResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.NutritionOrderResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.NutritionOrderResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ObservationResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ObservationResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.OperationDefinitionResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.OperationDefinitionResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.OperationOutcomeResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.OperationOutcomeResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.OrganizationResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.OrganizationResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ParametersResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ParametersResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.PatientResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.PatientResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.PaymentNoticeResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.PaymentNoticeResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.PaymentReconciliationResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.PaymentReconciliationResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.PersonResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.PersonResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.PlanDefinitionResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.PlanDefinitionResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.PractitionerResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.PractitionerResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.PractitionerRoleResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.PractitionerRoleResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ProcedureResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ProcedureResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ProcedureRequestResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ProcedureRequestResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ProcessRequestResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ProcessRequestResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ProcessResponseResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ProcessResponseResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ProvenanceResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ProvenanceResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.QuestionnaireResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.QuestionnaireResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.QuestionnaireResponseResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.QuestionnaireResponseResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ReferralRequestResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ReferralRequestResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.RelatedPersonResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.RelatedPersonResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.RequestGroupResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.RequestGroupResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ResearchStudyResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ResearchStudyResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ResearchSubjectResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ResearchSubjectResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.RiskAssessmentResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.RiskAssessmentResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ScheduleResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ScheduleResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.SearchParameterResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.SearchParameterResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.SequenceResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.SequenceResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ServiceDefinitionResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ServiceDefinitionResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.SlotResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.SlotResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.SpecimenResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.SpecimenResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.StructureDefinitionResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.StructureDefinitionResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.StructureMapResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.StructureMapResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.SubscriptionResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.SubscriptionResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.SubstanceResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.SubstanceResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.SupplyDeliveryResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.SupplyDeliveryResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.SupplyRequestResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.SupplyRequestResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.TaskResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.TaskResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.TestReportResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.TestReportResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.TestScriptResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.TestScriptResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ValueSetResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.ValueSetResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.VisionPrescriptionResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.VisionPrescriptionResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.AccountResIndexDateTime", "LowUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AddColumn("dbo.AccountResIndexDateTime", "HighUtcDateTime", c => c.DateTime(precision: 3, storeType: "datetime2"));
            AlterColumn("dbo._FhirRelease", "Date", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            CreateIndex("dbo.ActivityDefinitionResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ActivityDefinitionResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.AdverseEventResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.AdverseEventResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.AllergyIntoleranceResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.AllergyIntoleranceResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.AppointmentResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.AppointmentResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.AppointmentResponseResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.AppointmentResponseResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.AuditEventResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.AuditEventResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.BasicResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.BasicResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.BinaryResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.BinaryResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.BodySiteResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.BodySiteResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.BundleResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.BundleResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.CapabilityStatementResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.CapabilityStatementResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.CarePlanResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.CarePlanResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.CareTeamResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.CareTeamResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ChargeItemResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ChargeItemResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ClaimResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ClaimResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ClaimResponseResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ClaimResponseResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ClinicalImpressionResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ClinicalImpressionResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.CodeSystemResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.CodeSystemResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.CommunicationResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.CommunicationResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.CommunicationRequestResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.CommunicationRequestResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.CompartmentDefinitionResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.CompartmentDefinitionResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.CompositionResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.CompositionResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ConceptMapResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ConceptMapResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ConditionResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ConditionResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ConsentResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ConsentResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ContractResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ContractResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.CoverageResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.CoverageResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.DataElementResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.DataElementResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.DetectedIssueResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.DetectedIssueResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.DeviceComponentResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.DeviceComponentResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.DeviceResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.DeviceResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.DeviceMetricResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.DeviceMetricResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.DeviceRequestResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.DeviceRequestResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.DeviceUseStatementResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.DeviceUseStatementResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.DiagnosticReportResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.DiagnosticReportResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.DocumentManifestResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.DocumentManifestResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.DocumentReferenceResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.DocumentReferenceResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.EligibilityRequestResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.EligibilityRequestResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.EligibilityResponseResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.EligibilityResponseResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.EncounterResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.EncounterResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.EndpointResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.EndpointResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.EnrollmentRequestResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.EnrollmentRequestResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.EnrollmentResponseResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.EnrollmentResponseResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.EpisodeOfCareResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.EpisodeOfCareResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ExpansionProfileResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ExpansionProfileResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ExplanationOfBenefitResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ExplanationOfBenefitResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.FamilyMemberHistoryResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.FamilyMemberHistoryResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.FlagResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.FlagResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.GoalResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.GoalResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.GraphDefinitionResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.GraphDefinitionResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.GroupResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.GroupResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.GuidanceResponseResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.GuidanceResponseResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.HealthcareServiceResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.HealthcareServiceResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ImagingManifestResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ImagingManifestResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ImagingStudyResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ImagingStudyResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ImmunizationResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ImmunizationResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ImmunizationRecommendationResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ImmunizationRecommendationResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ImplementationGuideResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ImplementationGuideResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.LibraryResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.LibraryResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.LinkageResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.LinkageResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ListResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ListResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.LocationResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.LocationResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.MeasureResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.MeasureResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.MeasureReportResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.MeasureReportResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.MediaResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.MediaResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.MedicationAdministrationResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.MedicationAdministrationResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.MedicationDispenseResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.MedicationDispenseResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.MedicationResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.MedicationResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.MedicationRequestResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.MedicationRequestResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.MedicationStatementResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.MedicationStatementResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.MessageDefinitionResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.MessageDefinitionResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.MessageHeaderResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.MessageHeaderResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.NamingSystemResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.NamingSystemResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.NutritionOrderResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.NutritionOrderResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ObservationResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ObservationResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.OperationDefinitionResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.OperationDefinitionResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.OperationOutcomeResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.OperationOutcomeResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.OrganizationResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.OrganizationResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ParametersResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ParametersResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.PatientResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.PatientResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.PaymentNoticeResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.PaymentNoticeResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.PaymentReconciliationResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.PaymentReconciliationResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.PersonResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.PersonResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.PlanDefinitionResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.PlanDefinitionResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.PractitionerResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.PractitionerResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.PractitionerRoleResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.PractitionerRoleResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ProcedureResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ProcedureResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ProcedureRequestResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ProcedureRequestResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ProcessRequestResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ProcessRequestResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ProcessResponseResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ProcessResponseResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ProvenanceResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ProvenanceResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.QuestionnaireResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.QuestionnaireResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.QuestionnaireResponseResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.QuestionnaireResponseResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ReferralRequestResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ReferralRequestResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.RelatedPersonResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.RelatedPersonResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.RequestGroupResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.RequestGroupResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ResearchStudyResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ResearchStudyResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ResearchSubjectResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ResearchSubjectResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.RiskAssessmentResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.RiskAssessmentResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ScheduleResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ScheduleResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.SearchParameterResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.SearchParameterResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.SequenceResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.SequenceResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ServiceDefinitionResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ServiceDefinitionResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.SlotResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.SlotResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.SpecimenResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.SpecimenResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.StructureDefinitionResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.StructureDefinitionResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.StructureMapResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.StructureMapResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.SubscriptionResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.SubscriptionResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.SubstanceResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.SubstanceResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.SupplyDeliveryResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.SupplyDeliveryResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.SupplyRequestResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.SupplyRequestResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.TaskResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.TaskResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.TestReportResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.TestReportResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.TestScriptResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.TestScriptResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.ValueSetResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.ValueSetResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.VisionPrescriptionResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.VisionPrescriptionResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
            CreateIndex("dbo.AccountResIndexDateTime", "LowUtcDateTime", name: "ix_LowUtcDateTime");
            CreateIndex("dbo.AccountResIndexDateTime", "HighUtcDateTime", name: "ix_HighUtcDateTime");
        }
        
        public override void Down()
        {
            DropIndex("dbo.AccountResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.AccountResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.VisionPrescriptionResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.VisionPrescriptionResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ValueSetResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ValueSetResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.TestScriptResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.TestScriptResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.TestReportResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.TestReportResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.TaskResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.TaskResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.SupplyRequestResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.SupplyRequestResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.SupplyDeliveryResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.SupplyDeliveryResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.SubstanceResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.SubstanceResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.SubscriptionResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.SubscriptionResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.StructureMapResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.StructureMapResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.StructureDefinitionResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.StructureDefinitionResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.SpecimenResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.SpecimenResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.SlotResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.SlotResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ServiceDefinitionResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ServiceDefinitionResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.SequenceResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.SequenceResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.SearchParameterResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.SearchParameterResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ScheduleResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ScheduleResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.RiskAssessmentResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.RiskAssessmentResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ResearchSubjectResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ResearchSubjectResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ResearchStudyResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ResearchStudyResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.RequestGroupResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.RequestGroupResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.RelatedPersonResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.RelatedPersonResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ReferralRequestResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ReferralRequestResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.QuestionnaireResponseResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.QuestionnaireResponseResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.QuestionnaireResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.QuestionnaireResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ProvenanceResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ProvenanceResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ProcessResponseResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ProcessResponseResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ProcessRequestResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ProcessRequestResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ProcedureRequestResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ProcedureRequestResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ProcedureResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ProcedureResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.PractitionerRoleResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.PractitionerRoleResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.PractitionerResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.PractitionerResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.PlanDefinitionResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.PlanDefinitionResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.PersonResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.PersonResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.PaymentReconciliationResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.PaymentReconciliationResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.PaymentNoticeResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.PaymentNoticeResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.PatientResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.PatientResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ParametersResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ParametersResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.OrganizationResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.OrganizationResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.OperationOutcomeResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.OperationOutcomeResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.OperationDefinitionResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.OperationDefinitionResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ObservationResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ObservationResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.NutritionOrderResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.NutritionOrderResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.NamingSystemResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.NamingSystemResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.MessageHeaderResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.MessageHeaderResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.MessageDefinitionResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.MessageDefinitionResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.MedicationStatementResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.MedicationStatementResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.MedicationRequestResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.MedicationRequestResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.MedicationResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.MedicationResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.MedicationDispenseResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.MedicationDispenseResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.MedicationAdministrationResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.MedicationAdministrationResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.MediaResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.MediaResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.MeasureReportResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.MeasureReportResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.MeasureResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.MeasureResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.LocationResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.LocationResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ListResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ListResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.LinkageResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.LinkageResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.LibraryResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.LibraryResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ImplementationGuideResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ImplementationGuideResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ImmunizationRecommendationResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ImmunizationRecommendationResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ImmunizationResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ImmunizationResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ImagingStudyResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ImagingStudyResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ImagingManifestResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ImagingManifestResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.HealthcareServiceResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.HealthcareServiceResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.GuidanceResponseResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.GuidanceResponseResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.GroupResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.GroupResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.GraphDefinitionResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.GraphDefinitionResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.GoalResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.GoalResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.FlagResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.FlagResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.FamilyMemberHistoryResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.FamilyMemberHistoryResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ExplanationOfBenefitResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ExplanationOfBenefitResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ExpansionProfileResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ExpansionProfileResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.EpisodeOfCareResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.EpisodeOfCareResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.EnrollmentResponseResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.EnrollmentResponseResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.EnrollmentRequestResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.EnrollmentRequestResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.EndpointResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.EndpointResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.EncounterResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.EncounterResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.EligibilityResponseResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.EligibilityResponseResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.EligibilityRequestResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.EligibilityRequestResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.DocumentReferenceResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.DocumentReferenceResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.DocumentManifestResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.DocumentManifestResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.DiagnosticReportResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.DiagnosticReportResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.DeviceUseStatementResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.DeviceUseStatementResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.DeviceRequestResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.DeviceRequestResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.DeviceMetricResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.DeviceMetricResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.DeviceResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.DeviceResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.DeviceComponentResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.DeviceComponentResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.DetectedIssueResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.DetectedIssueResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.DataElementResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.DataElementResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.CoverageResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.CoverageResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ContractResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ContractResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ConsentResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ConsentResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ConditionResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ConditionResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ConceptMapResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ConceptMapResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.CompositionResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.CompositionResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.CompartmentDefinitionResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.CompartmentDefinitionResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.CommunicationRequestResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.CommunicationRequestResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.CommunicationResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.CommunicationResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.CodeSystemResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.CodeSystemResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ClinicalImpressionResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ClinicalImpressionResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ClaimResponseResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ClaimResponseResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ClaimResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ClaimResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ChargeItemResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ChargeItemResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.CareTeamResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.CareTeamResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.CarePlanResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.CarePlanResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.CapabilityStatementResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.CapabilityStatementResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.BundleResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.BundleResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.BodySiteResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.BodySiteResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.BinaryResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.BinaryResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.BasicResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.BasicResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.AuditEventResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.AuditEventResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.AppointmentResponseResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.AppointmentResponseResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.AppointmentResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.AppointmentResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.AllergyIntoleranceResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.AllergyIntoleranceResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.AdverseEventResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.AdverseEventResIndexDateTime", "ix_LowUtcDateTime");
            DropIndex("dbo.ActivityDefinitionResIndexDateTime", "ix_HighUtcDateTime");
            DropIndex("dbo.ActivityDefinitionResIndexDateTime", "ix_LowUtcDateTime");
            AlterColumn("dbo._FhirRelease", "Date", c => c.DateTime(nullable: false));
            DropColumn("dbo.AccountResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.AccountResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.VisionPrescriptionResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.VisionPrescriptionResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ValueSetResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ValueSetResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.TestScriptResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.TestScriptResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.TestReportResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.TestReportResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.TaskResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.TaskResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.SupplyRequestResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.SupplyRequestResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.SupplyDeliveryResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.SupplyDeliveryResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.SubstanceResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.SubstanceResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.SubscriptionResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.SubscriptionResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.StructureMapResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.StructureMapResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.StructureDefinitionResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.StructureDefinitionResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.SpecimenResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.SpecimenResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.SlotResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.SlotResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ServiceDefinitionResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ServiceDefinitionResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.SequenceResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.SequenceResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.SearchParameterResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.SearchParameterResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ScheduleResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ScheduleResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.RiskAssessmentResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.RiskAssessmentResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ResearchSubjectResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ResearchSubjectResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ResearchStudyResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ResearchStudyResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.RequestGroupResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.RequestGroupResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.RelatedPersonResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.RelatedPersonResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ReferralRequestResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ReferralRequestResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.QuestionnaireResponseResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.QuestionnaireResponseResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.QuestionnaireResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.QuestionnaireResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ProvenanceResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ProvenanceResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ProcessResponseResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ProcessResponseResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ProcessRequestResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ProcessRequestResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ProcedureRequestResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ProcedureRequestResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ProcedureResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ProcedureResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.PractitionerRoleResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.PractitionerRoleResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.PractitionerResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.PractitionerResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.PlanDefinitionResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.PlanDefinitionResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.PersonResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.PersonResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.PaymentReconciliationResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.PaymentReconciliationResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.PaymentNoticeResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.PaymentNoticeResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.PatientResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.PatientResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ParametersResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ParametersResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.OrganizationResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.OrganizationResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.OperationOutcomeResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.OperationOutcomeResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.OperationDefinitionResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.OperationDefinitionResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ObservationResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ObservationResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.NutritionOrderResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.NutritionOrderResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.NamingSystemResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.NamingSystemResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.MessageHeaderResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.MessageHeaderResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.MessageDefinitionResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.MessageDefinitionResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.MedicationStatementResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.MedicationStatementResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.MedicationRequestResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.MedicationRequestResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.MedicationResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.MedicationResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.MedicationDispenseResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.MedicationDispenseResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.MedicationAdministrationResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.MedicationAdministrationResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.MediaResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.MediaResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.MeasureReportResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.MeasureReportResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.MeasureResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.MeasureResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.LocationResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.LocationResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ListResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ListResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.LinkageResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.LinkageResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.LibraryResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.LibraryResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ImplementationGuideResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ImplementationGuideResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ImmunizationRecommendationResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ImmunizationRecommendationResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ImmunizationResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ImmunizationResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ImagingStudyResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ImagingStudyResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ImagingManifestResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ImagingManifestResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.HealthcareServiceResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.HealthcareServiceResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.GuidanceResponseResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.GuidanceResponseResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.GroupResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.GroupResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.GraphDefinitionResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.GraphDefinitionResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.GoalResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.GoalResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.FlagResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.FlagResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.FamilyMemberHistoryResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.FamilyMemberHistoryResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ExplanationOfBenefitResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ExplanationOfBenefitResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ExpansionProfileResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ExpansionProfileResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.EpisodeOfCareResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.EpisodeOfCareResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.EnrollmentResponseResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.EnrollmentResponseResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.EnrollmentRequestResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.EnrollmentRequestResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.EndpointResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.EndpointResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.EncounterResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.EncounterResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.EligibilityResponseResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.EligibilityResponseResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.EligibilityRequestResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.EligibilityRequestResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.DocumentReferenceResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.DocumentReferenceResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.DocumentManifestResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.DocumentManifestResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.DiagnosticReportResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.DiagnosticReportResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.DeviceUseStatementResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.DeviceUseStatementResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.DeviceRequestResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.DeviceRequestResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.DeviceMetricResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.DeviceMetricResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.DeviceResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.DeviceResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.DeviceComponentResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.DeviceComponentResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.DetectedIssueResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.DetectedIssueResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.DataElementResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.DataElementResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.CoverageResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.CoverageResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ContractResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ContractResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ConsentResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ConsentResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ConditionResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ConditionResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ConceptMapResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ConceptMapResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.CompositionResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.CompositionResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.CompartmentDefinitionResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.CompartmentDefinitionResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.CommunicationRequestResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.CommunicationRequestResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.CommunicationResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.CommunicationResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.CodeSystemResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.CodeSystemResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ClinicalImpressionResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ClinicalImpressionResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ClaimResponseResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ClaimResponseResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ClaimResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ClaimResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ChargeItemResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ChargeItemResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.CareTeamResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.CareTeamResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.CarePlanResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.CarePlanResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.CapabilityStatementResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.CapabilityStatementResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.BundleResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.BundleResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.BodySiteResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.BodySiteResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.BinaryResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.BinaryResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.BasicResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.BasicResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.AuditEventResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.AuditEventResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.AppointmentResponseResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.AppointmentResponseResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.AppointmentResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.AppointmentResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.AllergyIntoleranceResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.AllergyIntoleranceResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.AdverseEventResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.AdverseEventResIndexDateTime", "LowUtcDateTime");
            DropColumn("dbo.ActivityDefinitionResIndexDateTime", "HighUtcDateTime");
            DropColumn("dbo.ActivityDefinitionResIndexDateTime", "LowUtcDateTime");
        }
    }
}
