using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Diagnostics;
using Pyro.Common.Interfaces.Repositories;
using Pyro.DataLayer.Repository;
using Pyro.DataLayer.DbModel.EntityGenerated;
using Hl7.Fhir.Model;

//This file was code generated by Pyro.CodeGeneration.Template.MainTemplate.tt
//Generation TimeStamp: 29/08/2017 9:21:56 PM

namespace Pyro.DataLayer.DbModel.UnitOfWork
{  
  public partial class UnitOfWork : IUnitOfWork, IDisposable
  {    
    public IResourceRepository AccountRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<AccountRes, AccountResIndex, AccountResIndexString>(FHIRAllTypes.Account);     
      }
    }
    public IResourceRepository ActivityDefinitionRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ActivityDefinitionRes, ActivityDefinitionResIndex, ActivityDefinitionResIndexString>(FHIRAllTypes.ActivityDefinition);     
      }
    }
    public IResourceRepository AdverseEventRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<AdverseEventRes, AdverseEventResIndex, AdverseEventResIndexString>(FHIRAllTypes.AdverseEvent);     
      }
    }
    public IResourceRepository AllergyIntoleranceRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<AllergyIntoleranceRes, AllergyIntoleranceResIndex, AllergyIntoleranceResIndexString>(FHIRAllTypes.AllergyIntolerance);     
      }
    }
    public IResourceRepository AppointmentRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<AppointmentRes, AppointmentResIndex, AppointmentResIndexString>(FHIRAllTypes.Appointment);     
      }
    }
    public IResourceRepository AppointmentResponseRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<AppointmentResponseRes, AppointmentResponseResIndex, AppointmentResponseResIndexString>(FHIRAllTypes.AppointmentResponse);     
      }
    }
    public IResourceRepository AuditEventRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<AuditEventRes, AuditEventResIndex, AuditEventResIndexString>(FHIRAllTypes.AuditEvent);     
      }
    }
    public IResourceRepository BasicRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<BasicRes, BasicResIndex, BasicResIndexString>(FHIRAllTypes.Basic);     
      }
    }
    public IResourceRepository BinaryRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<BinaryRes, BinaryResIndex, BinaryResIndexString>(FHIRAllTypes.Binary);     
      }
    }
    public IResourceRepository BodySiteRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<BodySiteRes, BodySiteResIndex, BodySiteResIndexString>(FHIRAllTypes.BodySite);     
      }
    }
    public IResourceRepository BundleRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<BundleRes, BundleResIndex, BundleResIndexString>(FHIRAllTypes.Bundle);     
      }
    }
    public IResourceRepository CapabilityStatementRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<CapabilityStatementRes, CapabilityStatementResIndex, CapabilityStatementResIndexString>(FHIRAllTypes.CapabilityStatement);     
      }
    }
    public IResourceRepository CarePlanRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<CarePlanRes, CarePlanResIndex, CarePlanResIndexString>(FHIRAllTypes.CarePlan);     
      }
    }
    public IResourceRepository CareTeamRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<CareTeamRes, CareTeamResIndex, CareTeamResIndexString>(FHIRAllTypes.CareTeam);     
      }
    }
    public IResourceRepository ChargeItemRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ChargeItemRes, ChargeItemResIndex, ChargeItemResIndexString>(FHIRAllTypes.ChargeItem);     
      }
    }
    public IResourceRepository ClaimRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ClaimRes, ClaimResIndex, ClaimResIndexString>(FHIRAllTypes.Claim);     
      }
    }
    public IResourceRepository ClaimResponseRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ClaimResponseRes, ClaimResponseResIndex, ClaimResponseResIndexString>(FHIRAllTypes.ClaimResponse);     
      }
    }
    public IResourceRepository ClinicalImpressionRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ClinicalImpressionRes, ClinicalImpressionResIndex, ClinicalImpressionResIndexString>(FHIRAllTypes.ClinicalImpression);     
      }
    }
    public IResourceRepository CodeSystemRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<CodeSystemRes, CodeSystemResIndex, CodeSystemResIndexString>(FHIRAllTypes.CodeSystem);     
      }
    }
    public IResourceRepository CommunicationRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<CommunicationRes, CommunicationResIndex, CommunicationResIndexString>(FHIRAllTypes.Communication);     
      }
    }
    public IResourceRepository CommunicationRequestRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<CommunicationRequestRes, CommunicationRequestResIndex, CommunicationRequestResIndexString>(FHIRAllTypes.CommunicationRequest);     
      }
    }
    public IResourceRepository CompartmentDefinitionRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<CompartmentDefinitionRes, CompartmentDefinitionResIndex, CompartmentDefinitionResIndexString>(FHIRAllTypes.CompartmentDefinition);     
      }
    }
    public IResourceRepository CompositionRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<CompositionRes, CompositionResIndex, CompositionResIndexString>(FHIRAllTypes.Composition);     
      }
    }
    public IResourceRepository ConceptMapRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ConceptMapRes, ConceptMapResIndex, ConceptMapResIndexString>(FHIRAllTypes.ConceptMap);     
      }
    }
    public IResourceRepository ConditionRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ConditionRes, ConditionResIndex, ConditionResIndexString>(FHIRAllTypes.Condition);     
      }
    }
    public IResourceRepository ConsentRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ConsentRes, ConsentResIndex, ConsentResIndexString>(FHIRAllTypes.Consent);     
      }
    }
    public IResourceRepository ContractRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ContractRes, ContractResIndex, ContractResIndexString>(FHIRAllTypes.Contract);     
      }
    }
    public IResourceRepository CoverageRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<CoverageRes, CoverageResIndex, CoverageResIndexString>(FHIRAllTypes.Coverage);     
      }
    }
    public IResourceRepository DataElementRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<DataElementRes, DataElementResIndex, DataElementResIndexString>(FHIRAllTypes.DataElement);     
      }
    }
    public IResourceRepository DetectedIssueRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<DetectedIssueRes, DetectedIssueResIndex, DetectedIssueResIndexString>(FHIRAllTypes.DetectedIssue);     
      }
    }
    public IResourceRepository DeviceRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<DeviceRes, DeviceResIndex, DeviceResIndexString>(FHIRAllTypes.Device);     
      }
    }
    public IResourceRepository DeviceComponentRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<DeviceComponentRes, DeviceComponentResIndex, DeviceComponentResIndexString>(FHIRAllTypes.DeviceComponent);     
      }
    }
    public IResourceRepository DeviceMetricRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<DeviceMetricRes, DeviceMetricResIndex, DeviceMetricResIndexString>(FHIRAllTypes.DeviceMetric);     
      }
    }
    public IResourceRepository DeviceRequestRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<DeviceRequestRes, DeviceRequestResIndex, DeviceRequestResIndexString>(FHIRAllTypes.DeviceRequest);     
      }
    }
    public IResourceRepository DeviceUseStatementRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<DeviceUseStatementRes, DeviceUseStatementResIndex, DeviceUseStatementResIndexString>(FHIRAllTypes.DeviceUseStatement);     
      }
    }
    public IResourceRepository DiagnosticReportRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<DiagnosticReportRes, DiagnosticReportResIndex, DiagnosticReportResIndexString>(FHIRAllTypes.DiagnosticReport);     
      }
    }
    public IResourceRepository DocumentManifestRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<DocumentManifestRes, DocumentManifestResIndex, DocumentManifestResIndexString>(FHIRAllTypes.DocumentManifest);     
      }
    }
    public IResourceRepository DocumentReferenceRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<DocumentReferenceRes, DocumentReferenceResIndex, DocumentReferenceResIndexString>(FHIRAllTypes.DocumentReference);     
      }
    }
    public IResourceRepository EligibilityRequestRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<EligibilityRequestRes, EligibilityRequestResIndex, EligibilityRequestResIndexString>(FHIRAllTypes.EligibilityRequest);     
      }
    }
    public IResourceRepository EligibilityResponseRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<EligibilityResponseRes, EligibilityResponseResIndex, EligibilityResponseResIndexString>(FHIRAllTypes.EligibilityResponse);     
      }
    }
    public IResourceRepository EncounterRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<EncounterRes, EncounterResIndex, EncounterResIndexString>(FHIRAllTypes.Encounter);     
      }
    }
    public IResourceRepository EndpointRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<EndpointRes, EndpointResIndex, EndpointResIndexString>(FHIRAllTypes.Endpoint);     
      }
    }
    public IResourceRepository EnrollmentRequestRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<EnrollmentRequestRes, EnrollmentRequestResIndex, EnrollmentRequestResIndexString>(FHIRAllTypes.EnrollmentRequest);     
      }
    }
    public IResourceRepository EnrollmentResponseRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<EnrollmentResponseRes, EnrollmentResponseResIndex, EnrollmentResponseResIndexString>(FHIRAllTypes.EnrollmentResponse);     
      }
    }
    public IResourceRepository EpisodeOfCareRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<EpisodeOfCareRes, EpisodeOfCareResIndex, EpisodeOfCareResIndexString>(FHIRAllTypes.EpisodeOfCare);     
      }
    }
    public IResourceRepository ExpansionProfileRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ExpansionProfileRes, ExpansionProfileResIndex, ExpansionProfileResIndexString>(FHIRAllTypes.ExpansionProfile);     
      }
    }
    public IResourceRepository ExplanationOfBenefitRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ExplanationOfBenefitRes, ExplanationOfBenefitResIndex, ExplanationOfBenefitResIndexString>(FHIRAllTypes.ExplanationOfBenefit);     
      }
    }
    public IResourceRepository FamilyMemberHistoryRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<FamilyMemberHistoryRes, FamilyMemberHistoryResIndex, FamilyMemberHistoryResIndexString>(FHIRAllTypes.FamilyMemberHistory);     
      }
    }
    public IResourceRepository FlagRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<FlagRes, FlagResIndex, FlagResIndexString>(FHIRAllTypes.Flag);     
      }
    }
    public IResourceRepository GoalRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<GoalRes, GoalResIndex, GoalResIndexString>(FHIRAllTypes.Goal);     
      }
    }
    public IResourceRepository GraphDefinitionRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<GraphDefinitionRes, GraphDefinitionResIndex, GraphDefinitionResIndexString>(FHIRAllTypes.GraphDefinition);     
      }
    }
    public IResourceRepository GroupRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<GroupRes, GroupResIndex, GroupResIndexString>(FHIRAllTypes.Group);     
      }
    }
    public IResourceRepository GuidanceResponseRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<GuidanceResponseRes, GuidanceResponseResIndex, GuidanceResponseResIndexString>(FHIRAllTypes.GuidanceResponse);     
      }
    }
    public IResourceRepository HealthcareServiceRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<HealthcareServiceRes, HealthcareServiceResIndex, HealthcareServiceResIndexString>(FHIRAllTypes.HealthcareService);     
      }
    }
    public IResourceRepository ImagingManifestRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ImagingManifestRes, ImagingManifestResIndex, ImagingManifestResIndexString>(FHIRAllTypes.ImagingManifest);     
      }
    }
    public IResourceRepository ImagingStudyRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ImagingStudyRes, ImagingStudyResIndex, ImagingStudyResIndexString>(FHIRAllTypes.ImagingStudy);     
      }
    }
    public IResourceRepository ImmunizationRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ImmunizationRes, ImmunizationResIndex, ImmunizationResIndexString>(FHIRAllTypes.Immunization);     
      }
    }
    public IResourceRepository ImmunizationRecommendationRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ImmunizationRecommendationRes, ImmunizationRecommendationResIndex, ImmunizationRecommendationResIndexString>(FHIRAllTypes.ImmunizationRecommendation);     
      }
    }
    public IResourceRepository ImplementationGuideRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ImplementationGuideRes, ImplementationGuideResIndex, ImplementationGuideResIndexString>(FHIRAllTypes.ImplementationGuide);     
      }
    }
    public IResourceRepository LibraryRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<LibraryRes, LibraryResIndex, LibraryResIndexString>(FHIRAllTypes.Library);     
      }
    }
    public IResourceRepository LinkageRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<LinkageRes, LinkageResIndex, LinkageResIndexString>(FHIRAllTypes.Linkage);     
      }
    }
    public IResourceRepository ListRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ListRes, ListResIndex, ListResIndexString>(FHIRAllTypes.List);     
      }
    }
    public IResourceRepository LocationRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<LocationRes, LocationResIndex, LocationResIndexString>(FHIRAllTypes.Location);     
      }
    }
    public IResourceRepository MeasureRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<MeasureRes, MeasureResIndex, MeasureResIndexString>(FHIRAllTypes.Measure);     
      }
    }
    public IResourceRepository MeasureReportRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<MeasureReportRes, MeasureReportResIndex, MeasureReportResIndexString>(FHIRAllTypes.MeasureReport);     
      }
    }
    public IResourceRepository MediaRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<MediaRes, MediaResIndex, MediaResIndexString>(FHIRAllTypes.Media);     
      }
    }
    public IResourceRepository MedicationRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<MedicationRes, MedicationResIndex, MedicationResIndexString>(FHIRAllTypes.Medication);     
      }
    }
    public IResourceRepository MedicationAdministrationRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<MedicationAdministrationRes, MedicationAdministrationResIndex, MedicationAdministrationResIndexString>(FHIRAllTypes.MedicationAdministration);     
      }
    }
    public IResourceRepository MedicationDispenseRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<MedicationDispenseRes, MedicationDispenseResIndex, MedicationDispenseResIndexString>(FHIRAllTypes.MedicationDispense);     
      }
    }
    public IResourceRepository MedicationRequestRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<MedicationRequestRes, MedicationRequestResIndex, MedicationRequestResIndexString>(FHIRAllTypes.MedicationRequest);     
      }
    }
    public IResourceRepository MedicationStatementRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<MedicationStatementRes, MedicationStatementResIndex, MedicationStatementResIndexString>(FHIRAllTypes.MedicationStatement);     
      }
    }
    public IResourceRepository MessageDefinitionRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<MessageDefinitionRes, MessageDefinitionResIndex, MessageDefinitionResIndexString>(FHIRAllTypes.MessageDefinition);     
      }
    }
    public IResourceRepository MessageHeaderRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<MessageHeaderRes, MessageHeaderResIndex, MessageHeaderResIndexString>(FHIRAllTypes.MessageHeader);     
      }
    }
    public IResourceRepository NamingSystemRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<NamingSystemRes, NamingSystemResIndex, NamingSystemResIndexString>(FHIRAllTypes.NamingSystem);     
      }
    }
    public IResourceRepository NutritionOrderRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<NutritionOrderRes, NutritionOrderResIndex, NutritionOrderResIndexString>(FHIRAllTypes.NutritionOrder);     
      }
    }
    public IResourceRepository ObservationRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ObservationRes, ObservationResIndex, ObservationResIndexString>(FHIRAllTypes.Observation);     
      }
    }
    public IResourceRepository OperationDefinitionRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<OperationDefinitionRes, OperationDefinitionResIndex, OperationDefinitionResIndexString>(FHIRAllTypes.OperationDefinition);     
      }
    }
    public IResourceRepository OperationOutcomeRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<OperationOutcomeRes, OperationOutcomeResIndex, OperationOutcomeResIndexString>(FHIRAllTypes.OperationOutcome);     
      }
    }
    public IResourceRepository OrganizationRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<OrganizationRes, OrganizationResIndex, OrganizationResIndexString>(FHIRAllTypes.Organization);     
      }
    }
    public IResourceRepository ParametersRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ParametersRes, ParametersResIndex, ParametersResIndexString>(FHIRAllTypes.Parameters);     
      }
    }
    public IResourceRepository PatientRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<PatientRes, PatientResIndex, PatientResIndexString>(FHIRAllTypes.Patient);     
      }
    }
    public IResourceRepository PaymentNoticeRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<PaymentNoticeRes, PaymentNoticeResIndex, PaymentNoticeResIndexString>(FHIRAllTypes.PaymentNotice);     
      }
    }
    public IResourceRepository PaymentReconciliationRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<PaymentReconciliationRes, PaymentReconciliationResIndex, PaymentReconciliationResIndexString>(FHIRAllTypes.PaymentReconciliation);     
      }
    }
    public IResourceRepository PersonRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<PersonRes, PersonResIndex, PersonResIndexString>(FHIRAllTypes.Person);     
      }
    }
    public IResourceRepository PlanDefinitionRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<PlanDefinitionRes, PlanDefinitionResIndex, PlanDefinitionResIndexString>(FHIRAllTypes.PlanDefinition);     
      }
    }
    public IResourceRepository PractitionerRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<PractitionerRes, PractitionerResIndex, PractitionerResIndexString>(FHIRAllTypes.Practitioner);     
      }
    }
    public IResourceRepository PractitionerRoleRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<PractitionerRoleRes, PractitionerRoleResIndex, PractitionerRoleResIndexString>(FHIRAllTypes.PractitionerRole);     
      }
    }
    public IResourceRepository ProcedureRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ProcedureRes, ProcedureResIndex, ProcedureResIndexString>(FHIRAllTypes.Procedure);     
      }
    }
    public IResourceRepository ProcedureRequestRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ProcedureRequestRes, ProcedureRequestResIndex, ProcedureRequestResIndexString>(FHIRAllTypes.ProcedureRequest);     
      }
    }
    public IResourceRepository ProcessRequestRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ProcessRequestRes, ProcessRequestResIndex, ProcessRequestResIndexString>(FHIRAllTypes.ProcessRequest);     
      }
    }
    public IResourceRepository ProcessResponseRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ProcessResponseRes, ProcessResponseResIndex, ProcessResponseResIndexString>(FHIRAllTypes.ProcessResponse);     
      }
    }
    public IResourceRepository ProvenanceRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ProvenanceRes, ProvenanceResIndex, ProvenanceResIndexString>(FHIRAllTypes.Provenance);     
      }
    }
    public IResourceRepository QuestionnaireRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<QuestionnaireRes, QuestionnaireResIndex, QuestionnaireResIndexString>(FHIRAllTypes.Questionnaire);     
      }
    }
    public IResourceRepository QuestionnaireResponseRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<QuestionnaireResponseRes, QuestionnaireResponseResIndex, QuestionnaireResponseResIndexString>(FHIRAllTypes.QuestionnaireResponse);     
      }
    }
    public IResourceRepository ReferralRequestRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ReferralRequestRes, ReferralRequestResIndex, ReferralRequestResIndexString>(FHIRAllTypes.ReferralRequest);     
      }
    }
    public IResourceRepository RelatedPersonRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<RelatedPersonRes, RelatedPersonResIndex, RelatedPersonResIndexString>(FHIRAllTypes.RelatedPerson);     
      }
    }
    public IResourceRepository RequestGroupRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<RequestGroupRes, RequestGroupResIndex, RequestGroupResIndexString>(FHIRAllTypes.RequestGroup);     
      }
    }
    public IResourceRepository ResearchStudyRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ResearchStudyRes, ResearchStudyResIndex, ResearchStudyResIndexString>(FHIRAllTypes.ResearchStudy);     
      }
    }
    public IResourceRepository ResearchSubjectRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ResearchSubjectRes, ResearchSubjectResIndex, ResearchSubjectResIndexString>(FHIRAllTypes.ResearchSubject);     
      }
    }
    public IResourceRepository RiskAssessmentRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<RiskAssessmentRes, RiskAssessmentResIndex, RiskAssessmentResIndexString>(FHIRAllTypes.RiskAssessment);     
      }
    }
    public IResourceRepository ScheduleRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ScheduleRes, ScheduleResIndex, ScheduleResIndexString>(FHIRAllTypes.Schedule);     
      }
    }
    public IResourceRepository SearchParameterRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<SearchParameterRes, SearchParameterResIndex, SearchParameterResIndexString>(FHIRAllTypes.SearchParameter);     
      }
    }
    public IResourceRepository SequenceRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<SequenceRes, SequenceResIndex, SequenceResIndexString>(FHIRAllTypes.Sequence);     
      }
    }
    public IResourceRepository ServiceDefinitionRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ServiceDefinitionRes, ServiceDefinitionResIndex, ServiceDefinitionResIndexString>(FHIRAllTypes.ServiceDefinition);     
      }
    }
    public IResourceRepository SlotRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<SlotRes, SlotResIndex, SlotResIndexString>(FHIRAllTypes.Slot);     
      }
    }
    public IResourceRepository SpecimenRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<SpecimenRes, SpecimenResIndex, SpecimenResIndexString>(FHIRAllTypes.Specimen);     
      }
    }
    public IResourceRepository StructureDefinitionRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<StructureDefinitionRes, StructureDefinitionResIndex, StructureDefinitionResIndexString>(FHIRAllTypes.StructureDefinition);     
      }
    }
    public IResourceRepository StructureMapRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<StructureMapRes, StructureMapResIndex, StructureMapResIndexString>(FHIRAllTypes.StructureMap);     
      }
    }
    public IResourceRepository SubscriptionRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<SubscriptionRes, SubscriptionResIndex, SubscriptionResIndexString>(FHIRAllTypes.Subscription);     
      }
    }
    public IResourceRepository SubstanceRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<SubstanceRes, SubstanceResIndex, SubstanceResIndexString>(FHIRAllTypes.Substance);     
      }
    }
    public IResourceRepository SupplyDeliveryRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<SupplyDeliveryRes, SupplyDeliveryResIndex, SupplyDeliveryResIndexString>(FHIRAllTypes.SupplyDelivery);     
      }
    }
    public IResourceRepository SupplyRequestRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<SupplyRequestRes, SupplyRequestResIndex, SupplyRequestResIndexString>(FHIRAllTypes.SupplyRequest);     
      }
    }
    public IResourceRepository TaskRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<TaskRes, TaskResIndex, TaskResIndexString>(FHIRAllTypes.Task);     
      }
    }
    public IResourceRepository TestReportRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<TestReportRes, TestReportResIndex, TestReportResIndexString>(FHIRAllTypes.TestReport);     
      }
    }
    public IResourceRepository TestScriptRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<TestScriptRes, TestScriptResIndex, TestScriptResIndexString>(FHIRAllTypes.TestScript);     
      }
    }
    public IResourceRepository ValueSetRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<ValueSetRes, ValueSetResIndex, ValueSetResIndexString>(FHIRAllTypes.ValueSet);     
      }
    }
    public IResourceRepository VisionPrescriptionRepository
    {
      get
      {      
        return IResourceRepositoryFactory.Create<VisionPrescriptionRes, VisionPrescriptionResIndex, VisionPrescriptionResIndexString>(FHIRAllTypes.VisionPrescription);     
      }
    }
	
  }
}
