
 
// Generated helper templates
// Generated items
// Blaze\Blaze.DataModel\BlazeDbModel\Res_VisionPrescription_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_VisionPrescription.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ValueSet_Index_reference.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ValueSet_Index_context.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ValueSet_Index_code.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ValueSet.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_TestScript_Index_testscript_test_capability.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_TestScript_Index_testscript_setup_capability.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_TestScript_Index_testscript_capability.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_TestScript.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_SupplyRequest_Index_supplier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_SupplyRequest_Index_kind.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_SupplyRequest.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_SupplyDelivery_Index_receiver.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_SupplyDelivery.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Substance_Index_substance.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Substance_Index_quantity.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Substance_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Substance_Index_expiry.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Substance_Index_container_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Substance_Index_code.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Substance_Index_category.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Substance.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Subscription_Index_tag.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Subscription_Index_contact.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Subscription.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_StructureDefinition_Index_valueset.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_StructureDefinition_Index_path.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_StructureDefinition_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_StructureDefinition_Index_ext_context.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_StructureDefinition_Index_context.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_StructureDefinition_Index_code.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_StructureDefinition_Index_base_path.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_StructureDefinition.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Specimen_Index_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Specimen_Index_parent.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Specimen_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Specimen_Index_container_id.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Specimen_Index_container.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Specimen_Index_bodysite.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Specimen.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Slot_Index_slot_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Slot_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Slot.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_SearchParameter_Index_target.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_SearchParameter.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Schedule_Index_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Schedule_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Schedule.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_RiskAssessment_Index_method.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_RiskAssessment.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_RelatedPerson_Index_telecom.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_RelatedPerson_Index_phonetic.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_RelatedPerson_Index_phone.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_RelatedPerson_Index_name.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_RelatedPerson_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_RelatedPerson_Index_email.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_RelatedPerson_Index_address_use.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_RelatedPerson_Index_address_state.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_RelatedPerson_Index_address_postalcode.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_RelatedPerson_Index_address_country.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_RelatedPerson_Index_address_city.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_RelatedPerson_Index_address.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_RelatedPerson.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ReferralRequest_Index_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ReferralRequest_Index_specialty.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ReferralRequest_Index_recipient.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ReferralRequest_Index_priority.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ReferralRequest.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_QuestionnaireResponse.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Questionnaire_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Questionnaire_Index_code.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Questionnaire.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Provenance_Index_userid.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Provenance_Index_target.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Provenance_Index_sigtype.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Provenance_Index_patient.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Provenance_Index_entitytype.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Provenance_Index_entity.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Provenance_Index_agent.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Provenance.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ProcessResponse_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ProcessResponse.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ProcessRequest_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ProcessRequest.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ProcedureRequest_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ProcedureRequest.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Procedure_Index_performer.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Procedure_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Procedure_Index_code.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Procedure.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner_Index_telecom.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner_Index_specialty.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner_Index_role.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner_Index_phonetic.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner_Index_phone.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner_Index_organization.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner_Index_name.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner_Index_location.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner_Index_given.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner_Index_family.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner_Index_email.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner_Index_communication.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner_Index_address_use.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner_Index_address_state.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner_Index_address_postalcode.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner_Index_address_country.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner_Index_address_city.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner_Index_address.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Practitioner.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Person_Index_telecom.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Person_Index_relatedperson.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Person_Index_practitioner.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Person_Index_phonetic.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Person_Index_phone.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Person_Index_patient.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Person_Index_name.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Person_Index_link.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Person_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Person_Index_email.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Person_Index_address_use.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Person_Index_address_state.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Person_Index_address_postalcode.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Person_Index_address_country.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Person_Index_address_city.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Person_Index_address.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Person.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_PaymentReconciliation_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_PaymentReconciliation.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_PaymentNotice_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_PaymentNotice.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_ethnicity.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_race.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_telecom.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_phonetic.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_phone.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_name.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_link.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_language.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_given.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_family.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_email.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_careprovider.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_animal_species.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_animal_breed.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_address_use.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_address_state.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_address_postalcode.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_address_country.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_address_city.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient_Index_address.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Patient.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Parameters.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Organization_Index_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Organization_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Organization_Index_address_use.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Organization_Index_address_state.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Organization_Index_address_postalcode.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Organization_Index_address_country.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Organization_Index_address_city.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Organization_Index_address.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Organization.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_OrderResponse_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_OrderResponse_Index_fulfillment.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_OrderResponse.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Order_Index_when_code.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Order_Index_when.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Order_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Order_Index_detail.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Order.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_OperationOutcome.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_OperationDefinition_Index_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_OperationDefinition_Index_profile.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_OperationDefinition.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Observation_Index_related_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Observation_Index_related_target.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Observation_Index_performer.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Observation_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Observation_Index_data_absent_reason.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Observation_Index_component_value_string.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Observation_Index_component_value_quantity.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Observation_Index_component_value_concept.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Observation_Index_component_data_absent_reason.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Observation_Index_component_code.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Observation_Index_code.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Observation_Index_category.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Observation.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_NutritionOrder_Index_supplement.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_NutritionOrder_Index_oraldiet.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_NutritionOrder_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_NutritionOrder_Index_formula.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_NutritionOrder_Index_additive.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_NutritionOrder.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_NamingSystem_Index_value.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_NamingSystem_Index_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_NamingSystem_Index_telecom.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_NamingSystem_Index_period.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_NamingSystem_Index_id_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_NamingSystem_Index_context.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_NamingSystem_Index_contact.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_NamingSystem.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_MessageHeader_Index_target.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_MessageHeader_Index_destination_uri.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_MessageHeader_Index_destination.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_MessageHeader_Index_data.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_MessageHeader.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_MedicationStatement_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_MedicationStatement.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_MedicationOrder_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_MedicationOrder.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_MedicationDispense_Index_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_MedicationDispense_Index_responsibleparty.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_MedicationDispense_Index_receiver.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_MedicationDispense_Index_prescription.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_MedicationDispense.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_MedicationAdministration_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_MedicationAdministration_Index_device.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_MedicationAdministration.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Medication_Index_ingredient.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Medication_Index_form.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Medication_Index_content.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Medication_Index_container.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Medication_Index_code.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Medication.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Media_Index_view.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Media_Index_subtype.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Media_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Media.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Location_Index_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Location_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Location_Index_address.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Location.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_List_Index_item.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_List_Index_empty_reason.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_List_Index_code.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_List.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImplementationGuide_Index_dependency.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImplementationGuide_Index_context.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImplementationGuide.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImmunizationRecommendation_Index_vaccine_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImmunizationRecommendation_Index_support.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImmunizationRecommendation_Index_status.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImmunizationRecommendation_Index_information.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImmunizationRecommendation_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImmunizationRecommendation_Index_dose_sequence.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImmunizationRecommendation_Index_dose_number.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImmunizationRecommendation_Index_date.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImmunizationRecommendation.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Immunization_Index_vaccine_code.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Immunization_Index_reason_not_given.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Immunization_Index_reason.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Immunization_Index_reaction_date.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Immunization_Index_reaction.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Immunization_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Immunization_Index_dose_sequence.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Immunization.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImagingStudy_Index_uid.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImagingStudy_Index_series.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImagingStudy_Index_order.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImagingStudy_Index_modality.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImagingStudy_Index_dicom_class.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImagingStudy_Index_bodysite.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImagingStudy.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImagingObjectSelection_Index_title.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImagingObjectSelection_Index_selected_study.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ImagingObjectSelection.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_HealthcareService_Index_servicetype.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_HealthcareService_Index_servicecategory.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_HealthcareService_Index_programname.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_HealthcareService_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_HealthcareService_Index_characteristic.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_HealthcareService.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Group_Index_value.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Group_Index_member.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Group_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Group_Index_exclude.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Group_Index_code.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Group_Index_characteristic.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Group.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Goal_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Goal_Index_category.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Goal.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Flag.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_FamilyMemberHistory_Index_relationship.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_FamilyMemberHistory_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_FamilyMemberHistory_Index_code.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_FamilyMemberHistory.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ExplanationOfBenefit_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ExplanationOfBenefit.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_EpisodeOfCare_Index_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_EpisodeOfCare_Index_team_member.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_EpisodeOfCare_Index_incomingreferral.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_EpisodeOfCare_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_EpisodeOfCare_Index_condition.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_EpisodeOfCare.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_EnrollmentResponse_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_EnrollmentResponse.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_EnrollmentRequest_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_EnrollmentRequest.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Encounter_Index_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Encounter_Index_special_arrangement.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Encounter_Index_reason.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Encounter_Index_procedure.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Encounter_Index_practitioner.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Encounter_Index_participant_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Encounter_Index_participant.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Encounter_Index_location_period.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Encounter_Index_location.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Encounter_Index_indication.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Encounter_Index_incomingreferral.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Encounter_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Encounter_Index_episodeofcare.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Encounter_Index_condition.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Encounter.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_EligibilityResponse_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_EligibilityResponse.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_EligibilityRequest_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_EligibilityRequest.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentReference_Index_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentReference_Index_setting.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentReference_Index_securitylabel.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentReference_Index_relation.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentReference_Index_relatesto.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentReference_Index_related_ref.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentReference_Index_related_id.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentReference_Index_location.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentReference_Index_language.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentReference_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentReference_Index_format.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentReference_Index_facility.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentReference_Index_event.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentReference_Index_class.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentReference_Index_author.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentReference.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentManifest_Index_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentManifest_Index_related_ref.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentManifest_Index_related_id.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentManifest_Index_recipient.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentManifest_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentManifest_Index_content_ref.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentManifest_Index_author.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DocumentManifest.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticReport_Index_specimen.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticReport_Index_result.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticReport_Index_request.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticReport_Index_image.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticReport_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticReport_Index_diagnosis.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticReport_Index_code.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticReport_Index_category.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticReport.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticOrder_Index_specimen.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticOrder_Index_item_status.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticOrder_Index_item_past_status.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticOrder_Index_item_date.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticOrder_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticOrder_Index_event_status.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticOrder_Index_event_date.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticOrder_Index_code.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticOrder_Index_bodysite.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticOrder_Index_actor.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DiagnosticOrder.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DeviceUseStatement.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DeviceUseRequest.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DeviceMetric_Index_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DeviceMetric.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DeviceComponent_Index_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DeviceComponent.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Device_Index_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Device_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Device.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DetectedIssue_Index_implicated.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DetectedIssue_Index_category.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DetectedIssue.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DataElement_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DataElement_Index_description.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DataElement_Index_context.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DataElement_Index_code.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_DataElement.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Coverage_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Coverage.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Contract_Index_subject.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Contract_Index_signer.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Contract_Index_patient.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Contract_Index_actor.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Contract.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Conformance_Index_supported_profile.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Conformance_Index_security.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Conformance_Index_resource.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Conformance_Index_profile.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Conformance_Index_mode.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Conformance_Index_format.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Conformance_Index_event.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Conformance.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Condition_Index_stage.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Condition_Index_severity.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Condition_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Condition_Index_evidence.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Condition_Index_code.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Condition_Index_category.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Condition_Index_body_site.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Condition.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ConceptMap_Index_targetsystem.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ConceptMap_Index_targetcode.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ConceptMap_Index_sourcesystem.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ConceptMap_Index_sourcecode.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ConceptMap_Index_product.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ConceptMap_Index_dependson.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ConceptMap_Index_context.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ConceptMap.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Composition_Index_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Composition_Index_section.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Composition_Index_period.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Composition_Index_entry.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Composition_Index_context.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Composition_Index_class.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Composition_Index_author.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Composition_Index_attester.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Composition.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_CommunicationRequest_Index_recipient.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_CommunicationRequest_Index_priority.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_CommunicationRequest_Index_medium.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_CommunicationRequest_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_CommunicationRequest_Index_category.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_CommunicationRequest.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Communication_Index_recipient.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Communication_Index_medium.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Communication_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Communication_Index_category.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Communication.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ClinicalImpression_Index_ruledout.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ClinicalImpression_Index_resolved.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ClinicalImpression_Index_problem.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ClinicalImpression_Index_plan.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ClinicalImpression_Index_investigation.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ClinicalImpression_Index_finding.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ClinicalImpression_Index_action.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ClinicalImpression.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ClaimResponse_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_ClaimResponse.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Claim_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Claim.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_CarePlan_Index_relatedplan.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_CarePlan_Index_relatedcode.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_CarePlan_Index_performer.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_CarePlan_Index_participant.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_CarePlan_Index_goal.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_CarePlan_Index_condition.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_CarePlan_Index_activityreference.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_CarePlan_Index_activitydate.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_CarePlan_Index_activitycode.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_CarePlan.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Bundle.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_BodySite_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_BodySite_Index_code.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_BodySite.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Binary.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Basic_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Basic_Index_code.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Basic.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AuditEvent_Index_user.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AuditEvent_Index_subtype.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AuditEvent_Index_reference.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AuditEvent_Index_policy.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AuditEvent_Index_patient.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AuditEvent_Index_participant.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AuditEvent_Index_object_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AuditEvent_Index_name.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AuditEvent_Index_identity.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AuditEvent_Index_desc.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AuditEvent_Index_altid.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AuditEvent_Index_address.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AuditEvent.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AppointmentResponse_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AppointmentResponse.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Appointment_Index_practitioner.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Appointment_Index_patient.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Appointment_Index_part_status.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Appointment_Index_location.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Appointment_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Appointment_Index_actor.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Appointment.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AllergyIntolerance_Index_substance.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AllergyIntolerance_Index_severity.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AllergyIntolerance_Index_route.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AllergyIntolerance_Index_onset.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AllergyIntolerance_Index_manifestation.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AllergyIntolerance_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_AllergyIntolerance.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Account_Index_type.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Account_Index_identifier.cs
// Blaze\Blaze.DataModel\BlazeDbModel\Res_Account.cs

