namespace Pyro.DataLayer.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class OldStringIndexDrop : DbMigration
    {
        public override void Up()
        {
            DropIndex("dbo.AccountResIndex", "ix_String");
            DropIndex("dbo.ActivityDefinitionResIndex", "ix_String");
            DropIndex("dbo.AdverseEventResIndex", "ix_String");
            DropIndex("dbo.AllergyIntoleranceResIndex", "ix_String");
            DropIndex("dbo.AppointmentResIndex", "ix_String");
            DropIndex("dbo.AppointmentResponseResIndex", "ix_String");
            DropIndex("dbo.AuditEventResIndex", "ix_String");
            DropIndex("dbo.BasicResIndex", "ix_String");
            DropIndex("dbo.BinaryResIndex", "ix_String");
            DropIndex("dbo.BodySiteResIndex", "ix_String");
            DropIndex("dbo.BundleResIndex", "ix_String");
            DropIndex("dbo.CapabilityStatementResIndex", "ix_String");
            DropIndex("dbo.CarePlanResIndex", "ix_String");
            DropIndex("dbo.CareTeamResIndex", "ix_String");
            DropIndex("dbo.ChargeItemResIndex", "ix_String");
            DropIndex("dbo.ClaimResIndex", "ix_String");
            DropIndex("dbo.ClaimResponseResIndex", "ix_String");
            DropIndex("dbo.ClinicalImpressionResIndex", "ix_String");
            DropIndex("dbo.CodeSystemResIndex", "ix_String");
            DropIndex("dbo.CommunicationResIndex", "ix_String");
            DropIndex("dbo.CommunicationRequestResIndex", "ix_String");
            DropIndex("dbo.CompartmentDefinitionResIndex", "ix_String");
            DropIndex("dbo.CompositionResIndex", "ix_String");
            DropIndex("dbo.ConceptMapResIndex", "ix_String");
            DropIndex("dbo.ConditionResIndex", "ix_String");
            DropIndex("dbo.ConsentResIndex", "ix_String");
            DropIndex("dbo.ContractResIndex", "ix_String");
            DropIndex("dbo.CoverageResIndex", "ix_String");
            DropIndex("dbo.DataElementResIndex", "ix_String");
            DropIndex("dbo.DetectedIssueResIndex", "ix_String");
            DropIndex("dbo.DeviceResIndex", "ix_String");
            DropIndex("dbo.DeviceComponentResIndex", "ix_String");
            DropIndex("dbo.DeviceMetricResIndex", "ix_String");
            DropIndex("dbo.DeviceRequestResIndex", "ix_String");
            DropIndex("dbo.DeviceUseStatementResIndex", "ix_String");
            DropIndex("dbo.DiagnosticReportResIndex", "ix_String");
            DropIndex("dbo.DocumentManifestResIndex", "ix_String");
            DropIndex("dbo.DocumentReferenceResIndex", "ix_String");
            DropIndex("dbo.EligibilityRequestResIndex", "ix_String");
            DropIndex("dbo.EligibilityResponseResIndex", "ix_String");
            DropIndex("dbo.EncounterResIndex", "ix_String");
            DropIndex("dbo.EndpointResIndex", "ix_String");
            DropIndex("dbo.EnrollmentRequestResIndex", "ix_String");
            DropIndex("dbo.EnrollmentResponseResIndex", "ix_String");
            DropIndex("dbo.EpisodeOfCareResIndex", "ix_String");
            DropIndex("dbo.ExpansionProfileResIndex", "ix_String");
            DropIndex("dbo.ExplanationOfBenefitResIndex", "ix_String");
            DropIndex("dbo.FamilyMemberHistoryResIndex", "ix_String");
            DropIndex("dbo.FlagResIndex", "ix_String");
            DropIndex("dbo.GoalResIndex", "ix_String");
            DropIndex("dbo.GraphDefinitionResIndex", "ix_String");
            DropIndex("dbo.GroupResIndex", "ix_String");
            DropIndex("dbo.GuidanceResponseResIndex", "ix_String");
            DropIndex("dbo.HealthcareServiceResIndex", "ix_String");
            DropIndex("dbo.ImagingManifestResIndex", "ix_String");
            DropIndex("dbo.ImagingStudyResIndex", "ix_String");
            DropIndex("dbo.ImmunizationResIndex", "ix_String");
            DropIndex("dbo.ImmunizationRecommendationResIndex", "ix_String");
            DropIndex("dbo.ImplementationGuideResIndex", "ix_String");
            DropIndex("dbo.LibraryResIndex", "ix_String");
            DropIndex("dbo.LinkageResIndex", "ix_String");
            DropIndex("dbo.ListResIndex", "ix_String");
            DropIndex("dbo.LocationResIndex", "ix_String");
            DropIndex("dbo.MeasureResIndex", "ix_String");
            DropIndex("dbo.MeasureReportResIndex", "ix_String");
            DropIndex("dbo.MediaResIndex", "ix_String");
            DropIndex("dbo.MedicationResIndex", "ix_String");
            DropIndex("dbo.MedicationAdministrationResIndex", "ix_String");
            DropIndex("dbo.MedicationDispenseResIndex", "ix_String");
            DropIndex("dbo.MedicationRequestResIndex", "ix_String");
            DropIndex("dbo.MedicationStatementResIndex", "ix_String");
            DropIndex("dbo.MessageDefinitionResIndex", "ix_String");
            DropIndex("dbo.MessageHeaderResIndex", "ix_String");
            DropIndex("dbo.NamingSystemResIndex", "ix_String");
            DropIndex("dbo.NutritionOrderResIndex", "ix_String");
            DropIndex("dbo.ObservationResIndex", "ix_String");
            DropIndex("dbo.OperationDefinitionResIndex", "ix_String");
            DropIndex("dbo.OperationOutcomeResIndex", "ix_String");
            DropIndex("dbo.OrganizationResIndex", "ix_String");
            DropIndex("dbo.ParametersResIndex", "ix_String");
            DropIndex("dbo.PatientResIndex", "ix_String");
            DropIndex("dbo.PaymentNoticeResIndex", "ix_String");
            DropIndex("dbo.PaymentReconciliationResIndex", "ix_String");
            DropIndex("dbo.PersonResIndex", "ix_String");
            DropIndex("dbo.PlanDefinitionResIndex", "ix_String");
            DropIndex("dbo.PractitionerResIndex", "ix_String");
            DropIndex("dbo.PractitionerRoleResIndex", "ix_String");
            DropIndex("dbo.ProcedureResIndex", "ix_String");
            DropIndex("dbo.ProcedureRequestResIndex", "ix_String");
            DropIndex("dbo.ProcessRequestResIndex", "ix_String");
            DropIndex("dbo.ProcessResponseResIndex", "ix_String");
            DropIndex("dbo.ProvenanceResIndex", "ix_String");
            DropIndex("dbo.QuestionnaireResIndex", "ix_String");
            DropIndex("dbo.QuestionnaireResponseResIndex", "ix_String");
            DropIndex("dbo.ReferralRequestResIndex", "ix_String");
            DropIndex("dbo.RelatedPersonResIndex", "ix_String");
            DropIndex("dbo.RequestGroupResIndex", "ix_String");
            DropIndex("dbo.ResearchStudyResIndex", "ix_String");
            DropIndex("dbo.ResearchSubjectResIndex", "ix_String");
            DropIndex("dbo.RiskAssessmentResIndex", "ix_String");
            DropIndex("dbo.ScheduleResIndex", "ix_String");
            DropIndex("dbo.SearchParameterResIndex", "ix_String");
            DropIndex("dbo.SequenceResIndex", "ix_String");
            DropIndex("dbo.ServiceDefinitionResIndex", "ix_String");
            DropIndex("dbo.SlotResIndex", "ix_String");
            DropIndex("dbo.SpecimenResIndex", "ix_String");
            DropIndex("dbo.StructureDefinitionResIndex", "ix_String");
            DropIndex("dbo.StructureMapResIndex", "ix_String");
            DropIndex("dbo.SubscriptionResIndex", "ix_String");
            DropIndex("dbo.SubstanceResIndex", "ix_String");
            DropIndex("dbo.SupplyDeliveryResIndex", "ix_String");
            DropIndex("dbo.SupplyRequestResIndex", "ix_String");
            DropIndex("dbo.TaskResIndex", "ix_String");
            DropIndex("dbo.TestReportResIndex", "ix_String");
            DropIndex("dbo.TestScriptResIndex", "ix_String");
            DropIndex("dbo.ValueSetResIndex", "ix_String");
            DropIndex("dbo.VisionPrescriptionResIndex", "ix_String");
            DropColumn("dbo.AccountResIndex", "String");
            DropColumn("dbo.ActivityDefinitionResIndex", "String");
            DropColumn("dbo.AdverseEventResIndex", "String");
            DropColumn("dbo.AllergyIntoleranceResIndex", "String");
            DropColumn("dbo.AppointmentResIndex", "String");
            DropColumn("dbo.AppointmentResponseResIndex", "String");
            DropColumn("dbo.AuditEventResIndex", "String");
            DropColumn("dbo.BasicResIndex", "String");
            DropColumn("dbo.BinaryResIndex", "String");
            DropColumn("dbo.BodySiteResIndex", "String");
            DropColumn("dbo.BundleResIndex", "String");
            DropColumn("dbo.CapabilityStatementResIndex", "String");
            DropColumn("dbo.CarePlanResIndex", "String");
            DropColumn("dbo.CareTeamResIndex", "String");
            DropColumn("dbo.ChargeItemResIndex", "String");
            DropColumn("dbo.ClaimResIndex", "String");
            DropColumn("dbo.ClaimResponseResIndex", "String");
            DropColumn("dbo.ClinicalImpressionResIndex", "String");
            DropColumn("dbo.CodeSystemResIndex", "String");
            DropColumn("dbo.CommunicationResIndex", "String");
            DropColumn("dbo.CommunicationRequestResIndex", "String");
            DropColumn("dbo.CompartmentDefinitionResIndex", "String");
            DropColumn("dbo.CompositionResIndex", "String");
            DropColumn("dbo.ConceptMapResIndex", "String");
            DropColumn("dbo.ConditionResIndex", "String");
            DropColumn("dbo.ConsentResIndex", "String");
            DropColumn("dbo.ContractResIndex", "String");
            DropColumn("dbo.CoverageResIndex", "String");
            DropColumn("dbo.DataElementResIndex", "String");
            DropColumn("dbo.DetectedIssueResIndex", "String");
            DropColumn("dbo.DeviceResIndex", "String");
            DropColumn("dbo.DeviceComponentResIndex", "String");
            DropColumn("dbo.DeviceMetricResIndex", "String");
            DropColumn("dbo.DeviceRequestResIndex", "String");
            DropColumn("dbo.DeviceUseStatementResIndex", "String");
            DropColumn("dbo.DiagnosticReportResIndex", "String");
            DropColumn("dbo.DocumentManifestResIndex", "String");
            DropColumn("dbo.DocumentReferenceResIndex", "String");
            DropColumn("dbo.EligibilityRequestResIndex", "String");
            DropColumn("dbo.EligibilityResponseResIndex", "String");
            DropColumn("dbo.EncounterResIndex", "String");
            DropColumn("dbo.EndpointResIndex", "String");
            DropColumn("dbo.EnrollmentRequestResIndex", "String");
            DropColumn("dbo.EnrollmentResponseResIndex", "String");
            DropColumn("dbo.EpisodeOfCareResIndex", "String");
            DropColumn("dbo.ExpansionProfileResIndex", "String");
            DropColumn("dbo.ExplanationOfBenefitResIndex", "String");
            DropColumn("dbo.FamilyMemberHistoryResIndex", "String");
            DropColumn("dbo.FlagResIndex", "String");
            DropColumn("dbo.GoalResIndex", "String");
            DropColumn("dbo.GraphDefinitionResIndex", "String");
            DropColumn("dbo.GroupResIndex", "String");
            DropColumn("dbo.GuidanceResponseResIndex", "String");
            DropColumn("dbo.HealthcareServiceResIndex", "String");
            DropColumn("dbo.ImagingManifestResIndex", "String");
            DropColumn("dbo.ImagingStudyResIndex", "String");
            DropColumn("dbo.ImmunizationResIndex", "String");
            DropColumn("dbo.ImmunizationRecommendationResIndex", "String");
            DropColumn("dbo.ImplementationGuideResIndex", "String");
            DropColumn("dbo.LibraryResIndex", "String");
            DropColumn("dbo.LinkageResIndex", "String");
            DropColumn("dbo.ListResIndex", "String");
            DropColumn("dbo.LocationResIndex", "String");
            DropColumn("dbo.MeasureResIndex", "String");
            DropColumn("dbo.MeasureReportResIndex", "String");
            DropColumn("dbo.MediaResIndex", "String");
            DropColumn("dbo.MedicationResIndex", "String");
            DropColumn("dbo.MedicationAdministrationResIndex", "String");
            DropColumn("dbo.MedicationDispenseResIndex", "String");
            DropColumn("dbo.MedicationRequestResIndex", "String");
            DropColumn("dbo.MedicationStatementResIndex", "String");
            DropColumn("dbo.MessageDefinitionResIndex", "String");
            DropColumn("dbo.MessageHeaderResIndex", "String");
            DropColumn("dbo.NamingSystemResIndex", "String");
            DropColumn("dbo.NutritionOrderResIndex", "String");
            DropColumn("dbo.ObservationResIndex", "String");
            DropColumn("dbo.OperationDefinitionResIndex", "String");
            DropColumn("dbo.OperationOutcomeResIndex", "String");
            DropColumn("dbo.OrganizationResIndex", "String");
            DropColumn("dbo.ParametersResIndex", "String");
            DropColumn("dbo.PatientResIndex", "String");
            DropColumn("dbo.PaymentNoticeResIndex", "String");
            DropColumn("dbo.PaymentReconciliationResIndex", "String");
            DropColumn("dbo.PersonResIndex", "String");
            DropColumn("dbo.PlanDefinitionResIndex", "String");
            DropColumn("dbo.PractitionerResIndex", "String");
            DropColumn("dbo.PractitionerRoleResIndex", "String");
            DropColumn("dbo.ProcedureResIndex", "String");
            DropColumn("dbo.ProcedureRequestResIndex", "String");
            DropColumn("dbo.ProcessRequestResIndex", "String");
            DropColumn("dbo.ProcessResponseResIndex", "String");
            DropColumn("dbo.ProvenanceResIndex", "String");
            DropColumn("dbo.QuestionnaireResIndex", "String");
            DropColumn("dbo.QuestionnaireResponseResIndex", "String");
            DropColumn("dbo.ReferralRequestResIndex", "String");
            DropColumn("dbo.RelatedPersonResIndex", "String");
            DropColumn("dbo.RequestGroupResIndex", "String");
            DropColumn("dbo.ResearchStudyResIndex", "String");
            DropColumn("dbo.ResearchSubjectResIndex", "String");
            DropColumn("dbo.RiskAssessmentResIndex", "String");
            DropColumn("dbo.ScheduleResIndex", "String");
            DropColumn("dbo.SearchParameterResIndex", "String");
            DropColumn("dbo.SequenceResIndex", "String");
            DropColumn("dbo.ServiceDefinitionResIndex", "String");
            DropColumn("dbo.SlotResIndex", "String");
            DropColumn("dbo.SpecimenResIndex", "String");
            DropColumn("dbo.StructureDefinitionResIndex", "String");
            DropColumn("dbo.StructureMapResIndex", "String");
            DropColumn("dbo.SubscriptionResIndex", "String");
            DropColumn("dbo.SubstanceResIndex", "String");
            DropColumn("dbo.SupplyDeliveryResIndex", "String");
            DropColumn("dbo.SupplyRequestResIndex", "String");
            DropColumn("dbo.TaskResIndex", "String");
            DropColumn("dbo.TestReportResIndex", "String");
            DropColumn("dbo.TestScriptResIndex", "String");
            DropColumn("dbo.ValueSetResIndex", "String");
            DropColumn("dbo.VisionPrescriptionResIndex", "String");
        }
        
        public override void Down()
        {
            AddColumn("dbo.VisionPrescriptionResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ValueSetResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.TestScriptResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.TestReportResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.TaskResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.SupplyRequestResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.SupplyDeliveryResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.SubstanceResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.SubscriptionResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.StructureMapResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.StructureDefinitionResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.SpecimenResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.SlotResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ServiceDefinitionResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.SequenceResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.SearchParameterResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ScheduleResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.RiskAssessmentResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ResearchSubjectResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ResearchStudyResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.RequestGroupResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.RelatedPersonResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ReferralRequestResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.QuestionnaireResponseResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.QuestionnaireResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ProvenanceResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ProcessResponseResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ProcessRequestResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ProcedureRequestResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ProcedureResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.PractitionerRoleResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.PractitionerResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.PlanDefinitionResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.PersonResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.PaymentReconciliationResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.PaymentNoticeResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.PatientResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ParametersResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.OrganizationResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.OperationOutcomeResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.OperationDefinitionResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ObservationResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.NutritionOrderResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.NamingSystemResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.MessageHeaderResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.MessageDefinitionResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.MedicationStatementResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.MedicationRequestResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.MedicationDispenseResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.MedicationAdministrationResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.MedicationResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.MediaResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.MeasureReportResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.MeasureResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.LocationResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ListResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.LinkageResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.LibraryResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ImplementationGuideResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ImmunizationRecommendationResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ImmunizationResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ImagingStudyResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ImagingManifestResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.HealthcareServiceResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.GuidanceResponseResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.GroupResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.GraphDefinitionResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.GoalResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.FlagResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.FamilyMemberHistoryResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ExplanationOfBenefitResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ExpansionProfileResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.EpisodeOfCareResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.EnrollmentResponseResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.EnrollmentRequestResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.EndpointResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.EncounterResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.EligibilityResponseResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.EligibilityRequestResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.DocumentReferenceResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.DocumentManifestResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.DiagnosticReportResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.DeviceUseStatementResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.DeviceRequestResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.DeviceMetricResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.DeviceComponentResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.DeviceResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.DetectedIssueResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.DataElementResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.CoverageResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ContractResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ConsentResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ConditionResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ConceptMapResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.CompositionResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.CompartmentDefinitionResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.CommunicationRequestResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.CommunicationResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.CodeSystemResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ClinicalImpressionResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ClaimResponseResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ClaimResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ChargeItemResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.CareTeamResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.CarePlanResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.CapabilityStatementResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.BundleResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.BodySiteResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.BinaryResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.BasicResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.AuditEventResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.AppointmentResponseResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.AppointmentResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.AllergyIntoleranceResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.AdverseEventResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.ActivityDefinitionResIndex", "String", c => c.String(maxLength: 450));
            AddColumn("dbo.AccountResIndex", "String", c => c.String(maxLength: 450));
            CreateIndex("dbo.VisionPrescriptionResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ValueSetResIndex", "String", name: "ix_String");
            CreateIndex("dbo.TestScriptResIndex", "String", name: "ix_String");
            CreateIndex("dbo.TestReportResIndex", "String", name: "ix_String");
            CreateIndex("dbo.TaskResIndex", "String", name: "ix_String");
            CreateIndex("dbo.SupplyRequestResIndex", "String", name: "ix_String");
            CreateIndex("dbo.SupplyDeliveryResIndex", "String", name: "ix_String");
            CreateIndex("dbo.SubstanceResIndex", "String", name: "ix_String");
            CreateIndex("dbo.SubscriptionResIndex", "String", name: "ix_String");
            CreateIndex("dbo.StructureMapResIndex", "String", name: "ix_String");
            CreateIndex("dbo.StructureDefinitionResIndex", "String", name: "ix_String");
            CreateIndex("dbo.SpecimenResIndex", "String", name: "ix_String");
            CreateIndex("dbo.SlotResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ServiceDefinitionResIndex", "String", name: "ix_String");
            CreateIndex("dbo.SequenceResIndex", "String", name: "ix_String");
            CreateIndex("dbo.SearchParameterResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ScheduleResIndex", "String", name: "ix_String");
            CreateIndex("dbo.RiskAssessmentResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ResearchSubjectResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ResearchStudyResIndex", "String", name: "ix_String");
            CreateIndex("dbo.RequestGroupResIndex", "String", name: "ix_String");
            CreateIndex("dbo.RelatedPersonResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ReferralRequestResIndex", "String", name: "ix_String");
            CreateIndex("dbo.QuestionnaireResponseResIndex", "String", name: "ix_String");
            CreateIndex("dbo.QuestionnaireResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ProvenanceResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ProcessResponseResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ProcessRequestResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ProcedureRequestResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ProcedureResIndex", "String", name: "ix_String");
            CreateIndex("dbo.PractitionerRoleResIndex", "String", name: "ix_String");
            CreateIndex("dbo.PractitionerResIndex", "String", name: "ix_String");
            CreateIndex("dbo.PlanDefinitionResIndex", "String", name: "ix_String");
            CreateIndex("dbo.PersonResIndex", "String", name: "ix_String");
            CreateIndex("dbo.PaymentReconciliationResIndex", "String", name: "ix_String");
            CreateIndex("dbo.PaymentNoticeResIndex", "String", name: "ix_String");
            CreateIndex("dbo.PatientResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ParametersResIndex", "String", name: "ix_String");
            CreateIndex("dbo.OrganizationResIndex", "String", name: "ix_String");
            CreateIndex("dbo.OperationOutcomeResIndex", "String", name: "ix_String");
            CreateIndex("dbo.OperationDefinitionResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ObservationResIndex", "String", name: "ix_String");
            CreateIndex("dbo.NutritionOrderResIndex", "String", name: "ix_String");
            CreateIndex("dbo.NamingSystemResIndex", "String", name: "ix_String");
            CreateIndex("dbo.MessageHeaderResIndex", "String", name: "ix_String");
            CreateIndex("dbo.MessageDefinitionResIndex", "String", name: "ix_String");
            CreateIndex("dbo.MedicationStatementResIndex", "String", name: "ix_String");
            CreateIndex("dbo.MedicationRequestResIndex", "String", name: "ix_String");
            CreateIndex("dbo.MedicationDispenseResIndex", "String", name: "ix_String");
            CreateIndex("dbo.MedicationAdministrationResIndex", "String", name: "ix_String");
            CreateIndex("dbo.MedicationResIndex", "String", name: "ix_String");
            CreateIndex("dbo.MediaResIndex", "String", name: "ix_String");
            CreateIndex("dbo.MeasureReportResIndex", "String", name: "ix_String");
            CreateIndex("dbo.MeasureResIndex", "String", name: "ix_String");
            CreateIndex("dbo.LocationResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ListResIndex", "String", name: "ix_String");
            CreateIndex("dbo.LinkageResIndex", "String", name: "ix_String");
            CreateIndex("dbo.LibraryResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ImplementationGuideResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ImmunizationRecommendationResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ImmunizationResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ImagingStudyResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ImagingManifestResIndex", "String", name: "ix_String");
            CreateIndex("dbo.HealthcareServiceResIndex", "String", name: "ix_String");
            CreateIndex("dbo.GuidanceResponseResIndex", "String", name: "ix_String");
            CreateIndex("dbo.GroupResIndex", "String", name: "ix_String");
            CreateIndex("dbo.GraphDefinitionResIndex", "String", name: "ix_String");
            CreateIndex("dbo.GoalResIndex", "String", name: "ix_String");
            CreateIndex("dbo.FlagResIndex", "String", name: "ix_String");
            CreateIndex("dbo.FamilyMemberHistoryResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ExplanationOfBenefitResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ExpansionProfileResIndex", "String", name: "ix_String");
            CreateIndex("dbo.EpisodeOfCareResIndex", "String", name: "ix_String");
            CreateIndex("dbo.EnrollmentResponseResIndex", "String", name: "ix_String");
            CreateIndex("dbo.EnrollmentRequestResIndex", "String", name: "ix_String");
            CreateIndex("dbo.EndpointResIndex", "String", name: "ix_String");
            CreateIndex("dbo.EncounterResIndex", "String", name: "ix_String");
            CreateIndex("dbo.EligibilityResponseResIndex", "String", name: "ix_String");
            CreateIndex("dbo.EligibilityRequestResIndex", "String", name: "ix_String");
            CreateIndex("dbo.DocumentReferenceResIndex", "String", name: "ix_String");
            CreateIndex("dbo.DocumentManifestResIndex", "String", name: "ix_String");
            CreateIndex("dbo.DiagnosticReportResIndex", "String", name: "ix_String");
            CreateIndex("dbo.DeviceUseStatementResIndex", "String", name: "ix_String");
            CreateIndex("dbo.DeviceRequestResIndex", "String", name: "ix_String");
            CreateIndex("dbo.DeviceMetricResIndex", "String", name: "ix_String");
            CreateIndex("dbo.DeviceComponentResIndex", "String", name: "ix_String");
            CreateIndex("dbo.DeviceResIndex", "String", name: "ix_String");
            CreateIndex("dbo.DetectedIssueResIndex", "String", name: "ix_String");
            CreateIndex("dbo.DataElementResIndex", "String", name: "ix_String");
            CreateIndex("dbo.CoverageResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ContractResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ConsentResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ConditionResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ConceptMapResIndex", "String", name: "ix_String");
            CreateIndex("dbo.CompositionResIndex", "String", name: "ix_String");
            CreateIndex("dbo.CompartmentDefinitionResIndex", "String", name: "ix_String");
            CreateIndex("dbo.CommunicationRequestResIndex", "String", name: "ix_String");
            CreateIndex("dbo.CommunicationResIndex", "String", name: "ix_String");
            CreateIndex("dbo.CodeSystemResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ClinicalImpressionResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ClaimResponseResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ClaimResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ChargeItemResIndex", "String", name: "ix_String");
            CreateIndex("dbo.CareTeamResIndex", "String", name: "ix_String");
            CreateIndex("dbo.CarePlanResIndex", "String", name: "ix_String");
            CreateIndex("dbo.CapabilityStatementResIndex", "String", name: "ix_String");
            CreateIndex("dbo.BundleResIndex", "String", name: "ix_String");
            CreateIndex("dbo.BodySiteResIndex", "String", name: "ix_String");
            CreateIndex("dbo.BinaryResIndex", "String", name: "ix_String");
            CreateIndex("dbo.BasicResIndex", "String", name: "ix_String");
            CreateIndex("dbo.AuditEventResIndex", "String", name: "ix_String");
            CreateIndex("dbo.AppointmentResponseResIndex", "String", name: "ix_String");
            CreateIndex("dbo.AppointmentResIndex", "String", name: "ix_String");
            CreateIndex("dbo.AllergyIntoleranceResIndex", "String", name: "ix_String");
            CreateIndex("dbo.AdverseEventResIndex", "String", name: "ix_String");
            CreateIndex("dbo.ActivityDefinitionResIndex", "String", name: "ix_String");
            CreateIndex("dbo.AccountResIndex", "String", name: "ix_String");
        }
    }
}
