namespace Pyro.DataLayer.Migrations
{
  using System;
  using System.Data.Entity.Migrations;

  public partial class AddForeignKeyToFhirReleaseTableToResources : DbMigration
  {
    public override void Up()
    {
      // ADD THIS BY HAND      
      var ResourceList = Hl7.Fhir.Model.ModelInfo.SupportedResources;
      foreach (var ResourceName in ResourceList)
      {
        AddColumn($"dbo.{ResourceName}Res", "FhirReleaseId", c => c.Int(nullable: true));
        Sql($@"UPDATE dbo.{ResourceName}Res SET FhirReleaseId = (SELECT TOP 1 [Id] FROM [dbo].[_FhirRelease] where [FhirVersion] = '3.0.1') where FhirReleaseId IS NULL");
        AlterColumn($"dbo.{ResourceName}Res", "FhirReleaseId", c => c.Int(nullable: false));
        CreateIndex($"dbo.{ResourceName}Res", "FhirReleaseId");
        AddForeignKey($"dbo.{ResourceName}Res", "FhirReleaseId", "dbo._FhirRelease", "Id");
      }

    }

    public override void Down()
    {
      DropForeignKey("dbo.VisionPrescriptionRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ValueSetRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.TestScriptRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.TestReportRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.TaskRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.SupplyRequestRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.SupplyDeliveryRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.SubstanceRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.SubscriptionRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.StructureMapRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.StructureDefinitionRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.SpecimenRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.SlotRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ServiceDefinitionRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.SequenceRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.SearchParameterRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ScheduleRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.RiskAssessmentRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ResearchSubjectRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ResearchStudyRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.RequestGroupRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.RelatedPersonRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ReferralRequestRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.QuestionnaireResponseRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.QuestionnaireRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ProvenanceRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ProcessResponseRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ProcessRequestRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ProcedureRequestRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ProcedureRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.PractitionerRoleRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.PractitionerRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.PlanDefinitionRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.PersonRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.PaymentReconciliationRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.PaymentNoticeRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.PatientRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ParametersRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.OrganizationRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.OperationOutcomeRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.OperationDefinitionRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ObservationRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.NutritionOrderRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.NamingSystemRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.MessageHeaderRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.MessageDefinitionRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.MedicationStatementRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.MedicationRequestRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.MedicationRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.MedicationDispenseRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.MedicationAdministrationRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.MediaRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.MeasureReportRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.MeasureRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.LocationRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ListRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.LinkageRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.LibraryRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ImplementationGuideRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ImmunizationRecommendationRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ImmunizationRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ImagingStudyRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ImagingManifestRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.HealthcareServiceRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.GuidanceResponseRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.GroupRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.GraphDefinitionRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.GoalRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.FlagRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.FamilyMemberHistoryRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ExplanationOfBenefitRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ExpansionProfileRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.EpisodeOfCareRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.EnrollmentResponseRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.EnrollmentRequestRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.EndpointRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.EncounterRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.EligibilityResponseRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.EligibilityRequestRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.DocumentReferenceRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.DocumentManifestRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.DiagnosticReportRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.DeviceUseStatementRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.DeviceRequestRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.DeviceMetricRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.DeviceRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.DeviceComponentRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.DetectedIssueRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.DataElementRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.CoverageRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ContractRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ConsentRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ConditionRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ConceptMapRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.CompositionRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.CompartmentDefinitionRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.CommunicationRequestRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.CommunicationRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.CodeSystemRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ClinicalImpressionRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ClaimResponseRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ClaimRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ChargeItemRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.CareTeamRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.CarePlanRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.CapabilityStatementRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.BundleRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.BodySiteRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.BinaryRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.BasicRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.AuditEventRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.AppointmentResponseRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.AppointmentRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.AllergyIntoleranceRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.AdverseEventRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.ActivityDefinitionRes", "FhirReleaseId", "dbo._FhirRelease");
      DropForeignKey("dbo.AccountRes", "FhirReleaseId", "dbo._FhirRelease");
      DropIndex("dbo.VisionPrescriptionRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ValueSetRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.TestScriptRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.TestReportRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.TaskRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.SupplyRequestRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.SupplyDeliveryRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.SubstanceRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.SubscriptionRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.StructureMapRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.StructureDefinitionRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.SpecimenRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.SlotRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ServiceDefinitionRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.SequenceRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.SearchParameterRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ScheduleRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.RiskAssessmentRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ResearchSubjectRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ResearchStudyRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.RequestGroupRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.RelatedPersonRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ReferralRequestRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.QuestionnaireResponseRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.QuestionnaireRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ProvenanceRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ProcessResponseRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ProcessRequestRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ProcedureRequestRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ProcedureRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.PractitionerRoleRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.PractitionerRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.PlanDefinitionRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.PersonRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.PaymentReconciliationRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.PaymentNoticeRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.PatientRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ParametersRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.OrganizationRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.OperationOutcomeRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.OperationDefinitionRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ObservationRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.NutritionOrderRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.NamingSystemRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.MessageHeaderRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.MessageDefinitionRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.MedicationStatementRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.MedicationRequestRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.MedicationRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.MedicationDispenseRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.MedicationAdministrationRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.MediaRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.MeasureReportRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.MeasureRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.LocationRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ListRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.LinkageRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.LibraryRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ImplementationGuideRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ImmunizationRecommendationRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ImmunizationRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ImagingStudyRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ImagingManifestRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.HealthcareServiceRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.GuidanceResponseRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.GroupRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.GraphDefinitionRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.GoalRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.FlagRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.FamilyMemberHistoryRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ExplanationOfBenefitRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ExpansionProfileRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.EpisodeOfCareRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.EnrollmentResponseRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.EnrollmentRequestRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.EndpointRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.EncounterRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.EligibilityResponseRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.EligibilityRequestRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.DocumentReferenceRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.DocumentManifestRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.DiagnosticReportRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.DeviceUseStatementRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.DeviceRequestRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.DeviceMetricRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.DeviceRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.DeviceComponentRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.DetectedIssueRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.DataElementRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.CoverageRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ContractRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ConsentRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ConditionRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ConceptMapRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.CompositionRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.CompartmentDefinitionRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.CommunicationRequestRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.CommunicationRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.CodeSystemRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ClinicalImpressionRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ClaimResponseRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ClaimRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ChargeItemRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.CareTeamRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.CarePlanRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.CapabilityStatementRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.BundleRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.BodySiteRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.BinaryRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.BasicRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.AuditEventRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.AppointmentResponseRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.AppointmentRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.AllergyIntoleranceRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.AdverseEventRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.ActivityDefinitionRes", new[] { "FhirReleaseId" });
      DropIndex("dbo.AccountRes", new[] { "FhirReleaseId" });
      DropColumn("dbo.VisionPrescriptionRes", "FhirReleaseId");
      DropColumn("dbo.ValueSetRes", "FhirReleaseId");
      DropColumn("dbo.TestScriptRes", "FhirReleaseId");
      DropColumn("dbo.TestReportRes", "FhirReleaseId");
      DropColumn("dbo.TaskRes", "FhirReleaseId");
      DropColumn("dbo.SupplyRequestRes", "FhirReleaseId");
      DropColumn("dbo.SupplyDeliveryRes", "FhirReleaseId");
      DropColumn("dbo.SubstanceRes", "FhirReleaseId");
      DropColumn("dbo.SubscriptionRes", "FhirReleaseId");
      DropColumn("dbo.StructureMapRes", "FhirReleaseId");
      DropColumn("dbo.StructureDefinitionRes", "FhirReleaseId");
      DropColumn("dbo.SpecimenRes", "FhirReleaseId");
      DropColumn("dbo.SlotRes", "FhirReleaseId");
      DropColumn("dbo.ServiceDefinitionRes", "FhirReleaseId");
      DropColumn("dbo.SequenceRes", "FhirReleaseId");
      DropColumn("dbo.SearchParameterRes", "FhirReleaseId");
      DropColumn("dbo.ScheduleRes", "FhirReleaseId");
      DropColumn("dbo.RiskAssessmentRes", "FhirReleaseId");
      DropColumn("dbo.ResearchSubjectRes", "FhirReleaseId");
      DropColumn("dbo.ResearchStudyRes", "FhirReleaseId");
      DropColumn("dbo.RequestGroupRes", "FhirReleaseId");
      DropColumn("dbo.RelatedPersonRes", "FhirReleaseId");
      DropColumn("dbo.ReferralRequestRes", "FhirReleaseId");
      DropColumn("dbo.QuestionnaireResponseRes", "FhirReleaseId");
      DropColumn("dbo.QuestionnaireRes", "FhirReleaseId");
      DropColumn("dbo.ProvenanceRes", "FhirReleaseId");
      DropColumn("dbo.ProcessResponseRes", "FhirReleaseId");
      DropColumn("dbo.ProcessRequestRes", "FhirReleaseId");
      DropColumn("dbo.ProcedureRequestRes", "FhirReleaseId");
      DropColumn("dbo.ProcedureRes", "FhirReleaseId");
      DropColumn("dbo.PractitionerRoleRes", "FhirReleaseId");
      DropColumn("dbo.PractitionerRes", "FhirReleaseId");
      DropColumn("dbo.PlanDefinitionRes", "FhirReleaseId");
      DropColumn("dbo.PersonRes", "FhirReleaseId");
      DropColumn("dbo.PaymentReconciliationRes", "FhirReleaseId");
      DropColumn("dbo.PaymentNoticeRes", "FhirReleaseId");
      DropColumn("dbo.PatientRes", "FhirReleaseId");
      DropColumn("dbo.ParametersRes", "FhirReleaseId");
      DropColumn("dbo.OrganizationRes", "FhirReleaseId");
      DropColumn("dbo.OperationOutcomeRes", "FhirReleaseId");
      DropColumn("dbo.OperationDefinitionRes", "FhirReleaseId");
      DropColumn("dbo.ObservationRes", "FhirReleaseId");
      DropColumn("dbo.NutritionOrderRes", "FhirReleaseId");
      DropColumn("dbo.NamingSystemRes", "FhirReleaseId");
      DropColumn("dbo.MessageHeaderRes", "FhirReleaseId");
      DropColumn("dbo.MessageDefinitionRes", "FhirReleaseId");
      DropColumn("dbo.MedicationStatementRes", "FhirReleaseId");
      DropColumn("dbo.MedicationRequestRes", "FhirReleaseId");
      DropColumn("dbo.MedicationDispenseRes", "FhirReleaseId");
      DropColumn("dbo.MedicationAdministrationRes", "FhirReleaseId");
      DropColumn("dbo.MedicationRes", "FhirReleaseId");
      DropColumn("dbo.MediaRes", "FhirReleaseId");
      DropColumn("dbo.MeasureReportRes", "FhirReleaseId");
      DropColumn("dbo.MeasureRes", "FhirReleaseId");
      DropColumn("dbo.LocationRes", "FhirReleaseId");
      DropColumn("dbo.ListRes", "FhirReleaseId");
      DropColumn("dbo.LinkageRes", "FhirReleaseId");
      DropColumn("dbo.LibraryRes", "FhirReleaseId");
      DropColumn("dbo.ImplementationGuideRes", "FhirReleaseId");
      DropColumn("dbo.ImmunizationRecommendationRes", "FhirReleaseId");
      DropColumn("dbo.ImmunizationRes", "FhirReleaseId");
      DropColumn("dbo.ImagingStudyRes", "FhirReleaseId");
      DropColumn("dbo.ImagingManifestRes", "FhirReleaseId");
      DropColumn("dbo.HealthcareServiceRes", "FhirReleaseId");
      DropColumn("dbo.GuidanceResponseRes", "FhirReleaseId");
      DropColumn("dbo.GroupRes", "FhirReleaseId");
      DropColumn("dbo.GraphDefinitionRes", "FhirReleaseId");
      DropColumn("dbo.GoalRes", "FhirReleaseId");
      DropColumn("dbo.FlagRes", "FhirReleaseId");
      DropColumn("dbo.FamilyMemberHistoryRes", "FhirReleaseId");
      DropColumn("dbo.ExplanationOfBenefitRes", "FhirReleaseId");
      DropColumn("dbo.ExpansionProfileRes", "FhirReleaseId");
      DropColumn("dbo.EpisodeOfCareRes", "FhirReleaseId");
      DropColumn("dbo.EnrollmentResponseRes", "FhirReleaseId");
      DropColumn("dbo.EnrollmentRequestRes", "FhirReleaseId");
      DropColumn("dbo.EndpointRes", "FhirReleaseId");
      DropColumn("dbo.EncounterRes", "FhirReleaseId");
      DropColumn("dbo.EligibilityResponseRes", "FhirReleaseId");
      DropColumn("dbo.EligibilityRequestRes", "FhirReleaseId");
      DropColumn("dbo.DocumentReferenceRes", "FhirReleaseId");
      DropColumn("dbo.DocumentManifestRes", "FhirReleaseId");
      DropColumn("dbo.DiagnosticReportRes", "FhirReleaseId");
      DropColumn("dbo.DeviceUseStatementRes", "FhirReleaseId");
      DropColumn("dbo.DeviceRequestRes", "FhirReleaseId");
      DropColumn("dbo.DeviceMetricRes", "FhirReleaseId");
      DropColumn("dbo.DeviceComponentRes", "FhirReleaseId");
      DropColumn("dbo.DeviceRes", "FhirReleaseId");
      DropColumn("dbo.DetectedIssueRes", "FhirReleaseId");
      DropColumn("dbo.DataElementRes", "FhirReleaseId");
      DropColumn("dbo.CoverageRes", "FhirReleaseId");
      DropColumn("dbo.ContractRes", "FhirReleaseId");
      DropColumn("dbo.ConsentRes", "FhirReleaseId");
      DropColumn("dbo.ConditionRes", "FhirReleaseId");
      DropColumn("dbo.ConceptMapRes", "FhirReleaseId");
      DropColumn("dbo.CompositionRes", "FhirReleaseId");
      DropColumn("dbo.CompartmentDefinitionRes", "FhirReleaseId");
      DropColumn("dbo.CommunicationRequestRes", "FhirReleaseId");
      DropColumn("dbo.CommunicationRes", "FhirReleaseId");
      DropColumn("dbo.CodeSystemRes", "FhirReleaseId");
      DropColumn("dbo.ClinicalImpressionRes", "FhirReleaseId");
      DropColumn("dbo.ClaimResponseRes", "FhirReleaseId");
      DropColumn("dbo.ClaimRes", "FhirReleaseId");
      DropColumn("dbo.ChargeItemRes", "FhirReleaseId");
      DropColumn("dbo.CareTeamRes", "FhirReleaseId");
      DropColumn("dbo.CarePlanRes", "FhirReleaseId");
      DropColumn("dbo.CapabilityStatementRes", "FhirReleaseId");
      DropColumn("dbo.BundleRes", "FhirReleaseId");
      DropColumn("dbo.BodySiteRes", "FhirReleaseId");
      DropColumn("dbo.BinaryRes", "FhirReleaseId");
      DropColumn("dbo.BasicRes", "FhirReleaseId");
      DropColumn("dbo.AuditEventRes", "FhirReleaseId");
      DropColumn("dbo.AppointmentResponseRes", "FhirReleaseId");
      DropColumn("dbo.AppointmentRes", "FhirReleaseId");
      DropColumn("dbo.AllergyIntoleranceRes", "FhirReleaseId");
      DropColumn("dbo.AdverseEventRes", "FhirReleaseId");
      DropColumn("dbo.ActivityDefinitionRes", "FhirReleaseId");
      DropColumn("dbo.AccountRes", "FhirReleaseId");
    }
  }
}
