namespace Pyro.DataLayer.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddGZipResourceColumn : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.AccountRes", "Resource", c => c.Binary());
            AddColumn("dbo.ActivityDefinitionRes", "Resource", c => c.Binary());
            AddColumn("dbo.AdverseEventRes", "Resource", c => c.Binary());
            AddColumn("dbo.AllergyIntoleranceRes", "Resource", c => c.Binary());
            AddColumn("dbo.AppointmentRes", "Resource", c => c.Binary());
            AddColumn("dbo.AppointmentResponseRes", "Resource", c => c.Binary());
            AddColumn("dbo.AuditEventRes", "Resource", c => c.Binary());
            AddColumn("dbo.BasicRes", "Resource", c => c.Binary());
            AddColumn("dbo.BinaryRes", "Resource", c => c.Binary());
            AddColumn("dbo.BodySiteRes", "Resource", c => c.Binary());
            AddColumn("dbo.BundleRes", "Resource", c => c.Binary());
            AddColumn("dbo.CapabilityStatementRes", "Resource", c => c.Binary());
            AddColumn("dbo.CarePlanRes", "Resource", c => c.Binary());
            AddColumn("dbo.CareTeamRes", "Resource", c => c.Binary());
            AddColumn("dbo.ChargeItemRes", "Resource", c => c.Binary());
            AddColumn("dbo.ClaimRes", "Resource", c => c.Binary());
            AddColumn("dbo.ClaimResponseRes", "Resource", c => c.Binary());
            AddColumn("dbo.ClinicalImpressionRes", "Resource", c => c.Binary());
            AddColumn("dbo.CodeSystemRes", "Resource", c => c.Binary());
            AddColumn("dbo.CommunicationRes", "Resource", c => c.Binary());
            AddColumn("dbo.CommunicationRequestRes", "Resource", c => c.Binary());
            AddColumn("dbo.CompartmentDefinitionRes", "Resource", c => c.Binary());
            AddColumn("dbo.CompositionRes", "Resource", c => c.Binary());
            AddColumn("dbo.ConceptMapRes", "Resource", c => c.Binary());
            AddColumn("dbo.ConditionRes", "Resource", c => c.Binary());
            AddColumn("dbo.ConsentRes", "Resource", c => c.Binary());
            AddColumn("dbo.ContractRes", "Resource", c => c.Binary());
            AddColumn("dbo.CoverageRes", "Resource", c => c.Binary());
            AddColumn("dbo.DataElementRes", "Resource", c => c.Binary());
            AddColumn("dbo.DetectedIssueRes", "Resource", c => c.Binary());
            AddColumn("dbo.DeviceComponentRes", "Resource", c => c.Binary());
            AddColumn("dbo.DeviceRes", "Resource", c => c.Binary());
            AddColumn("dbo.DeviceMetricRes", "Resource", c => c.Binary());
            AddColumn("dbo.DeviceRequestRes", "Resource", c => c.Binary());
            AddColumn("dbo.DeviceUseStatementRes", "Resource", c => c.Binary());
            AddColumn("dbo.DiagnosticReportRes", "Resource", c => c.Binary());
            AddColumn("dbo.DocumentManifestRes", "Resource", c => c.Binary());
            AddColumn("dbo.DocumentReferenceRes", "Resource", c => c.Binary());
            AddColumn("dbo.EligibilityRequestRes", "Resource", c => c.Binary());
            AddColumn("dbo.EligibilityResponseRes", "Resource", c => c.Binary());
            AddColumn("dbo.EncounterRes", "Resource", c => c.Binary());
            AddColumn("dbo.EndpointRes", "Resource", c => c.Binary());
            AddColumn("dbo.EnrollmentRequestRes", "Resource", c => c.Binary());
            AddColumn("dbo.EnrollmentResponseRes", "Resource", c => c.Binary());
            AddColumn("dbo.EpisodeOfCareRes", "Resource", c => c.Binary());
            AddColumn("dbo.ExpansionProfileRes", "Resource", c => c.Binary());
            AddColumn("dbo.ExplanationOfBenefitRes", "Resource", c => c.Binary());
            AddColumn("dbo.FamilyMemberHistoryRes", "Resource", c => c.Binary());
            AddColumn("dbo.FlagRes", "Resource", c => c.Binary());
            AddColumn("dbo.GoalRes", "Resource", c => c.Binary());
            AddColumn("dbo.GraphDefinitionRes", "Resource", c => c.Binary());
            AddColumn("dbo.GroupRes", "Resource", c => c.Binary());
            AddColumn("dbo.GuidanceResponseRes", "Resource", c => c.Binary());
            AddColumn("dbo.HealthcareServiceRes", "Resource", c => c.Binary());
            AddColumn("dbo.ImagingManifestRes", "Resource", c => c.Binary());
            AddColumn("dbo.ImagingStudyRes", "Resource", c => c.Binary());
            AddColumn("dbo.ImmunizationRes", "Resource", c => c.Binary());
            AddColumn("dbo.ImmunizationRecommendationRes", "Resource", c => c.Binary());
            AddColumn("dbo.ImplementationGuideRes", "Resource", c => c.Binary());
            AddColumn("dbo.LibraryRes", "Resource", c => c.Binary());
            AddColumn("dbo.LinkageRes", "Resource", c => c.Binary());
            AddColumn("dbo.ListRes", "Resource", c => c.Binary());
            AddColumn("dbo.LocationRes", "Resource", c => c.Binary());
            AddColumn("dbo.MeasureRes", "Resource", c => c.Binary());
            AddColumn("dbo.MeasureReportRes", "Resource", c => c.Binary());
            AddColumn("dbo.MediaRes", "Resource", c => c.Binary());
            AddColumn("dbo.MedicationAdministrationRes", "Resource", c => c.Binary());
            AddColumn("dbo.MedicationDispenseRes", "Resource", c => c.Binary());
            AddColumn("dbo.MedicationRes", "Resource", c => c.Binary());
            AddColumn("dbo.MedicationRequestRes", "Resource", c => c.Binary());
            AddColumn("dbo.MedicationStatementRes", "Resource", c => c.Binary());
            AddColumn("dbo.MessageDefinitionRes", "Resource", c => c.Binary());
            AddColumn("dbo.MessageHeaderRes", "Resource", c => c.Binary());
            AddColumn("dbo.NamingSystemRes", "Resource", c => c.Binary());
            AddColumn("dbo.NutritionOrderRes", "Resource", c => c.Binary());
            AddColumn("dbo.ObservationRes", "Resource", c => c.Binary());
            AddColumn("dbo.OperationDefinitionRes", "Resource", c => c.Binary());
            AddColumn("dbo.OperationOutcomeRes", "Resource", c => c.Binary());
            AddColumn("dbo.OrganizationRes", "Resource", c => c.Binary());
            AddColumn("dbo.ParametersRes", "Resource", c => c.Binary());
            AddColumn("dbo.PatientRes", "Resource", c => c.Binary());
            AddColumn("dbo.PaymentNoticeRes", "Resource", c => c.Binary());
            AddColumn("dbo.PaymentReconciliationRes", "Resource", c => c.Binary());
            AddColumn("dbo.PersonRes", "Resource", c => c.Binary());
            AddColumn("dbo.PlanDefinitionRes", "Resource", c => c.Binary());
            AddColumn("dbo.PractitionerRes", "Resource", c => c.Binary());
            AddColumn("dbo.PractitionerRoleRes", "Resource", c => c.Binary());
            AddColumn("dbo.ProcedureRes", "Resource", c => c.Binary());
            AddColumn("dbo.ProcedureRequestRes", "Resource", c => c.Binary());
            AddColumn("dbo.ProcessRequestRes", "Resource", c => c.Binary());
            AddColumn("dbo.ProcessResponseRes", "Resource", c => c.Binary());
            AddColumn("dbo.ProvenanceRes", "Resource", c => c.Binary());
            AddColumn("dbo.QuestionnaireRes", "Resource", c => c.Binary());
            AddColumn("dbo.QuestionnaireResponseRes", "Resource", c => c.Binary());
            AddColumn("dbo.ReferralRequestRes", "Resource", c => c.Binary());
            AddColumn("dbo.RelatedPersonRes", "Resource", c => c.Binary());
            AddColumn("dbo.RequestGroupRes", "Resource", c => c.Binary());
            AddColumn("dbo.ResearchStudyRes", "Resource", c => c.Binary());
            AddColumn("dbo.ResearchSubjectRes", "Resource", c => c.Binary());
            AddColumn("dbo.RiskAssessmentRes", "Resource", c => c.Binary());
            AddColumn("dbo.ScheduleRes", "Resource", c => c.Binary());
            AddColumn("dbo.SearchParameterRes", "Resource", c => c.Binary());
            AddColumn("dbo.SequenceRes", "Resource", c => c.Binary());
            AddColumn("dbo.ServiceDefinitionRes", "Resource", c => c.Binary());
            AddColumn("dbo.SlotRes", "Resource", c => c.Binary());
            AddColumn("dbo.SpecimenRes", "Resource", c => c.Binary());
            AddColumn("dbo.StructureDefinitionRes", "Resource", c => c.Binary());
            AddColumn("dbo.StructureMapRes", "Resource", c => c.Binary());
            AddColumn("dbo.SubscriptionRes", "Resource", c => c.Binary());
            AddColumn("dbo.SubstanceRes", "Resource", c => c.Binary());
            AddColumn("dbo.SupplyDeliveryRes", "Resource", c => c.Binary());
            AddColumn("dbo.SupplyRequestRes", "Resource", c => c.Binary());
            AddColumn("dbo.TaskRes", "Resource", c => c.Binary());
            AddColumn("dbo.TestReportRes", "Resource", c => c.Binary());
            AddColumn("dbo.TestScriptRes", "Resource", c => c.Binary());
            AddColumn("dbo.ValueSetRes", "Resource", c => c.Binary());
            AddColumn("dbo.VisionPrescriptionRes", "Resource", c => c.Binary());
            AlterColumn("dbo.AccountRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ActivityDefinitionRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.AdverseEventRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.AllergyIntoleranceRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.AppointmentRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.AppointmentResponseRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.AuditEventRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.BasicRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.BinaryRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.BodySiteRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.BundleRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.CapabilityStatementRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.CarePlanRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.CareTeamRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ChargeItemRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ClaimRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ClaimResponseRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ClinicalImpressionRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.CodeSystemRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.CommunicationRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.CommunicationRequestRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.CompartmentDefinitionRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.CompositionRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ConceptMapRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ConditionRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ConsentRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ContractRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.CoverageRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.DataElementRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.DetectedIssueRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.DeviceComponentRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.DeviceRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.DeviceMetricRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.DeviceRequestRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.DeviceUseStatementRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.DiagnosticReportRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.DocumentManifestRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.DocumentReferenceRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.EligibilityRequestRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.EligibilityResponseRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.EncounterRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.EndpointRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.EnrollmentRequestRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.EnrollmentResponseRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.EpisodeOfCareRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ExpansionProfileRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ExplanationOfBenefitRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.FamilyMemberHistoryRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.FlagRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.GoalRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.GraphDefinitionRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.GroupRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.GuidanceResponseRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.HealthcareServiceRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ImagingManifestRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ImagingStudyRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ImmunizationRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ImmunizationRecommendationRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ImplementationGuideRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.LibraryRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.LinkageRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ListRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.LocationRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.MeasureRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.MeasureReportRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.MediaRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.MedicationAdministrationRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.MedicationDispenseRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.MedicationRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.MedicationRequestRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.MedicationStatementRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.MessageDefinitionRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.MessageHeaderRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.NamingSystemRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.NutritionOrderRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ObservationRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.OperationDefinitionRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.OperationOutcomeRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.OrganizationRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ParametersRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.PatientRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.PaymentNoticeRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.PaymentReconciliationRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.PersonRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.PlanDefinitionRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.PractitionerRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.PractitionerRoleRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ProcedureRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ProcedureRequestRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ProcessRequestRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ProcessResponseRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ProvenanceRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.QuestionnaireRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.QuestionnaireResponseRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ReferralRequestRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.RelatedPersonRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.RequestGroupRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ResearchStudyRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ResearchSubjectRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.RiskAssessmentRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ScheduleRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.SearchParameterRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.SequenceRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ServiceDefinitionRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.SlotRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.SpecimenRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.StructureDefinitionRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.StructureMapRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.SubscriptionRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.SubstanceRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.SupplyDeliveryRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.SupplyRequestRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.TaskRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.TestReportRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.TestScriptRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.ValueSetRes", "XmlBlob", c => c.String());
            AlterColumn("dbo.VisionPrescriptionRes", "XmlBlob", c => c.String());
        }
        
        public override void Down()
        {
            AlterColumn("dbo.VisionPrescriptionRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ValueSetRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.TestScriptRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.TestReportRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.TaskRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.SupplyRequestRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.SupplyDeliveryRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.SubstanceRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.SubscriptionRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.StructureMapRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.StructureDefinitionRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.SpecimenRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.SlotRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ServiceDefinitionRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.SequenceRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.SearchParameterRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ScheduleRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.RiskAssessmentRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ResearchSubjectRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ResearchStudyRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.RequestGroupRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.RelatedPersonRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ReferralRequestRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.QuestionnaireResponseRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.QuestionnaireRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ProvenanceRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ProcessResponseRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ProcessRequestRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ProcedureRequestRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ProcedureRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.PractitionerRoleRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.PractitionerRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.PlanDefinitionRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.PersonRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.PaymentReconciliationRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.PaymentNoticeRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.PatientRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ParametersRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.OrganizationRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.OperationOutcomeRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.OperationDefinitionRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ObservationRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.NutritionOrderRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.NamingSystemRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.MessageHeaderRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.MessageDefinitionRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.MedicationStatementRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.MedicationRequestRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.MedicationRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.MedicationDispenseRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.MedicationAdministrationRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.MediaRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.MeasureReportRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.MeasureRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.LocationRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ListRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.LinkageRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.LibraryRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ImplementationGuideRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ImmunizationRecommendationRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ImmunizationRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ImagingStudyRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ImagingManifestRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.HealthcareServiceRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.GuidanceResponseRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.GroupRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.GraphDefinitionRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.GoalRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.FlagRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.FamilyMemberHistoryRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ExplanationOfBenefitRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ExpansionProfileRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.EpisodeOfCareRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.EnrollmentResponseRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.EnrollmentRequestRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.EndpointRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.EncounterRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.EligibilityResponseRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.EligibilityRequestRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.DocumentReferenceRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.DocumentManifestRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.DiagnosticReportRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.DeviceUseStatementRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.DeviceRequestRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.DeviceMetricRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.DeviceRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.DeviceComponentRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.DetectedIssueRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.DataElementRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.CoverageRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ContractRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ConsentRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ConditionRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ConceptMapRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.CompositionRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.CompartmentDefinitionRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.CommunicationRequestRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.CommunicationRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.CodeSystemRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ClinicalImpressionRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ClaimResponseRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ClaimRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ChargeItemRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.CareTeamRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.CarePlanRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.CapabilityStatementRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.BundleRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.BodySiteRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.BinaryRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.BasicRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.AuditEventRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.AppointmentResponseRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.AppointmentRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.AllergyIntoleranceRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.AdverseEventRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.ActivityDefinitionRes", "XmlBlob", c => c.String(nullable: false));
            AlterColumn("dbo.AccountRes", "XmlBlob", c => c.String(nullable: false));
            DropColumn("dbo.VisionPrescriptionRes", "Resource");
            DropColumn("dbo.ValueSetRes", "Resource");
            DropColumn("dbo.TestScriptRes", "Resource");
            DropColumn("dbo.TestReportRes", "Resource");
            DropColumn("dbo.TaskRes", "Resource");
            DropColumn("dbo.SupplyRequestRes", "Resource");
            DropColumn("dbo.SupplyDeliveryRes", "Resource");
            DropColumn("dbo.SubstanceRes", "Resource");
            DropColumn("dbo.SubscriptionRes", "Resource");
            DropColumn("dbo.StructureMapRes", "Resource");
            DropColumn("dbo.StructureDefinitionRes", "Resource");
            DropColumn("dbo.SpecimenRes", "Resource");
            DropColumn("dbo.SlotRes", "Resource");
            DropColumn("dbo.ServiceDefinitionRes", "Resource");
            DropColumn("dbo.SequenceRes", "Resource");
            DropColumn("dbo.SearchParameterRes", "Resource");
            DropColumn("dbo.ScheduleRes", "Resource");
            DropColumn("dbo.RiskAssessmentRes", "Resource");
            DropColumn("dbo.ResearchSubjectRes", "Resource");
            DropColumn("dbo.ResearchStudyRes", "Resource");
            DropColumn("dbo.RequestGroupRes", "Resource");
            DropColumn("dbo.RelatedPersonRes", "Resource");
            DropColumn("dbo.ReferralRequestRes", "Resource");
            DropColumn("dbo.QuestionnaireResponseRes", "Resource");
            DropColumn("dbo.QuestionnaireRes", "Resource");
            DropColumn("dbo.ProvenanceRes", "Resource");
            DropColumn("dbo.ProcessResponseRes", "Resource");
            DropColumn("dbo.ProcessRequestRes", "Resource");
            DropColumn("dbo.ProcedureRequestRes", "Resource");
            DropColumn("dbo.ProcedureRes", "Resource");
            DropColumn("dbo.PractitionerRoleRes", "Resource");
            DropColumn("dbo.PractitionerRes", "Resource");
            DropColumn("dbo.PlanDefinitionRes", "Resource");
            DropColumn("dbo.PersonRes", "Resource");
            DropColumn("dbo.PaymentReconciliationRes", "Resource");
            DropColumn("dbo.PaymentNoticeRes", "Resource");
            DropColumn("dbo.PatientRes", "Resource");
            DropColumn("dbo.ParametersRes", "Resource");
            DropColumn("dbo.OrganizationRes", "Resource");
            DropColumn("dbo.OperationOutcomeRes", "Resource");
            DropColumn("dbo.OperationDefinitionRes", "Resource");
            DropColumn("dbo.ObservationRes", "Resource");
            DropColumn("dbo.NutritionOrderRes", "Resource");
            DropColumn("dbo.NamingSystemRes", "Resource");
            DropColumn("dbo.MessageHeaderRes", "Resource");
            DropColumn("dbo.MessageDefinitionRes", "Resource");
            DropColumn("dbo.MedicationStatementRes", "Resource");
            DropColumn("dbo.MedicationRequestRes", "Resource");
            DropColumn("dbo.MedicationRes", "Resource");
            DropColumn("dbo.MedicationDispenseRes", "Resource");
            DropColumn("dbo.MedicationAdministrationRes", "Resource");
            DropColumn("dbo.MediaRes", "Resource");
            DropColumn("dbo.MeasureReportRes", "Resource");
            DropColumn("dbo.MeasureRes", "Resource");
            DropColumn("dbo.LocationRes", "Resource");
            DropColumn("dbo.ListRes", "Resource");
            DropColumn("dbo.LinkageRes", "Resource");
            DropColumn("dbo.LibraryRes", "Resource");
            DropColumn("dbo.ImplementationGuideRes", "Resource");
            DropColumn("dbo.ImmunizationRecommendationRes", "Resource");
            DropColumn("dbo.ImmunizationRes", "Resource");
            DropColumn("dbo.ImagingStudyRes", "Resource");
            DropColumn("dbo.ImagingManifestRes", "Resource");
            DropColumn("dbo.HealthcareServiceRes", "Resource");
            DropColumn("dbo.GuidanceResponseRes", "Resource");
            DropColumn("dbo.GroupRes", "Resource");
            DropColumn("dbo.GraphDefinitionRes", "Resource");
            DropColumn("dbo.GoalRes", "Resource");
            DropColumn("dbo.FlagRes", "Resource");
            DropColumn("dbo.FamilyMemberHistoryRes", "Resource");
            DropColumn("dbo.ExplanationOfBenefitRes", "Resource");
            DropColumn("dbo.ExpansionProfileRes", "Resource");
            DropColumn("dbo.EpisodeOfCareRes", "Resource");
            DropColumn("dbo.EnrollmentResponseRes", "Resource");
            DropColumn("dbo.EnrollmentRequestRes", "Resource");
            DropColumn("dbo.EndpointRes", "Resource");
            DropColumn("dbo.EncounterRes", "Resource");
            DropColumn("dbo.EligibilityResponseRes", "Resource");
            DropColumn("dbo.EligibilityRequestRes", "Resource");
            DropColumn("dbo.DocumentReferenceRes", "Resource");
            DropColumn("dbo.DocumentManifestRes", "Resource");
            DropColumn("dbo.DiagnosticReportRes", "Resource");
            DropColumn("dbo.DeviceUseStatementRes", "Resource");
            DropColumn("dbo.DeviceRequestRes", "Resource");
            DropColumn("dbo.DeviceMetricRes", "Resource");
            DropColumn("dbo.DeviceRes", "Resource");
            DropColumn("dbo.DeviceComponentRes", "Resource");
            DropColumn("dbo.DetectedIssueRes", "Resource");
            DropColumn("dbo.DataElementRes", "Resource");
            DropColumn("dbo.CoverageRes", "Resource");
            DropColumn("dbo.ContractRes", "Resource");
            DropColumn("dbo.ConsentRes", "Resource");
            DropColumn("dbo.ConditionRes", "Resource");
            DropColumn("dbo.ConceptMapRes", "Resource");
            DropColumn("dbo.CompositionRes", "Resource");
            DropColumn("dbo.CompartmentDefinitionRes", "Resource");
            DropColumn("dbo.CommunicationRequestRes", "Resource");
            DropColumn("dbo.CommunicationRes", "Resource");
            DropColumn("dbo.CodeSystemRes", "Resource");
            DropColumn("dbo.ClinicalImpressionRes", "Resource");
            DropColumn("dbo.ClaimResponseRes", "Resource");
            DropColumn("dbo.ClaimRes", "Resource");
            DropColumn("dbo.ChargeItemRes", "Resource");
            DropColumn("dbo.CareTeamRes", "Resource");
            DropColumn("dbo.CarePlanRes", "Resource");
            DropColumn("dbo.CapabilityStatementRes", "Resource");
            DropColumn("dbo.BundleRes", "Resource");
            DropColumn("dbo.BodySiteRes", "Resource");
            DropColumn("dbo.BinaryRes", "Resource");
            DropColumn("dbo.BasicRes", "Resource");
            DropColumn("dbo.AuditEventRes", "Resource");
            DropColumn("dbo.AppointmentResponseRes", "Resource");
            DropColumn("dbo.AppointmentRes", "Resource");
            DropColumn("dbo.AllergyIntoleranceRes", "Resource");
            DropColumn("dbo.AdverseEventRes", "Resource");
            DropColumn("dbo.ActivityDefinitionRes", "Resource");
            DropColumn("dbo.AccountRes", "Resource");
        }
    }
}
