namespace Pyro.DataLayer.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class SetForgienKeyToFhirReleaseForResource : DbMigration
    {
        public override void Up()
        {
            AlterColumn("dbo.AccountRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ActivityDefinitionRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.AdverseEventRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.AllergyIntoleranceRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.AppointmentRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.AppointmentResponseRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.AuditEventRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.BasicRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.BinaryRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.BodySiteRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.BundleRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.CapabilityStatementRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.CarePlanRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.CareTeamRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ChargeItemRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ClaimRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ClaimResponseRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ClinicalImpressionRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.CodeSystemRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.CommunicationRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.CommunicationRequestRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.CompartmentDefinitionRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.CompositionRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ConceptMapRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ConditionRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ConsentRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ContractRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.CoverageRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.DataElementRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.DetectedIssueRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.DeviceRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.DeviceComponentRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.DeviceMetricRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.DeviceRequestRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.DeviceUseStatementRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.DiagnosticReportRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.DocumentManifestRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.DocumentReferenceRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.EligibilityRequestRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.EligibilityResponseRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.EncounterRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.EndpointRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.EnrollmentRequestRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.EnrollmentResponseRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.EpisodeOfCareRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ExpansionProfileRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ExplanationOfBenefitRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.FamilyMemberHistoryRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.FlagRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.GoalRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.GraphDefinitionRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.GroupRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.GuidanceResponseRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.HealthcareServiceRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ImagingManifestRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ImagingStudyRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ImmunizationRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ImmunizationRecommendationRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ImplementationGuideRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.LibraryRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.LinkageRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ListRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.LocationRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.MeasureRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.MeasureReportRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.MediaRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.MedicationRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.MedicationAdministrationRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.MedicationDispenseRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.MedicationRequestRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.MedicationStatementRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.MessageDefinitionRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.MessageHeaderRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.NamingSystemRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.NutritionOrderRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ObservationRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.OperationDefinitionRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.OperationOutcomeRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.OrganizationRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ParametersRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.PatientRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.PaymentNoticeRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.PaymentReconciliationRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.PersonRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.PlanDefinitionRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.PractitionerRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.PractitionerRoleRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ProcedureRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ProcedureRequestRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ProcessRequestRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ProcessResponseRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ProvenanceRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.QuestionnaireRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.QuestionnaireResponseRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ReferralRequestRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.RelatedPersonRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.RequestGroupRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ResearchStudyRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ResearchSubjectRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.RiskAssessmentRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ScheduleRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.SearchParameterRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.SequenceRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ServiceDefinitionRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.SlotRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.SpecimenRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.StructureDefinitionRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.StructureMapRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.SubscriptionRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.SubstanceRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.SupplyDeliveryRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.SupplyRequestRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.TaskRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.TestReportRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.TestScriptRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.ValueSetRes", "FhirReleaseId", c => c.Int(nullable: false));
            AlterColumn("dbo.VisionPrescriptionRes", "FhirReleaseId", c => c.Int(nullable: false));
            CreateIndex("dbo.AccountRes", "FhirReleaseId");
            CreateIndex("dbo.ActivityDefinitionRes", "FhirReleaseId");
            CreateIndex("dbo.AdverseEventRes", "FhirReleaseId");
            CreateIndex("dbo.AllergyIntoleranceRes", "FhirReleaseId");
            CreateIndex("dbo.AppointmentRes", "FhirReleaseId");
            CreateIndex("dbo.AppointmentResponseRes", "FhirReleaseId");
            CreateIndex("dbo.AuditEventRes", "FhirReleaseId");
            CreateIndex("dbo.BasicRes", "FhirReleaseId");
            CreateIndex("dbo.BinaryRes", "FhirReleaseId");
            CreateIndex("dbo.BodySiteRes", "FhirReleaseId");
            CreateIndex("dbo.BundleRes", "FhirReleaseId");
            CreateIndex("dbo.CapabilityStatementRes", "FhirReleaseId");
            CreateIndex("dbo.CarePlanRes", "FhirReleaseId");
            CreateIndex("dbo.CareTeamRes", "FhirReleaseId");
            CreateIndex("dbo.ChargeItemRes", "FhirReleaseId");
            CreateIndex("dbo.ClaimRes", "FhirReleaseId");
            CreateIndex("dbo.ClaimResponseRes", "FhirReleaseId");
            CreateIndex("dbo.ClinicalImpressionRes", "FhirReleaseId");
            CreateIndex("dbo.CodeSystemRes", "FhirReleaseId");
            CreateIndex("dbo.CommunicationRes", "FhirReleaseId");
            CreateIndex("dbo.CommunicationRequestRes", "FhirReleaseId");
            CreateIndex("dbo.CompartmentDefinitionRes", "FhirReleaseId");
            CreateIndex("dbo.CompositionRes", "FhirReleaseId");
            CreateIndex("dbo.ConceptMapRes", "FhirReleaseId");
            CreateIndex("dbo.ConditionRes", "FhirReleaseId");
            CreateIndex("dbo.ConsentRes", "FhirReleaseId");
            CreateIndex("dbo.ContractRes", "FhirReleaseId");
            CreateIndex("dbo.CoverageRes", "FhirReleaseId");
            CreateIndex("dbo.DataElementRes", "FhirReleaseId");
            CreateIndex("dbo.DetectedIssueRes", "FhirReleaseId");
            CreateIndex("dbo.DeviceComponentRes", "FhirReleaseId");
            CreateIndex("dbo.DeviceRes", "FhirReleaseId");
            CreateIndex("dbo.DeviceMetricRes", "FhirReleaseId");
            CreateIndex("dbo.DeviceRequestRes", "FhirReleaseId");
            CreateIndex("dbo.DeviceUseStatementRes", "FhirReleaseId");
            CreateIndex("dbo.DiagnosticReportRes", "FhirReleaseId");
            CreateIndex("dbo.DocumentManifestRes", "FhirReleaseId");
            CreateIndex("dbo.DocumentReferenceRes", "FhirReleaseId");
            CreateIndex("dbo.EligibilityRequestRes", "FhirReleaseId");
            CreateIndex("dbo.EligibilityResponseRes", "FhirReleaseId");
            CreateIndex("dbo.EncounterRes", "FhirReleaseId");
            CreateIndex("dbo.EndpointRes", "FhirReleaseId");
            CreateIndex("dbo.EnrollmentRequestRes", "FhirReleaseId");
            CreateIndex("dbo.EnrollmentResponseRes", "FhirReleaseId");
            CreateIndex("dbo.EpisodeOfCareRes", "FhirReleaseId");
            CreateIndex("dbo.ExpansionProfileRes", "FhirReleaseId");
            CreateIndex("dbo.ExplanationOfBenefitRes", "FhirReleaseId");
            CreateIndex("dbo.FamilyMemberHistoryRes", "FhirReleaseId");
            CreateIndex("dbo.FlagRes", "FhirReleaseId");
            CreateIndex("dbo.GoalRes", "FhirReleaseId");
            CreateIndex("dbo.GraphDefinitionRes", "FhirReleaseId");
            CreateIndex("dbo.GroupRes", "FhirReleaseId");
            CreateIndex("dbo.GuidanceResponseRes", "FhirReleaseId");
            CreateIndex("dbo.HealthcareServiceRes", "FhirReleaseId");
            CreateIndex("dbo.ImagingManifestRes", "FhirReleaseId");
            CreateIndex("dbo.ImagingStudyRes", "FhirReleaseId");
            CreateIndex("dbo.ImmunizationRes", "FhirReleaseId");
            CreateIndex("dbo.ImmunizationRecommendationRes", "FhirReleaseId");
            CreateIndex("dbo.ImplementationGuideRes", "FhirReleaseId");
            CreateIndex("dbo.LibraryRes", "FhirReleaseId");
            CreateIndex("dbo.LinkageRes", "FhirReleaseId");
            CreateIndex("dbo.ListRes", "FhirReleaseId");
            CreateIndex("dbo.LocationRes", "FhirReleaseId");
            CreateIndex("dbo.MeasureRes", "FhirReleaseId");
            CreateIndex("dbo.MeasureReportRes", "FhirReleaseId");
            CreateIndex("dbo.MediaRes", "FhirReleaseId");
            CreateIndex("dbo.MedicationAdministrationRes", "FhirReleaseId");
            CreateIndex("dbo.MedicationDispenseRes", "FhirReleaseId");
            CreateIndex("dbo.MedicationRes", "FhirReleaseId");
            CreateIndex("dbo.MedicationRequestRes", "FhirReleaseId");
            CreateIndex("dbo.MedicationStatementRes", "FhirReleaseId");
            CreateIndex("dbo.MessageDefinitionRes", "FhirReleaseId");
            CreateIndex("dbo.MessageHeaderRes", "FhirReleaseId");
            CreateIndex("dbo.NamingSystemRes", "FhirReleaseId");
            CreateIndex("dbo.NutritionOrderRes", "FhirReleaseId");
            CreateIndex("dbo.ObservationRes", "FhirReleaseId");
            CreateIndex("dbo.OperationDefinitionRes", "FhirReleaseId");
            CreateIndex("dbo.OperationOutcomeRes", "FhirReleaseId");
            CreateIndex("dbo.OrganizationRes", "FhirReleaseId");
            CreateIndex("dbo.ParametersRes", "FhirReleaseId");
            CreateIndex("dbo.PatientRes", "FhirReleaseId");
            CreateIndex("dbo.PaymentNoticeRes", "FhirReleaseId");
            CreateIndex("dbo.PaymentReconciliationRes", "FhirReleaseId");
            CreateIndex("dbo.PersonRes", "FhirReleaseId");
            CreateIndex("dbo.PlanDefinitionRes", "FhirReleaseId");
            CreateIndex("dbo.PractitionerRes", "FhirReleaseId");
            CreateIndex("dbo.PractitionerRoleRes", "FhirReleaseId");
            CreateIndex("dbo.ProcedureRes", "FhirReleaseId");
            CreateIndex("dbo.ProcedureRequestRes", "FhirReleaseId");
            CreateIndex("dbo.ProcessRequestRes", "FhirReleaseId");
            CreateIndex("dbo.ProcessResponseRes", "FhirReleaseId");
            CreateIndex("dbo.ProvenanceRes", "FhirReleaseId");
            CreateIndex("dbo.QuestionnaireRes", "FhirReleaseId");
            CreateIndex("dbo.QuestionnaireResponseRes", "FhirReleaseId");
            CreateIndex("dbo.ReferralRequestRes", "FhirReleaseId");
            CreateIndex("dbo.RelatedPersonRes", "FhirReleaseId");
            CreateIndex("dbo.RequestGroupRes", "FhirReleaseId");
            CreateIndex("dbo.ResearchStudyRes", "FhirReleaseId");
            CreateIndex("dbo.ResearchSubjectRes", "FhirReleaseId");
            CreateIndex("dbo.RiskAssessmentRes", "FhirReleaseId");
            CreateIndex("dbo.ScheduleRes", "FhirReleaseId");
            CreateIndex("dbo.SearchParameterRes", "FhirReleaseId");
            CreateIndex("dbo.SequenceRes", "FhirReleaseId");
            CreateIndex("dbo.ServiceDefinitionRes", "FhirReleaseId");
            CreateIndex("dbo.SlotRes", "FhirReleaseId");
            CreateIndex("dbo.SpecimenRes", "FhirReleaseId");
            CreateIndex("dbo.StructureDefinitionRes", "FhirReleaseId");
            CreateIndex("dbo.StructureMapRes", "FhirReleaseId");
            CreateIndex("dbo.SubscriptionRes", "FhirReleaseId");
            CreateIndex("dbo.SubstanceRes", "FhirReleaseId");
            CreateIndex("dbo.SupplyDeliveryRes", "FhirReleaseId");
            CreateIndex("dbo.SupplyRequestRes", "FhirReleaseId");
            CreateIndex("dbo.TaskRes", "FhirReleaseId");
            CreateIndex("dbo.TestReportRes", "FhirReleaseId");
            CreateIndex("dbo.TestScriptRes", "FhirReleaseId");
            CreateIndex("dbo.ValueSetRes", "FhirReleaseId");
            CreateIndex("dbo.VisionPrescriptionRes", "FhirReleaseId");
            AddForeignKey("dbo.AccountRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ActivityDefinitionRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AdverseEventRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AllergyIntoleranceRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AppointmentRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AppointmentResponseRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AuditEventRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.BasicRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.BinaryRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.BodySiteRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.BundleRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CapabilityStatementRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CarePlanRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CareTeamRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ChargeItemRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ClaimRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ClaimResponseRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ClinicalImpressionRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CodeSystemRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CommunicationRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CommunicationRequestRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CompartmentDefinitionRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CompositionRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ConceptMapRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ConditionRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ConsentRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ContractRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CoverageRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DataElementRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DetectedIssueRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DeviceComponentRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DeviceRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DeviceMetricRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DeviceRequestRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DeviceUseStatementRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DiagnosticReportRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DocumentManifestRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DocumentReferenceRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EligibilityRequestRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EligibilityResponseRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EncounterRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EndpointRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EnrollmentRequestRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EnrollmentResponseRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EpisodeOfCareRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ExpansionProfileRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ExplanationOfBenefitRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.FamilyMemberHistoryRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.FlagRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.GoalRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.GraphDefinitionRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.GroupRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.GuidanceResponseRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.HealthcareServiceRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ImagingManifestRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ImagingStudyRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ImmunizationRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ImmunizationRecommendationRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ImplementationGuideRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.LibraryRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.LinkageRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ListRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.LocationRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.MeasureRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.MeasureReportRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.MediaRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.MedicationAdministrationRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.MedicationDispenseRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.MedicationRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.MedicationRequestRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.MedicationStatementRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.MessageDefinitionRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.MessageHeaderRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.NamingSystemRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.NutritionOrderRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ObservationRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.OperationDefinitionRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.OperationOutcomeRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.OrganizationRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ParametersRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PatientRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PaymentNoticeRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PaymentReconciliationRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PersonRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PlanDefinitionRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PractitionerRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PractitionerRoleRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ProcedureRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ProcedureRequestRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ProcessRequestRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ProcessResponseRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ProvenanceRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.QuestionnaireRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.QuestionnaireResponseRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ReferralRequestRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.RelatedPersonRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.RequestGroupRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ResearchStudyRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ResearchSubjectRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.RiskAssessmentRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ScheduleRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SearchParameterRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SequenceRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ServiceDefinitionRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SlotRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SpecimenRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.StructureDefinitionRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.StructureMapRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SubscriptionRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SubstanceRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SupplyDeliveryRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SupplyRequestRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TaskRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TestReportRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TestScriptRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ValueSetRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
            AddForeignKey("dbo.VisionPrescriptionRes", "FhirReleaseId", "dbo._FhirRelease", "Id", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.VisionPrescriptionRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ValueSetRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.TestScriptRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.TestReportRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.TaskRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.SupplyRequestRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.SupplyDeliveryRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.SubstanceRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.SubscriptionRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.StructureMapRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.StructureDefinitionRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.SpecimenRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.SlotRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ServiceDefinitionRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.SequenceRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.SearchParameterRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ScheduleRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.RiskAssessmentRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ResearchSubjectRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ResearchStudyRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.RequestGroupRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.RelatedPersonRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ReferralRequestRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.QuestionnaireResponseRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.QuestionnaireRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ProvenanceRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ProcessResponseRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ProcessRequestRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ProcedureRequestRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ProcedureRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.PractitionerRoleRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.PractitionerRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.PlanDefinitionRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.PersonRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.PaymentReconciliationRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.PaymentNoticeRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.PatientRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ParametersRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.OrganizationRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.OperationOutcomeRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.OperationDefinitionRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ObservationRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.NutritionOrderRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.NamingSystemRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.MessageHeaderRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.MessageDefinitionRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.MedicationStatementRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.MedicationRequestRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.MedicationRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.MedicationDispenseRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.MedicationAdministrationRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.MediaRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.MeasureReportRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.MeasureRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.LocationRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ListRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.LinkageRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.LibraryRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ImplementationGuideRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ImmunizationRecommendationRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ImmunizationRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ImagingStudyRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ImagingManifestRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.HealthcareServiceRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.GuidanceResponseRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.GroupRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.GraphDefinitionRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.GoalRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.FlagRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.FamilyMemberHistoryRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ExplanationOfBenefitRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ExpansionProfileRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.EpisodeOfCareRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.EnrollmentResponseRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.EnrollmentRequestRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.EndpointRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.EncounterRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.EligibilityResponseRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.EligibilityRequestRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.DocumentReferenceRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.DocumentManifestRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.DiagnosticReportRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.DeviceUseStatementRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.DeviceRequestRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.DeviceMetricRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.DeviceRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.DeviceComponentRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.DetectedIssueRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.DataElementRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.CoverageRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ContractRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ConsentRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ConditionRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ConceptMapRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.CompositionRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.CompartmentDefinitionRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.CommunicationRequestRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.CommunicationRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.CodeSystemRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ClinicalImpressionRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ClaimResponseRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ClaimRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ChargeItemRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.CareTeamRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.CarePlanRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.CapabilityStatementRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.BundleRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.BodySiteRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.BinaryRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.BasicRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.AuditEventRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.AppointmentResponseRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.AppointmentRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.AllergyIntoleranceRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.AdverseEventRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.ActivityDefinitionRes", "FhirReleaseId", "dbo._FhirRelease");
            DropForeignKey("dbo.AccountRes", "FhirReleaseId", "dbo._FhirRelease");
            DropIndex("dbo.VisionPrescriptionRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ValueSetRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.TestScriptRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.TestReportRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.TaskRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.SupplyRequestRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.SupplyDeliveryRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.SubstanceRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.SubscriptionRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.StructureMapRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.StructureDefinitionRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.SpecimenRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.SlotRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ServiceDefinitionRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.SequenceRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.SearchParameterRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ScheduleRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.RiskAssessmentRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ResearchSubjectRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ResearchStudyRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.RequestGroupRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.RelatedPersonRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ReferralRequestRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.QuestionnaireResponseRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.QuestionnaireRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ProvenanceRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ProcessResponseRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ProcessRequestRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ProcedureRequestRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ProcedureRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.PractitionerRoleRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.PractitionerRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.PlanDefinitionRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.PersonRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.PaymentReconciliationRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.PaymentNoticeRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.PatientRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ParametersRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.OrganizationRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.OperationOutcomeRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.OperationDefinitionRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ObservationRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.NutritionOrderRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.NamingSystemRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.MessageHeaderRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.MessageDefinitionRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.MedicationStatementRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.MedicationRequestRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.MedicationRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.MedicationDispenseRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.MedicationAdministrationRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.MediaRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.MeasureReportRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.MeasureRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.LocationRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ListRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.LinkageRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.LibraryRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ImplementationGuideRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ImmunizationRecommendationRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ImmunizationRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ImagingStudyRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ImagingManifestRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.HealthcareServiceRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.GuidanceResponseRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.GroupRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.GraphDefinitionRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.GoalRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.FlagRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.FamilyMemberHistoryRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ExplanationOfBenefitRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ExpansionProfileRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.EpisodeOfCareRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.EnrollmentResponseRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.EnrollmentRequestRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.EndpointRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.EncounterRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.EligibilityResponseRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.EligibilityRequestRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.DocumentReferenceRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.DocumentManifestRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.DiagnosticReportRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.DeviceUseStatementRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.DeviceRequestRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.DeviceMetricRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.DeviceRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.DeviceComponentRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.DetectedIssueRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.DataElementRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.CoverageRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ContractRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ConsentRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ConditionRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ConceptMapRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.CompositionRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.CompartmentDefinitionRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.CommunicationRequestRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.CommunicationRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.CodeSystemRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ClinicalImpressionRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ClaimResponseRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ClaimRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ChargeItemRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.CareTeamRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.CarePlanRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.CapabilityStatementRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.BundleRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.BodySiteRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.BinaryRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.BasicRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.AuditEventRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.AppointmentResponseRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.AppointmentRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.AllergyIntoleranceRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.AdverseEventRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.ActivityDefinitionRes", new[] { "FhirReleaseId" });
            DropIndex("dbo.AccountRes", new[] { "FhirReleaseId" });
            AlterColumn("dbo.VisionPrescriptionRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ValueSetRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.TestScriptRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.TestReportRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.TaskRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.SupplyRequestRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.SupplyDeliveryRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.SubstanceRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.SubscriptionRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.StructureMapRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.StructureDefinitionRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.SpecimenRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.SlotRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ServiceDefinitionRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.SequenceRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.SearchParameterRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ScheduleRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.RiskAssessmentRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ResearchSubjectRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ResearchStudyRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.RequestGroupRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.RelatedPersonRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ReferralRequestRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.QuestionnaireResponseRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.QuestionnaireRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ProvenanceRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ProcessResponseRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ProcessRequestRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ProcedureRequestRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ProcedureRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.PractitionerRoleRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.PractitionerRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.PlanDefinitionRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.PersonRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.PaymentReconciliationRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.PaymentNoticeRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.PatientRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ParametersRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.OrganizationRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.OperationOutcomeRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.OperationDefinitionRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ObservationRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.NutritionOrderRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.NamingSystemRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.MessageHeaderRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.MessageDefinitionRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.MedicationStatementRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.MedicationRequestRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.MedicationDispenseRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.MedicationAdministrationRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.MedicationRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.MediaRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.MeasureReportRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.MeasureRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.LocationRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ListRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.LinkageRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.LibraryRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ImplementationGuideRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ImmunizationRecommendationRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ImmunizationRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ImagingStudyRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ImagingManifestRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.HealthcareServiceRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.GuidanceResponseRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.GroupRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.GraphDefinitionRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.GoalRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.FlagRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.FamilyMemberHistoryRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ExplanationOfBenefitRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ExpansionProfileRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.EpisodeOfCareRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.EnrollmentResponseRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.EnrollmentRequestRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.EndpointRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.EncounterRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.EligibilityResponseRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.EligibilityRequestRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.DocumentReferenceRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.DocumentManifestRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.DiagnosticReportRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.DeviceUseStatementRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.DeviceRequestRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.DeviceMetricRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.DeviceComponentRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.DeviceRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.DetectedIssueRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.DataElementRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.CoverageRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ContractRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ConsentRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ConditionRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ConceptMapRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.CompositionRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.CompartmentDefinitionRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.CommunicationRequestRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.CommunicationRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.CodeSystemRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ClinicalImpressionRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ClaimResponseRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ClaimRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ChargeItemRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.CareTeamRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.CarePlanRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.CapabilityStatementRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.BundleRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.BodySiteRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.BinaryRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.BasicRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.AuditEventRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.AppointmentResponseRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.AppointmentRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.AllergyIntoleranceRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.AdverseEventRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.ActivityDefinitionRes", "FhirReleaseId", c => c.Int());
            AlterColumn("dbo.AccountRes", "FhirReleaseId", c => c.Int());
        }
    }
}
